### ISSUE TITLE
Proposal: Get rid of spring dependency for portability

### ISSUE THREAD

**Issue by veqtor** [ethereum/ethereumj#1003]
Motivation:
Using spring for dependency injection creates a needless dependency on a framework that is optimized for servers and desktop applications.
By getting rid of spring and working towards a modular pluggable component structure, parts of ethereumj can be used in mobile and embedded applications.

Solution:
* Move spring configuration into a separate module
* Isolate all the core components from the spring context, inject all dependencies in constructor, use builders when necessary

**Comment by bitsabhi** [comment]
Also DI often relies heavily on reflection which is not good for performance reasons.

**Comment by veqtor** [comment]
Another thing I would like to remove is dependency on "config files"
This prevents platform-agnosticism in that there are a lot of hard-coded defaults, that aren't even well documented.

**Comment by pschweitz** [comment]
Removing the dependency from the spring framework could also help to resolve further issues as well:

Using JDK11 in early access for testing:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$2 (file:/home/interactive/Recordin/lib/spring-core-4.2.0.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: **All illegal access operations will be denied in a future release**

**Comment by mkalinin** [comment]
Superseded by https://github.com/ethereum/ethereumj/issues/1007
