### ISSUE TITLE
No parent on the chain log messages

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/ethereumj#1005]
While trying to sync Ethereum-Harmony my node is generating a ton of error messages stating `No parent on the chain for block.number:` followed by various block numbers in the high 3M range

The first occurrence of this log entry appears to be:
`No parent on the chain for block.number: 3844481`

The node was ran with default command `gradlew runMain` it ran for about a day or so in Fast Sync mode before this started happening.

**Comment by zilm13** [comment]
@MysticRyuujin could you add log here, some part before "No parent", including "No parent".
Latest 1Mb would be enough.
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by MysticRyuujin** [comment]
Here's the latest log
[harmony.out.zip](https://github.com/ethereum/ethereumj/files/1728247/harmony.out.zip)

**Comment by MysticRyuujin** [comment]
I've been trying to re-sync fresh and I just noticed it happening again. Here are more logs....

[harmonylogs.zip](https://github.com/ethereum/ethereumj/files/1778796/harmonylogs.zip)

**Comment by mkalinin** [comment]
@MysticRyuujin please, check it with latest version now. This conflict should be sorted out

**Comment by MysticRyuujin** [comment]
Using the latest git pull from yesterday, I was able to successfully sync the mainnet! 🎉
