### ISSUE TITLE
Resource conflict with other libraries

### ISSUE THREAD

**Issue by liorregev** [ethereum/ethereumj#1008]
I believe you should avoid having resources in the root of the 'resources' directory since it is not specific to you library and a class-loader could fetch the wrong one if multiple libraries do this.

For example: your 'version.properties' resource conflict with the one in https://github.com/web3j/web3j
and therefore causes NullPointerException 
I have opened a similar [issue](https://github.com/web3j/web3j/issues/365) on that repo, but I think it should be fixed in both

**Comment by zilm13** [comment]
@liorregev Should be fixed with #988 Did you use snapshot? It's not merged in RELEASE until next release.

**Comment by fcorneli** [comment]
When is the next release planned?

**Comment by mkalinin** [comment]
in about a months

**Comment by mkalinin** [comment]
@fcorneli we got released [1.7.0](https://github.com/ethereum/ethereumj/releases/tag/1.7.0). Please check it

**Comment by fcorneli** [comment]
ok, awaiting for Maven repo availability.

**Comment by mkalinin** [comment]
cool 👍
