### ISSUE TITLE
Can someone please explain this difference with geth?

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/ethereumj#1011]
https://github.com/ethereum/ethereumj/blob/de97ee39bdf4fdff2706f356c6f6783b73420b9b/ethereumj-core/src/main/java/org/ethereum/crypto/EthereumIESEngine.java#L252

I am comparing sources with geth and I see that the ecies encrypt call in geth is https://github.com/ethereum/go-ethereum/blob/da41a7258d94fb35113f3b2da3635c7c451e5831/p2p/rlpx.go#L461 initialized with a 2 byte big endian , whereas in the J version there is a 4 byte array. Is this significant?

**Comment by FrankSzendzielarz** [comment]
@mkalinin Привет. Yes, those two bytes. Actually I have a detailed explanation of what I am looking at here: https://ethereum.stackexchange.com/questions/40109/why-is-there-a-difference-between-the-ecies-encryption-implementation-in-ethereu 
Maybe there is no significance to this difference, but I would be very happy to learn why if so.

**Comment by mkalinin** [comment]
(This)[https://github.com/ethereum/ethereumj/blob/de97ee39bdf4fdff2706f356c6f6783b73420b9b/ethereumj-core/src/main/java/org/ethereum/net/rlpx/EncryptionHandshake.java#L177] is the right place to start comparing that piece of code from Geth with EthereumJ's code.

**Comment by FrankSzendzielarz** [comment]
Ah! Yes, it is MacData that is the 2 byte big-endian (message length). Thanks.
