### ISSUE TITLE
ethereumj.conf issue

### ISSUE THREAD

**Issue by FlyFire-Young** [ethereum/ethereumj#1026]
The role of each parameter

**Comment by mkalinin** [comment]
did you read the comments above each parameter?

**Comment by FlyFire-Young** [comment]
yes,but I still don't understand,are there any more detailed annotations or wiki?

**Comment by mkalinin** [comment]
Unfortunately, no. There is a wiki which describes certain use cases, you may take a look [here](https://github.com/ether-camp/ethereum-harmony/wiki)

**Comment by FlyFire-Young** [comment]
thanks！！
