### ISSUE TITLE
Exception： Is there an unresolvable circular reference ‘SyncPool’

### ISSUE THREAD

**Issue by fangshun1980** [ethereum/ethereumj#1029]
**Exception segment:**
org.ethereum.sync.SyncPool

private Blockchain blockchain;

@Autowired
public SyncPool(final SystemProperties config, final Blockchain blockchain) {
        this.config = config;
        this.blockchain = blockchain;
    }

**modify ：**
@Autowired
 private Blockchain blockchain;
@Autowired
public SyncPool(final SystemProperties config) {
     this.config = config;
//    this.blockchain = blockchain;
}

**Comment by mkalinin** [comment]
The fix is a part of [1.7.0](https://github.com/ethereum/ethereumj/releases/tag/1.7.0). Check it please

**Comment by fangshun1980** [comment]
ok，I've checked it.
