### ISSUE TITLE
 Can this project be created with maven

### ISSUE THREAD

**Issue by liming1010** [ethereum/ethereumj#1030]
sorry, 
I don't have a gradle environment，
Can this project be created with maven？

**Comment by mkalinin** [comment]
we don't support Maven. what is the problem with Gradle? if you run `./gradlew command` it installs Gradle in automatic fashion.

**Comment by mkalinin** [comment]
@liming1010 is this issue still actual?

**Comment by kishansagathiya** [comment]
@mkalinin I think it would be safe to close this issue
