### ISSUE TITLE
after git clone and gradlew build,there are some errors

### ISSUE THREAD

**Issue by huanleyuan** [ethereum/ethereumj#1031]
I haven't change anything,why some errors like this:
1127 tests completed, 3 failed, 109 skipped
:ethereumj-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ethereumj-core:test'.
> There were failing tests. See the report at: file:///H:/block%20chain/workspace/ethereumj/ethereumj-core/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by huanleyuan** [comment]
1) java.lang.AssertionError: at 
    org.ethereum.config.SystemPropertiesTest.testPunchBindIp(SystemPropertiesTest.java:71)
2) RuntimeException: Problem loading genesis file from /ethereumj/ethereumj-
     core/build/resources/main/genesis/frontier-test.json

**Comment by zilm13** [comment]
@huanleyuan could you point to exact commit number where you run tests?

**Comment by kishansagathiya** [comment]
@zilm13 This should be closed, I think. It is pretty old. Plus since latest commit builds, so I don't think there is a point looking into this, is there?
