### ISSUE TITLE
Replace `Hex.toHexString` in logging, toString etc to safer alternative

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#1032]
Fails on null, pain.

**Comment by kishansagathiya** [comment]
@zilm13 This looks like something simple that I can pick up, is it?

**Comment by zilm13** [comment]
@kishansagathiya sure, check `ByteUtil.toHexString`, it exists, but not used in all hex logging.

**Comment by kishansagathiya** [comment]
Tried few different libraries, failed to find any null safe hex encoder.
 
@zilm13 
org.apache.commons.codec.binary.Hex.encodeHexString()
org.apache.soap.encoding.Hex.encode(null)
I guess spongycastle uses bouncycastle internally, but tried that anyway
org.bouncycastle.util.encoders.Hex.encode(null)

How about adding a null check before every call or create our own method that wraps this function with a null check, 
I believe if null, we would be throwing illigalArgumentError right?

**Comment by zilm13** [comment]
@kishansagathiya what you don't like in `org.ethereum.util.ByteUtil.toHexString`which I mentioned before?

**Comment by kishansagathiya** [comment]
@zilm13 I thought that is one more thing that is not null safe method :), 

Anyway org.ethereum.util.ByteUtil.toHexString is perfect. I will use it.

**Comment by kishansagathiya** [comment]
@zilm13 
I believe you don't want to replace all Hex.toHexString() to ByteUtil.toHexUtil, right? Otherwise I can just do a replace all.

For something like https://github.com/ethereum/ethereumj/blob/4cdc799a2e957110656a38bf9a40769b5e9c2630/ethereumj-core/src/main/java/org/ethereum/config/SystemProperties.java#L687
You would rather want to through an error instead of setting to null,
Right?

**Comment by zilm13** [comment]
@kishansagathiya I want to change `Hex.toHexString()` to `ByteUtil.toHexUtil` in logging only. So we could see at least part of data in logs if smth is null (instead of Exception).

**Comment by zilm13** [comment]
resolved with #1069
