### ISSUE TITLE
Adopt new Transaction Tests format

### ISSUE THREAD

**Issue by mkalinin** [ethereum/ethereumj#1038]
https://github.com/ethereum/tests/issues/373 describes the format

**Comment by kishansagathiya** [comment]
@mkalinin Has this issue been tackled? If not, can you give me some pointers on this? Also some more description on what this issue is about?

**Comment by mkalinin** [comment]
This issue is about adopting new test format for [GitHubTransactionTest](https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/test/java/org/ethereum/jsontestsuite/GitHubTransactionTest.java) suite. The link above gives a description of the format that should be adopted. Test sources can be found [here](https://github.com/ethereum/tests/tree/develop/TransactionTests).

**Comment by tenghuanhe** [comment]
@mkalinin @kishansagathiya Is anyone working on this or it has been done now?  If not, I would like to have a try:)

**Comment by kishansagathiya** [comment]
@tenghuanhe I am not working on this

**Comment by tenghuanhe** [comment]
> @tenghuanhe I am not working on this

@kishansagathiya thanks for your reply

**Comment by mkalinin** [comment]
Addressed by https://github.com/ethereum/ethereumj/pull/1246
