### ISSUE TITLE
Getting over block 2 283 415

### ISSUE THREAD

**Issue by uzoltan** [ethereum/ethereumj#1040]
I cloned the develop branch recently, and starting running the Start class to synch the blockchain to my PC. When I got to this block in the title, all I see in the console is logs about IDLE peers and measures about TCP/UDP speed, but the sync wont progress. After some googling, I saw this is not a new problem, but what could I do/try to help the sync move forward? I could not find an answer for this, not for ethereumj at least.

update: Waited half a day, problem solved itself, closing the thread.

update2: never mind, it just started the sync from a few hundred blocks earlier.

**Comment by mkalinin** [comment]
You better set `sync.fast.enabled = true` in the config file (use `ethereumj.conf` or better create a new called `user.conf` with options that you want to override). Fast sync passes much faster than the regular one. Here https://github.com/ethereum/ethereumj/issues/586#issuecomment-276981758 is the list of attack waves on the Mainnet. Processing of these blocks is really slow
