### ISSUE TITLE
validating block difficulty with bare minimum header data

### ISSUE THREAD

**Issue by baaa** [ethereum/ethereumj#1044]
Hi, 
this may or may not be a feature request. May be there is chance to do this with existing code and I am not able to find it.

with the go implementation of ethash I can do:

```
import(
    "github.com/ethereum/ethash"
    "github.com/ethereum/go-ethereum/common"
)
verifyMe := Block{
	number:      height,
	hashNoNonce: common.HexToHash(hashNoNonce),
	difficulty:  someBigIntegerDifficulty,
	nonce:       nonce,
	mixDigest:   common.HexToHash(mixDigest),
}
hasher := ethash.New()
hasher.Verify(verifyMe)
```
which just satisfies this nonce is valid for this hash in this height and difficulty.

In Ethereumj to create a block header I have to provide all sorts of other data (if I am not actually missing anything) Is there a way to replicate above snippet in Java with Ethereumj?

**Comment by mkalinin** [comment]
In current implementation it's possible to verify entire `BlockHeader` only. And you have to create one. Basically, verification requires `hashNoNonce` field which is calculated from almost all header fields and you have to get it somehow. What your case exactly is?

**Comment by baaa** [comment]
the use case is mining, as you can see I already have a calculated `hashNoNonce value.

using a sample block from `ethereumj/ethereumj-core/src/test/java/org/ethereum/mine/EthashTest.java` I do something like:

```
long height=49045;
string hashNoNonce="f901eba0809870664d9a43cf1827aa515de6374e2fad1bf64290a9f261dd49c525d6a0efa01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794f927a40c8b7f6e07c5af7fa2155b4864a4112b13a010c8ec4f62ecea600c616443bcf527d97e5b1c5bb4a9769c496d1bf32636c95da056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000086015a1c28ae5e82bf958302472c808455c4e47b99476574682f76312e302e312f6c696e75782f676f312e342e32";
string nonce="e2ff1b6435006517";
difficulty=ByteUtil.longToBytes(hexToLong("015a1c28ae5e"));
EthashAlgo ethash = new EthashAlgo();
long cacheSize = ethash.getParams().getCacheSize(height);
long fullSize = ethash.getParams().getFullSize(height);
byte[] seedHash = ethash.getSeedHash(height);

int[] cache = ethash.makeCache(cacheSize, seedHash);

byte[] blockTruncHash = sha3( RLP.encodeElement(ByteUtil.hexStringToBytes(hashNoNonce)) );

Pair<byte[], byte[]> pair = ethash.hashimotoLight(fullSize, cache, blockTruncHash, ByteUtil.longToBytes( Miner.hexToLong(nonce)));

byte[] boundary = BigIntegers.asUnsignedByteArray(32, BigInteger.ONE.shiftLeft(256).divide(new BigInteger(1, difficulty)))

Assert.assertTrue(FastByteComparisons.compareTo(pair.getRight(), 0, 32, boundary, 0, 32) < 0);
```
As you can see this is almost identical to `realBlockValidateTest1` 

I took `getPowBoundary` method out, and I am also providing the hashNoNonce value (I took this value from the test by doing a print of `b.getHeader().getEncodedWithoutNonce()`)

This still says hash is invalid.

**Comment by baaa** [comment]
Hi,
I just figured out how to do this, using `Ethash` and `EthashAlgo` classes and I moved some functions from `BlockHeader` to outside, It is a bit convoluted but it works.
