### ISSUE TITLE
gradlew shadowJar doesn't work

### ISSUE THREAD

**Issue by stasbar** [ethereum/ethereumj#1047]
Hello.
I'm unable to build fat jar with `./gradlew clean shadowJar`
FAILURE: Build failed with an exception.

* What went wrong:
Task 'shadowjar' not found in root project 'ethereumj'.

Any suggestion why ? workaround ?

**Comment by mkalinin** [comment]
It doesn't work cause shadow plugin is not a part of gradle config

**Comment by stasbar** [comment]
Right. So I need to add it manually ? Or is there other way to start it standalone from console.

**Comment by zilm13** [comment]
Resolved with https://github.com/ethereum/ethereumj/pull/1080
Use `./gradlew clean fatJar`
