### ISSUE TITLE
unknown opcode 0xfe interupt evm execution

### ISSUE THREAD

**Issue by ferdiknight** [ethereum/ethereumj#1049]
version: 1.7.2.RELEASE
org.ethereum.vm.VM.java:149 throw an exception when catch an unknown opcode.So the opcode 0xfe hit this line.
0xfe is defined in [solidity instruction](https://github.com/ethereum/solidity/blob/2abc5be7e628c18562f1df546137fcb0748ecbb2/libevmasm/Instruction.h).

I add this opcode definition in org.ethereum.vm.OpCode.java. Skip it and increase the pc to avoid this issue temporary.

Is there any future plan for 0xfe?

**Comment by kishansagathiya** [comment]
@ferdiknight OpCode `0xfe` is not part of the  Virtual Machine Specification in [Ethereum Yellow Paper](http://www.gavwood.com/Paper.pdf) (Appendix G)
So it doesn't seem like it would/should be implemented, but @mkalinin or @zilm13 can confirm if that is the case.

**Comment by mkalinin** [comment]
Yes, `0xfe` indeed is not a defined OpCode. But it's used by `assert` and `throw` Solidity statements to abort the execution with consuming all the gas provided for the Tx. Check this post  https://medium.com/blockchannel/the-use-of-revert-assert-and-require-in-solidity-and-the-new-revert-opcode-in-the-evm-1a3a7990e06e

**Comment by kishansagathiya** [comment]
@mkalinin Does that mean that we have to add support for `0xfe` ?

**Comment by ferdiknight** [comment]
Ok,got it. Thanks for reply.
