### ISSUE TITLE
Lack of commonly validating blocks if sync.fast.skipHistory = true

### ISSUE THREAD

**Issue by mkalinin** [ethereum/ethereumj#1058]

**Comment by zilm13** [comment]
Also we are downloading headers but cannot use it for GetBlockHeaders answer

**Comment by kishansagathiya** [comment]
Looks like this is closed with https://github.com/ethereum/ethereumj/pull/1060. In that case we should close this.

**Comment by zilm13** [comment]
@kishansagathiya yeah
resolved with #1060 and #1074
