### ISSUE TITLE
New fork chainitem will be discared in the segment

### ISSUE THREAD

**Issue by majingfenggithub** [ethereum/ethereumj#1059]
If we add the items with the same hash but with differenet father hash and number, segment will do  the comparation to check whether or not this chianItem exsist or not. But the comparation is just compare the hash , not include the number and parent has,  if the hash is the same, it will think the same chainitem. This will resolved in item lost. See the list. 

t.addItem(2, intToBytes(22), intToBytes(1));
t.addItem(3, intToBytes(22), intToBytes(21));

How to : please modify the code in chainItem.java for equals method

**Comment by mkalinin** [comment]
It's assumed that there could not be different chain items with equal hash. As it's impossible that two different blocks have same hash.

**Comment by majingfenggithub** [comment]
Yes, I agree.
