### ISSUE TITLE
Refactor VMHook

### ISSUE THREAD

**Issue by mkalinin** [ethereum/ethereumj#1070]
VM hooks are currently not thread safe due to sharing one `VMHook` instance across all `VM` instances. For example, it turns into concurrent modifications because of `PendingState` processing. A straightforward way of solving this issue is to instantiate own `VMHook` instance for each `VM`. One of the way to achieve this is to introduce `VMHookFactory`

**Comment by RichardH92** [comment]
It looks like the `VMHook` interface is never implemented. Is that correct? Does this ticket involve creating the implementation as well?

**Comment by mkalinin** [comment]
Actually its implementation depends on client needs, thus it's assumed to be implemented on client's side.

**Comment by RichardH92** [comment]
Gotcha. I'm assuming then that `VMHookFactory` would be an interface implemented by the client as well? And that `VMHookFactory` would be a static field shared across each `VM`, but the `VM` constructor would just call `VMHookFactory.build()` or something similar to get a unique `VMHook` per `VM`?

**Comment by RichardH92** [comment]
Is there a user case for different `VM` instantiations to have different `VMHook` implementations?

**Comment by mkalinin** [comment]
> Is there a user case for different VM instantiations to have different VMHook implementations?

Not for now I think. This update is intended to solve concurrency issue that occurs due to sharing same `VMHook` instance between several `VM`s
