### ISSUE TITLE
Could not find artifact org.ethereum:solcJ-all:jar:0.4.8

### ISSUE THREAD

**Issue by xiongben-tongxue** [ethereum/ethereumj#1071]
Maven project Error
[ERROR] Failed to execute goal on project usdgservice: Could not resolve dependencies for project com.gws:usdgservice:jar:1.0.0: Could not find artifact org.ethereum:solcJ-all:jar:0.4.8 in central-repository (http://central.maven.org/maven2/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

when I write pom.xml

		<dependency>
			<groupId>org.ethereum</groupId>
			<artifactId>ethereumj-core</artifactId>
			<version>1.6.3-RELEASE</version>
		</dependency>

[ERROR] Failed to execute goal on project usdgservice: Could not resolve dependencies for project com.gws:usdgservice:jar:1.0.0: Could not find artifact org.ethereum:solcJ-all:jar:0.4.8 in central-repository (http://central.maven.org/maven2/) -> [Help 1]
[ERROR]

**Comment by zilm13** [comment]
@xiongben-tongxue did it help?
