### ISSUE TITLE
bucket size

### ISSUE THREAD

**Issue by ayrat555** [ethereum/ethereumj#1075]
https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/net/dht/Bucket.java#L59

It looks like not empty bucket split if it size is bigger than 5. But by specification bucket size is 16

**Comment by mkalinin** [comment]
Reading from the [spec](https://github.com/ethereum/wiki/wiki/Kademlia-Peer-Selection):
_Each row contains at most k peers ... , where k is a parameter (not necessarily global) with typical values betwen 5 and 20._

**Comment by mkalinin** [comment]
Yes, you're right. And options which are used in discovery can be found here:
https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/net/rlpx/discover/table/KademliaOptions.java#L24
`Bucket` class is not used across the codebase
