### ISSUE TITLE
Enhance the new branck creation efficiency

### ISSUE THREAD

**Issue by majingfenggithub** [ethereum/ethereumj#1106]
for the file: package org.ethereum.db.prune. Segment;

I have suggetsion, please add the break in this method. once we have detected it is the sun of forkitem,  absolutely this is a branch fork, no need contiune do the comparation, exit it. 

private void connectFork(ChainItem item) {
        for (Chain fork : forks) {
            if (fork.contains(item))
                return;
        }
        if (root.isParentOf(item)) {
            branch(item);
        } else {
            for (ChainItem mainItem : main.items) {
                if (mainItem.isParentOf(item)) {
                    branch(item);
                }
            }

            for (Chain fork : forks) {
                if (fork.connect(item)) {
                    return;
                }
            }

            List<Chain> branchedForks = new ArrayList<>();
            for (Chain fork : forks) {
                for (ChainItem forkItem : fork.items) {

                    if (forkItem.isParentOf(item)) {
                        branchedForks.add(new Chain(item));
// add this

                        _break;_ 
                    }
                }
            }
            forks.addAll(branchedForks);
        }
    }

**Comment by mkalinin** [comment]
Your note looks reasonable! But I don't think this update brings a valuable boost to the performance. The other thing against this update is that we're going to replace pruner with a new one sooner than later, details are here https://github.com/ethereum/ethereumj/issues/1100. New pruner won't have to manage chain Segment at all. 
Thanks for keeping an eye on the code! 👍
