### ISSUE TITLE
Seeing account balances

### ISSUE THREAD

**Issue by redskate** [ethereum/ethereumj#1115]
Hi

I am using ethereumJ (thanks!!!) to create a private network which I later would like to use publically.
Furthermore, I an developing / debugging / running eclipse Neon 2 on mac Sierra.

In the genesis file I created some special users (together with their private keys) with a balance of 10.

The network starts at a port ... say 20201. To humanly monitor the state of the net I use ethereum-harmony also listening to that port.

How can I see the per genesis generated accounts and their balance?

On harmony I can create a wallet and "import" some genesis users, harmony shows "0" instead of "10". Any RPC commands (getBalance ) show "0"

In Java/Eclipse how can I browse in debug the ethereum object in order to discover those accounts ??? I would be nice to open a wallet in java to check all that directly - how?

The difficulty is set in the genesis file to a very low value: 1. Do I have to wait ... how long ? 

It seems that there are some specialities (non visibilities) in ethereum-harmony which prevents harmony to access the genesis users on the private network...

Thanks a lot for any help on that!!!!!

Regards

**Comment by redskate** [comment]
OK, probably I do not see any balance because those account in genesis are not ("yet") mined.

**Comment by zilm13** [comment]
@redskate 
1. Does harmony use the same genesis and network config (networkId etc)? It should. Also it should be synchronized to the same block that's the last for miner, but if you have alloc in genesis, these accounts will be shown from the beginning.
2. Balances in harmony are shown in eth, allocs in genesis are in wei (10^-18 eth), so you need 1_000_000_000_000_000_000 wei for 1 eth.
