### ISSUE TITLE
Is there a way to scan an ethereumj using etherscan.io or other?

### ISSUE THREAD

**Issue by redskate** [ethereum/ethereumj#1117]
Hi, I would need to look into your ethereumJ network using a client which opens the network and shows what is inside (similar as etherscan.io) - I tried using harmony or mist but did not succeed.

Is there a concise way to tune an ethererum scan graphical program so that one can look and interact to a running ethereumj instance ?

Can therescan.io be somehow used for this purpose (how) ?

Thank you

**Comment by mkalinin** [comment]
Block explorer like etherscan.io works with its own Ethereum node infrastructure. If you need to explore private network you may setup your own explorer for it, all you need to get EthereumJ data in the explorer is to connect nodes which are used by explorer with EthereumJ nodes.
Wondering for the case you'd like to solve with block explorer?

**Comment by redskate** [comment]
Hi @mkalinin do you mean, I could develop one node explorer? What do you mean by "setup" ? Could you be more explicit please? 

etherscan.io is hence not available for browsing a private ethereumj networt. Pity.

**Comment by mkalinin** [comment]
I just answered your question whether etherscan.io can be used to achieve your goal or not and how. But you need an etherscan.io copy for that private net. 
What you're requesting is a handy feature. Can you be more specific on what exact information you would need?

**Comment by redskate** [comment]
Thank you for your answer on etherscan.io (not avail), @mkalinin 

And I did not understand "setup".

I would like to take a (now) available block scan system like etherscan.io, bring it to a server and then configuring it in order for it to point at my current ethererumj peer. So I would hope someone tell me something like: "look, there is this and that system you could use as a private etherscan.io system". The information I need (from a block scanner) is to see the chain, contracts, accounts, etc. in a human readable way. In my eclipse debugger I get to everything but ... hugh....

Hope now I could clarify

**Comment by mkalinin** [comment]
> I would like to take a (now) available block scan system like etherscan.io, bring it to a server and then configuring it in order for it to point at my current ethererumj peer.

This is what I meant by "setup"

You may try this one: https://github.com/blk-io/blk-explorer-free, I haven't used it though, just googled.

**Comment by redskate** [comment]
I will :) thank you @mkalinin
