### ISSUE TITLE
This is a pre-release compiler version, please do not use it in production.

### ISSUE THREAD

**Issue by redskate** [ethereum/ethereumj#1118]
Hi dear community

The title says what is found inside a compiler result using the lines:

					compiler = new SolidityCompiler(config);
					result = compiler.compileSrc(contract.getBytes(), true, true,
					        SolidityCompiler.Options.ABI, SolidityCompiler.Options.BIN);

Am I using the wrong compiler instantiation? 
Do we have (when) a production ready compiler ?

Thanks a lot
Regards

**Comment by mkalinin** [comment]
Resolved by https://github.com/ethereum/ethereumj/commit/d8ecb5eb69ec2f6d3fb59d7e5d204ecc560d6e02
