### ISSUE TITLE
How can I download only portions of the blockchain?

### ISSUE THREAD

**Issue by cekoivisto** [ethereum/ethereumj#1123]
Hello, is it possible to to listen to a wallet address for completed transactions, as well as check the balance of that wallet without syncing the entire blockchain? I know BitcoinJ does this by only syncing the blocks that pertain to the wallet(s) you are following, but I can't figure out how to do it with EthereumJ. Or better yet, is it possible to not download anything at all and just ask other nodes to relay completed transactions and the wallet balance to you?

**Comment by mkalinin** [comment]
What you are asking for is more or less a light client behavior. EthereumJ dones't have this feature yet, check this issue https://github.com/ethereum/ethereumj/issues/602

**Comment by cekoivisto** [comment]
Alright thank you!
