### ISSUE TITLE
Properly initialize a private network

### ISSUE THREAD

**Issue by redskate** [ethereum/ethereumj#1124]
Dear community

Thank you for your ethereumj framework! Seems now all working. Nevertheless I would need to clarify the following points, maybe someone has (had) the same questions ... 

The use I am doing is not creating a coin, but storing (zipped) documents. So I created a system with a bunch of "well-balanced" accounts in the genesis file and started.

1. How should the peer.active conf be properly initialised. I generated a pair (pkey/address) and used one pkey just like below. Is this the right way ??? Who uses this pkey again? (the key should be then stored in the DB...). If I do not provide a nodeid like that ... the miner does not start. (I changed them here a bit to be sure ... they are not abused).

peer.privateKey = 58e23aef07d6a7844987369498a5c5358ad45feed322c1b94f7cab322bc

peer.active = 
[ 
	{
		ip= 10.0.1.120
		port= 20202
		nodeName = "sks1"
		nodeId = aedfbba296bc101ed67808a64ebddc5cr6a908437553d6b852903ca5944bec371351d9b0373911408929b7addc1dab7e016da05c835 <- an older generated node id ... ok?
	} 
]

2. A private network is now running and locally mining (one CPU mining). Contracts are stored, data is stored and retrieved. Work (excluding some open issues) fine!  What is the sense of discovering other peers via the port ? That other miners connect and help mining? Does it make sense in a private network? (maybe my miners ... ?) Do I have to give them the address of the private network to invite them join it? A blockchain is secure the more miners are involved in it. what shell the others know of my private network in order to mine in it ? e.g. the nodeid?  And what would be the reward for them? (nothing, besides the fact that having multiple miners enhance the "ledgers" security).

Thanks a lot!

**Comment by pschweitz** [comment]
Hi,

ethereumj was primarily designed to work as a public blockchain. However it could also work as a private network, but we must adapt the configuration to operate it correctly.

1 - You must maintain the list manually, or update it when in your listener triggers the event corresponding to a new node connection.

2 - You can disable the node discovery in the config
   - You can have miner and not mining nodes, it depend on your platform policy (your choice)
   - Having more miners will increase your platform resilience in case networking issues.
   - Be careful by providing the correct information, another node could connect to your existing nodes, this is something to adapt in order to prevent that.

I would let the other specialist to give additional information if more details could be provided to these first set of answers.

**Comment by redskate** [comment]
Hi

Thank you @pschweitz for your hints.

Yes for the moment "peer discovery" is disabled (there are no peers wanting to point at my ethereum but some of them seems to be "discovered".

The answers to my questions (apparently you are the only one wanting to give advice, thank you) will be found by looking at the Java code - I guess....

**Comment by mkalinin** [comment]
Ha ha! @redskate 
1. This pKey is used to derive node url: `enode://{pub_key}@IP:PORT` where `pub_key` is derived from that pKey. If you don't specify one, then it will be generated and stored in database folder to be presumed between launches.
`peer.active` setting sample can be found [here](https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/resources/ethereumj.conf#L93)

2. It depends on your network topology, how many nodes are there, do you want others to connect to your network easily. If yes, then peer discovery is a thing that will help you to manage your network. If you have a couple of peers and not going to add more capacity here then peer discovery is not necessary and may be turned off. I would not pay much attention to it. To distinguish your private network from the others use custom genesis and set `networkId` to some custom value, latter will distinguish your network on ETH protocol layer. If discovery is essential for your network then don't forget to set boot nodes via `peer.discovery.ip.list`.

**Comment by redskate** [comment]
Thank you @mkalinin 
1. Thank you :)
2. I could set up a second ethereumj node "sks2" on another machine. So If I understand you well, I then need to insert in the peer.discovery.ip.list conf section of the first ethereumj instance "sks1" the enode of "sks2"...

**Comment by mkalinin** [comment]
Well, whether peer is miner or not is defined by its config, with no regard to network configuration. I'd treat miner as one of bootstrap nodes in private network. Thus new connected peers will be able to start its discovery from the oldest network node which knows a lot about other peers.

**Comment by redskate** [comment]
ok :) thank you @mkalinin - I feel I understood what you wrote, I'll try to set it up as time comes.
