### ISSUE TITLE
Question about Solidity constant function using ethereumj evm

### ISSUE THREAD

**Issue by reverde** [ethereum/ethereumj#1148]
I am trying to understand the logic how evm deal with constant function in ethereumj. It seems when I trigger a constant function, evm will regard it as a normal call and push the transaction in a block. But, from what I understand, the transaction contain constant function should not be pushed to the network. So, can you point out how evm in ethereumj distinguish constant function from other functions? 

Thanks!

**Comment by reverde** [comment]
@zilm13 , Thank you for the response!  So, if I want to call a constant function, I need to callConstantImpl(). 
Some following questions:
1. What if I want to trigger a function which changes the blockchain states? I find submitTransaction() in the same file. Is that means I should build a transaction and use this function to submit my tx?
2. What if I suppose to call a constant function but not using callConstantImpl(). Instead, I submit a transaction to the network use submitTransaction(might be a not suggested way, but can I do this ). Will it spread to all the node or actually we already have mechanism to prevent this happen? 

Trying to do some develop basing on ethereumj. Do you guys have any official guide to read or slack I can join?

Thanks.

**Comment by zilm13** [comment]
@reverde you need to call one of two public methods: `public ProgramResult callConstantFunction(String receiveAddress, CallTransaction.Function function, Object... funcArgs)` or  `public ProgramResult callConstantFunction(String receiveAddress, ECKey senderPrivateKey, CallTransaction.Function function, Object... funcArgs)` if the result of the call could depend on the caller.

1. if you don't need to submit it to the network but just want to see what it changes etc, look at https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/samples/StandaloneBlockchainSample.java or PendingStateImpl logic if you want to execute it on the current chain without saving changes
2. I guess you could create constant call which will not refused to go outside if you use from address with some money on it and set gasPrice enough high to be not rejected by miners. When you create it using `ethereum.callConstantFunction`, gasPrice = 0 and it will be rejected by `PendingStateImpl` even if you use from address with some ether and try to send it.

You could join our gitter: https://gitter.im/ethereum/ethereumj

**Comment by reverde** [comment]
Thank you.
