### ISSUE TITLE
Constantinople

### ISSUE THREAD

**Issue by mkalinin** [ethereum/ethereumj#1149]
EIPs included in Constantinople:
- [x] [EIP 145](https://eips.ethereum.org/EIPS/eip-145): Bitwise shifting instructions in EVM, https://github.com/ethereum/ethereumj/pull/1167
- [x] [EIP 1014](https://eips.ethereum.org/EIPS/eip-1014): Skinny CREATE2, https://github.com/ethereum/ethereumj/pull/1178
- [x] [EIP 1052](https://eips.ethereum.org/EIPS/eip-1052): EXTCODEHASH opcode, https://github.com/ethereum/ethereumj/pull/1162
- [x] [EIP 1283](https://eips.ethereum.org/EIPS/eip-1283): Net gas metering for SSTORE without dirty maps, https://github.com/ethereum/ethereumj/pull/1173
- [x] [EIP 1234](https://eips.ethereum.org/EIPS/eip-1234): Constantinople Difficulty Bomb Delay and Block Reward Adjustment, https://github.com/ethereum/ethereumj/pull/1181

**Comment by mkalinin** [comment]
I'll take [EIP 1087](https://eips.ethereum.org/EIPS/eip-1087)

**Comment by zilm13** [comment]
I'll take  EIP 1052

**Comment by zilm13** [comment]
EIP-145 #1167

**Comment by zilm13** [comment]
Taking EIP 1283 instead of dropped 1087

**Comment by zilm13** [comment]
EIP-1014 #1178

**Comment by zilm13** [comment]
EIP-1234 #1181

**Comment by zilm13** [comment]
I'd leave some issue for github Ethereum tests tracking after all Constantinople parts are done: either keep this issue open or create separate one for Constantinople tests. https://github.com/ethereum/tests will be regularly updated with new Constantinople cases in the coming weeks and we should follow this updates and be sure our implementation could pass them.

**Comment by mkalinin** [comment]
I'd keep this issue open until Constantinople tests are finalized and passed by EthereumJ.

**Comment by zilm13** [comment]
1014 test cases for address calculation:
https://github.com/ethereum/EIPs/pull/1375

**Comment by mkalinin** [comment]
Removed an item related to tests. It's not possible to be accomplished at the moment due to issues in tests.
