### ISSUE TITLE
NodeKeyCompositor for storage [ BUG ]

### ISSUE THREAD

**Issue by ithinker1991** [ethereum/ethereumj#1157]
ethereumj-core/src/main/java/org/ethereum/datasource/NodeKeyCompositor.java
This method
``` java
 private static byte[] composeInner(byte[] key, byte[] addrHash) {

        validateKey(key);

        byte[] derivative = new byte[key.length];
        arraycopy(key, 0, derivative, 0, PREFIX_BYTES);
        arraycopy(addrHash, 0, derivative, PREFIX_BYTES, PREFIX_BYTES);

        return derivative;
}
```

``` java
 public static void main(String[] args) {
        byte[] addrhash = Hex.decode("a9539c810cc2e8fa20785bdd78ec36ccb25e1b5be78dbadf6c4e817c6d170bbb");
        byte[] key = Hex.decode("bbbbbb5be78dbadf6c4e817c6d170bbb47e9916f8f6cc4607c5f3819ce98497b");

        byte[] ret = NodeKeyCompositor.compose(key, addrhash);
        System.out.println(Hex.toHexString(ret));

       // output : bbbbbb5be78dbadf6c4e817c6d170bbba9539c810cc2e8fa20785bdd78ec36cc
    }
```

the output is not  match the example 
 * Example: <br/>
 * Contract address hash <i>a9539c810cc2e8fa20785bdd78ec36ccb25e1b5be78dbadf6c4e817c6d170bbb</i> <br/>
 * Key of one of the storage nodes <i>bbbbbb5be78dbadf6c4e817c6d170bbb47e9916f8f6cc4607c5f3819ce98497b</i> <br/>
 * Composed key will be <i>a9539c810cc2e8fa20785bdd78ec36ccbbbbbb5be78dbadf6c4e817c6d170bbb</i> <br/><br/>

**Comment by mkalinin** [comment]
Yep, that was incorrect. Fixed by https://github.com/ethereum/ethereumj/commit/ec3ce8fccb75987f101096c61af137c4f5b17adb. Thank you for the report!

**Comment by ithinker1991** [comment]
emmm...
There seems a another BIG problem. I noticed in solidity, for dynamic type such as  `string`， `bytes`
head of the storage-key are same and tail are different.
So if one field has been encoded to many storage-key. the composed key will be same.

For example
string s = '111111111111111111111111111111111111111111'
encoded result:
key of storage node												 value of storage node													     
0000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000e7
290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563 3131313131313131313131313131313131313131313131313131313131313131
290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e564 3131313131313132323232323232323232323232323232323232323232323232
290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e565 3232323232323232323232323232323333333333333333333333333333333333
290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e566 3333333333333333333333333333333333333300000000000000000000000000
