### ISSUE TITLE
NodeManager::setBootNodes should be public

### ISSUE THREAD

**Issue by matthewleon** [ethereum/ethereumj#1171]
`org.ethereum.net.rlpx.discover.NodeManager::setBootNodes` should be `public` and not package-private. Without setting boot nodes, the object is very difficult to use outside of the package.

https://github.com/ethereum/ethereumj/blob/5c808c1ddfd743e668386d94ec68b6ba3f7713dd/ethereumj-core/src/main/java/org/ethereum/net/rlpx/discover/NodeManager.java#L120

**Comment by netwalker2000** [comment]
I'v got this problem too. Without setting boot nodes, the object is very difficult to use outside of the package, considering the constructor is also public. I created a PR   https://github.com/ethereum/ethereumj/pull/1262
