### ISSUE TITLE
Verify attestations in blocks

### ISSUE THREAD

**Issue by mkalinin** [ethereum/ethereumj#1193]
### Abstract
Verify block's attestation records on before the import.

### Proposed implementation
Implement a couple of new [ValidationRule](https://github.com/ethereum/ethereumj/blob/research/sharding/ethereumj-core/src/main/java/org/ethereum/sharding/processing/validation/ValidationRule.java) and add it to the [BeaconValidator](https://github.com/ethereum/ethereumj/blob/research/sharding/ethereumj-core/src/main/java/org/ethereum/sharding/processing/validation/BeaconValidator.java).
Rules should do following checks:
- Attestation record with `0` index contains distinct valid attestation that is created by proposer of that block
- Attestation records with indices `> 0` are valid records and were created by attesters from committee that is eligible to attest on block's slot number

Consider block as invalid if any of these two checks fails.

**Comment by zilm13** [comment]
resolved with #1219
