### ISSUE TITLE
Fork choice rule with attestations

### ISSUE THREAD

**Issue by mkalinin** [ethereum/ethereumj#1194]
### Abstract
Update fork choice rule with IMD GHOST algorithm.

### Proposed implementation
New [ScoreFunction](https://github.com/ethereum/ethereumj/blob/research/sharding/ethereumj-core/src/main/java/org/ethereum/sharding/processing/consensus/ScoreFunction.java) should be implemented that uses IMD GHOST algorithm combined with finality.

Beacon chain fork choice rule is outlined in the [spec](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?view#Beacon-chain-fork-choice-rule).
IMD GHOST is well described by following posts:
- https://ethresear.ch/t/immediate-message-driven-ghost-as-ffg-fork-choice-rule/2561
- https://ethresear.ch/t/beacon-chain-casper-ffg-rpj-mini-spec/2760

As finality is not yet implemented, there is a suggestion to use block with a highest slot number that satisfies condition `<= head.slotNumber - CYCLE_LENGTH` as `highestSlotNumberJustifiedBlock`

**Comment by zilm13** [comment]
resolved with #1219
