### ISSUE TITLE
Support or not 

### ISSUE THREAD

**Issue by 3Mohammed2013** [ethereum/ethereumj#1212]
Dear Developer, 
 I have a couple of the question. if you do not mind 

1-  EthereumJ and Ethereum Harmony run in which protocol Proof of work POW, POS
2- Is EthereumJ and Ethereum Harmony support the Proof of authority POA? or not yet if yes, please share with me document approval or steps to find these things.

**Comment by zilm13** [comment]
1 - We support PoW, default ethereum proto, we don't support PoS. We have tree with Casper implementation but there were decided to drop Casper in favor of shasper (sharding + casper), so we are moving this way in https://github.com/ethereum/ethereumj/tree/research/sharding . But it will definitely took some time until we have anything usable. Months.
2 - We don't support PoA. While we are thinking about it from time to time, we have no schedule for it. If anyone is interested in adding PoA support, we are open to review code and help. But we don't have resources to implement it by ourselves in the coming months.

**Comment by 3Mohammed2013** [comment]
Dear Dmitry, 
is there are any possibility to integrate your application ( Ethereum Harmony & Ethereumj )
with IoT devices AND  as you know POW is consuming high power consumption,
is there any way to integrate with each other?

**Comment by zilm13** [comment]
@3Mohammed2013 I think no way pow could work on IoT. Too heavy. You are right. Both PoS and PoA could be usable for light clients. So you could either wait for some shasper implementation, including light clients support or take some existing client (not EthereumJ) supporting PoA.

**Comment by zilm13** [comment]
@3Mohammed2013 btw regarding to the shasper, take a look at https://github.com/status-im/nimbus
shasper is in R&D stage and everything is not done yet and changing, but you can follow updates, these folks are focused on shasper implementation on devices with limited resources.

**Comment by zilm13** [comment]
I think we could close this one
