### ISSUE TITLE
It is necessary?

### ISSUE THREAD

**Issue by chenjiaweiprimeledger** [ethereum/ethereumj#1225]
1) org.ethereum.core.TransactionExecutor#create
        AccountState existingAddr = cacheTrack.getAccountState(newContractAddress);
        if (existingAddr != null && existingAddr.isContractExist(blockchainConfig)) {
            execError("Trying to create a contract with existing contract address: 0x" + toHexString(newContractAddress));
            m_endGas = BigInteger.ZERO;
            return;
        }

existingAddr will not exists, because the nonce of the sender has been checked in org.ethereum.core.TransactionExecutor#init

2) org.ethereum.core.TransactionExecutor#create
        //In case of hashing collisions (for TCK tests only), check for any balance before createAccount()
        BigInteger oldBalance = track.getBalance(newContractAddress);
        cacheTrack.createAccount(tx.getContractAddress());
        cacheTrack.addBalance(newContractAddress, oldBalance);

It is rude to transfer balance of same-address contract to the new contract ?

**Comment by mkalinin** [comment]
1. Relates to https://github.com/ethereum/EIPs/issues/684
2. Relates only to tests from [#ethereum/tests](http://github.com/ethereum/tests/) repository, it hardly could happen on main or any other network.
