### ISSUE TITLE
"throw new RuntimeException("Not supported")" in many funs of RepositoryImpl.java

### ISSUE THREAD

**Issue by w1397800** [ethereum/ethereumj#1226]
There are lots of funs which contains "throw new RuntimeException("Not supported")" in "org.ethereum.db.RepositoryImpl.java".  
eg:
 public Set<DataWord> getStorageKeys(byte[] addr) {
        throw new RuntimeException("Not supported");
    }
Is there any implemented function replacing it?

**Comment by mkalinin** [comment]
It's hardly feasible to support some methods in main repository implementation. 
But they are pretty useful in tests, take a look at this implementation
https://github.com/ethereum/ethereumj/blob/561582b965648f8d359b50d4c40c0984e5a4d48e/ethereumj-core/src/test/java/org/ethereum/jsontestsuite/suite/IterableTestRepository.java#L266-L269

**Comment by w1397800** [comment]
thanks for your reply.
