### ISSUE TITLE
rlp code area

### ISSUE THREAD

**Issue by romanman** [ethereum/ethereumj#172]
turn: 
http://www.ethergit.com/raw-transaction/9d8c4ca247980d7df230e2bb045abbcf4905ef5bfe13753d53d793f3ac4bda74

into: 
http://imgur.com/LLKOA2g

the RLP encode rules can be found here: 
https://github.com/ethereum/wiki/wiki/RLP

important points
1. The are should be limited to 64 chars, 
after it the line is wrapped
2. when pressed rlp button , the characters that
represent list encoding will get one color
and characters that represent element encoding 
in different color , the data itself will stay colorless.

**Comment by hems** [comment]
nice one!
