### ISSUE TITLE
EthereumJ compatibility with geth

### ISSUE THREAD

**Issue by mikkazan** [ethereum/ethereumj#287]
Hi,
I've tried to run node started in ethereumJ connecting to the other nodes with geth and it failed due to handshake failure. Is ethereumJ compatible with geth?
Thanks,
Michael

**Comment by romanman** [comment]
Hey  @mikkazan , thanks for reaching out, 
it working very well in our environment with 
all kind of peers go/cpp/python. What versions 
are you trying to connect ?

**Comment by mikkazan** [comment]
Hi @romanman  we are using Geth/v1.0.0/windows/go1.4.2

**Comment by romanman** [comment]
@mikkazan : and how do you specify for EthereumJ 
to connect to that particular peer ?

**Comment by mikkazan** [comment]
This is actually the other limitations I see in ethereumJ or at least I probably did not find documentation how to start ethereumJ with console. What I did i unjared the ethereum jar added json file generated by geth updated .conf file by adding peers addresses. The geth node sees me trying to connect but then fails due to handshake. It would be great if ethereumJ had ability to run with console or at least had possibility to pass .conf and custom .json file. I looked at the CLIInterface and it only recognizes -- help -db -listen -connect -reset. But -connect accepts only one address and to have multiple I need to modify peers in .conf file which is part of the jar.

**Comment by Nashatyrev** [comment]
Hi @mikkazan, 
you may try to override the ethereumj.conf defaults with your custom .conf file. Just specify it with -Dethereumj.conf.file=[file.conf]

**Comment by romanman** [comment]
actually you have one great option to manage 
all of the options , it's the `ethereumj.conf` file
and you can add node list of nodes you want to 
try to connect additional to what peer discovery will find
e.g: 
```
peer {
    # Boot node list
    active = [

        {
            # frontier peer
            ip = my.ether.domain,
            port = 30303,
            nodeId = aa39958f256944e524096d63b7fe6d4b47c9a2efaecebe32edf139354d80120f46d36c9c63b68f3135867a511cec335a575abfacf81a7ef678afb5fb117d0cb3
        }
```

```

**Comment by mikkazan** [comment]
OK. I understand how to pass conf file but what about handshake? Does it have to do something with difficulty? I see that numbers do not match.

**Comment by romanman** [comment]
@mikkazan : let's talk details ? what numbers don't match ?

**Comment by mikkazan** [comment]
the difficulty in generated_block.json which was generated by geth
"difficulty": "0x400000000", 

ethereumJ was throwing exception trying to parse it so I took it from frontier.json 
"difficulty": "0x0400000000", 

After that  I was able to start ethereumj but could not connect to the node which is running on geth

"difficulty": "0x0400000000",

**Comment by romanman** [comment]
@mikkazan : here is the file we specify for the frontier network

https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/resources/genesis/olympic.json

**Comment by mikkazan** [comment]
yeah that is what I have in the .conf file. Otherwise ethereumj won't start. Let me play with it a little more and get back to you.

**Comment by romanman** [comment]
@mikkazan : sure :+1:

**Comment by mikkazan** [comment]
OK, found the issue. Apparently the difficulty generated by geth client had X instead of x. Java is pretty strict about it. Once I changed it to proper I was able to connect to geth clieant

**Comment by romanman** [comment]
what do you mean X instead of x (curious) ?

**Comment by romanman** [comment]
@mkalinin : just adding you

**Comment by ligi** [comment]
I think he means that only lower case x is accepted - not a capitalized one

**Comment by romanman** [comment]
ohh like in the hex type number ?

**Comment by ligi** [comment]
yea - a 0x0400000000 is accepted - a 0X0400000000 is not - a toLowerCase on the string should solve the problem

**Comment by romanman** [comment]
@ligi @mikkazan : cool got you now, ok guess not a big deal :)

**Comment by rajesh-parab** [comment]
what is networkId stands for in conf file ? is the one we gave while initializing geth node ?

**Comment by zilm13** [comment]
@rajesh-parab to get your Geth nodeId run in console `admin.nodeInfo`
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#adminnodeinfo
networkId is id of Ethereum network (live - 1, morden - 2, test - 161, your private network - anything else), for geth its command line parameter.
Please update, whether you were able to solve your issue.

**Comment by rajesh-parab** [comment]
I have started geth  with this geth --networkid 777 --port 30303 --rpcport 8103 console
I have downloaded ethereumj-starter-master project. First i run with default settings.
then i wanted to connect to my geth node above I tried modifying configuration file but not working.

check if my ethereum conf file. 

[ethereum.txt](https://github.com/ethereum/ethereumj/files/597820/ethereum.txt)

**Comment by rajesh-parab** [comment]
@zilm13 

I have started geth with this geth --networkid 777 --port 30303 --rpcport 8103 console
I have downloaded ethereumj-starter-master project. First i run with default settings.
then i wanted to connect to my geth node above I tried modifying configuration file but not working.

check if my ethereum conf file is correct.

[ethereum.txt](https://github.com/ethereum/ethereumj/files/597830/ethereum.txt)

**Comment by zilm13** [comment]
Have you updated it with correct nodeId from geth?

> active = [ { ip= 127.0.0.1
                 port=30303
> ....
>  listen.port = 30303

How do you run both on one port??

>         blocks = 10000

I'd recommend something less for private network, even 1, maybe, if you restart often

> genesis = frontier.json

You should have same genesis files for geth and EthereumJ. for geth you first init db with your genesis, something like that:
```
--datadir /path/to/private/db --networkid 777 --nodiscover --verbosity 6 --port 30309 init /some/path/src/main/resources/genesis/frontier-private.json
```
and after that you run it:
```
--datadir /path/to/private/db --networkid 777 --nodiscover --verbosity 6 --port 30309 console
```

If genesis files doesn't match, you will see something like that in EthereumJ logs:
> Removing EthHandler for b4c8393cb due to protocol incompatibility

**Comment by rajesh-parab** [comment]
@zilm13 is it ok if i have 2 copies of same file one is used by geth and another is by ethereumj . contents are same

**Comment by zilm13** [comment]
@rajesh-parab sure, just contents should be the same

**Comment by rajesh-parab** [comment]
@zilm13 where frontier.json should be kept I put in src/main/resources/genesis folder but looks like it is not reading from there

**Comment by zilm13** [comment]
@rajesh-parab could you change name to be sure? frontier.json is standard in library, may be it's using it.

**Comment by rajesh-parab** [comment]
@zilm13  thanks its working now. I am able to connect to geth network

**Comment by zilm13** [comment]
@rajesh-parab great!

**Comment by rajesh-parab** [comment]
@romanman  
I am able to connect to geth network with spring boot application using ethereumJ  but what I have found that ehtereumJ created a peer and add itself to my geth network both running on same machine.

I have 2 questions now.
1) how i can prevent thereumJ to create its own peer and add it in geth or any external network.

2) I have created an account using ECKey class but when i gave etch.accounts in geth console i do not see any account created.  I do not want to import it manually . I want etheriumJ create an account and save it in network could be started by geth or created by azure template in cloud.

**Comment by cupuyc** [comment]
@rajesh-parab 
1) EthereumJ can interact with ethereum network only as a peer.

2) EthereumJ doesn't support keystore feature like in geth. But it is possible to use Harmony node to access system wide keystore. Harmony is based on EthereumJ-core and located at https://github.com/ether-camp/ethereum-harmony . Keys could be operated via JSON-RPC there.

**Comment by rajesh-parab** [comment]
@cupuyc 
Is there any chance in future version that EthereumJ will allow to create an account and it can be visible in any network. I wanted to create some admin screen which create an account.

**Comment by cupuyc** [comment]
@rajesh-parab 
1. A creating account in ethereum network could mean just sending ETH to it. EthereumJ can do that via sending transaction for example.
2. On other side keystore feature allows you to save private key in your filesystem. With a private key you can execute transactions from your account. Harmony has wallet for example, where you could see all stored keys, similar to `eth.accounts`
