### ISSUE TITLE
Question about Miner

### ISSUE THREAD

**Issue by mikkazan** [ethereum/ethereumj#291]
Hi EthereumJ team,
I am trying to figure out if there is any way to start mining in ethereumj thee same way it works in geth. In geth you just execute miner.start(number_of_threads) and miner.stop(). I found Miner.java in the repo but there is no unit test nor documentation how to use it. I see mine(Block newBlock, byte[] difficulty) method but it is not the same as miner.start in geth and not quite sure how to use that method in external code.
Thank you

**Comment by romanman** [comment]
@mikkazan : hey body, I am sorry but we didn't implemented the miner 
yet , it's really  not a big priority for us , but if you want to work it 
out we will find the way to reward you.

**Comment by mikkazan** [comment]
@romanman I would love to participate in it, but not at the moment. We have very tight deadline in blockchain implementation so currently we have go and c++ versions running in the full speed. We also wanted to have node running in java but due to this limitation we probably drop it for now. I see that other developer is working on miner so please let me know if you'll still want me to contribute in the future.
Thank you,

**Comment by romanman** [comment]
@mikkazan : sure thing :+1:

**Comment by redskate** [comment]
Hi, now we have 2018 - does ethereumj have a miner ? How can be mined to a test network issued by ethereumj ?

Thanks a lot in advance
Regards

**Comment by mkalinin** [comment]
@redskate it has a miner now. Look at [this](https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/samples/PrivateMinerSample.java), it represents a miner in private network
