### ISSUE TITLE
Contract submission fails

### ISSUE THREAD

**Issue by mikkazan** [ethereum/ethereumj#312]
Hi EthereumJ team,
hope you missed me :)

I am trying to send new contract to ethereumj and got exception back

Here is my code
```
@Override
// data is compiled contract
    public void submitContract(byte[] data, Long value) {
        Repository repository = ethereumBean.getEthereum().getRepository();
        //Fails here
        nonce = repository.getNonce(userKey.getAddress());
        Long gasLimit = ethereumBean.getEthereum().getBlockchain().getBestBlock().getGasLimit();
        Transaction tx = CallTransaction.createRawTransaction(nonce.longValue(), 70_000_000_000L, gasLimit, null, value, data);
        tx.sign(userKey.getPrivKeyBytes());
        ethereumBean.getEthereum().submitTransaction(tx);
    }
```

I generated user privateKey using Hex.toHexString(new ECKey().decompress().getPrivKeyBytes()); and added it to .conf file. Genesis file has nonce and gasLimit and was loaded according to the log

2015-09-28 14:57:06.704  INFO 5724 --- [pool-1-thread-1] general                                  : DB is empty - adding Genesis
2015-09-28 14:57:07.040  INFO 5724 --- [pool-1-thread-1] general                                  : Genesis block loaded
2015-09-28 14:57:07.053  INFO 5724 --- [       Thread-6] blockqueue                               : Start loading sync queue
2015-09-28 14:57:07.072  INFO 5724 --- [       Thread-6] sync                                     : Sync Manager: ON
2015-09-28 14:57:07.090  INFO 5724 --- [    UDPListener] discover                                 : Discovery UDPListener started
2015-09-28 14:57:07.116  INFO 5724 --- [pool-6-thread-1] net                                      : Listening for incoming connections, port: [30303]
2015-09-28 14:57:07.129  INFO 5724 --- [pool-6-thread-1] net                                      : NodeId: [server_node_id]

The exception is 
java.lang.NullPointerException: null
        at org.ethereum.trie.TrieImpl.insert(TrieImpl.java:225)
        at org.ethereum.trie.TrieImpl.insertOrDelete(TrieImpl.java:201)
        at org.ethereum.trie.TrieImpl.update(TrieImpl.java:133)
        at org.ethereum.trie.SecureTrie.update(SecureTrie.java:25)
        at org.ethereum.db.RepositoryImpl$9.invoke(RepositoryImpl.java:492)
        at org.ethereum.db.RepositoryImpl$13.invoke(RepositoryImpl.java:636)
        at org.ethereum.db.RepositoryImpl.doWithAccessCounting(RepositoryImpl.java:626)
        at org.ethereum.db.RepositoryImpl.doWithAccessCounting(RepositoryImpl.java:633)
        at org.ethereum.db.RepositoryImpl.updateAccountState(RepositoryImpl.java:489)
        at org.ethereum.db.RepositoryImpl.createAccount(RepositoryImpl.java:560)
        at org.ethereum.db.RepositoryImpl.getAccountStateOrCreateNew(RepositoryImpl.java:475)
        at org.ethereum.db.RepositoryImpl.getNonce(RepositoryImpl.java:469)

can you pelase point me what am I doing wrong?

**Comment by romanman** [comment]
@mikkazan : need more info,
are you on version = latest snapshot now ?

**Comment by mikkazan** [comment]
the snapshot is ethereumj-core-1.0.0-20150916.144407-76. I checked repo last week. Only jar with -stage was newer than mine.

**Comment by romanman** [comment]
@mikkazan  will check that , 
really thank you for your patience

**Comment by romanman** [comment]
@mkalinin : can you please see if you recreate this in your current env ?

**Comment by mkalinin** [comment]
@mikkazan do you use custom Genesis file?

**Comment by mikkazan** [comment]
yes. We generated genesis file using geth and I am re-using it

**Comment by mkalinin** [comment]
I just tried a small test. Loaded our `frontier` Genesis and called `repository.getNonce(random_address)`. It returned `0` as expected. 
Could you please share your Genesis and your `userKey` with me?

**Comment by romanman** [comment]
@mikkazan @mkalinin : I think the genesis is the key , 
@mikkazan , how exactly you call your genesis , and how
you execute it ?

**Comment by mikkazan** [comment]
I added new file to .conf file
genesis = genesis_block.json
It is also part of the ethereum jar. I unarchived it, added the file to the genesis directory and archived it back.
Ethereum loads it fine. 

Here is the file 

{
    "nonce": "0xdeadbeefdeadbeef",
    "timestamp": "0x00", 
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
    "extraData": "0x686f727365", 
    "gasLimit": "0x08000000", 
    "difficulty": "0x0400", 
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
    "coinbase": "0x3333333333333333333333333333333333333333",
    "alloc": {
   }
}

**Comment by mkalinin** [comment]
I've got same exception as you with this Genesis. Let us check what's wrong

**Comment by mikkazan** [comment]
Okie dokie

**Comment by romanman** [comment]
@mikkazan @mkalinin ::: I think that the genesis is not loaded that way , 
to load it you need 
 1. to place it in resources/genesis
 2. to name it frontier-custom (or something that contains frontier keyword)
     that is how we identify the frontier consensys algorithm 
 3. you obviously need to specify the in the conf file.

-- sorry guys it all should be documented, and will be one day :+1:

**Comment by mikkazan** [comment]
@romanman I don't think you're right. I spent some time dealing with custom genesis file. The genesis loader is actually looking for the property I mentioned above and hard coded directory in the jar is genesis.

**Comment by romanman** [comment]
@mikkazan : yep we can debate that, 
or try it my way , cause I am the one 
who actually typed down that code, 
maybe will be logical , at least to try it. :8ball:

**Comment by mkalinin** [comment]
@mikkazan this behavior caused by empty `alloc` attribute, we'll fix that bug. You may add a line with zero balance to the `alloc` as a workaround for a while

**Comment by romanman** [comment]
@mkalinin : looks like a bug , we 
should not crush on empty trie, 

@mikkazan : anyway , can you please
1. add some element to the trie, 
2. to put the genesis , on the app level
and not injected.

**Comment by mikkazan** [comment]
@romanman 
1. I will add some element in trie.
2. The thing is according to line 35 in GenesisLoader - https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/core/genesis/GenesisLoader.java
 putting custom genesis file into the app level will not work.
InputStream is = ClassLoader.getSystemResourceAsStream("genesis/" + genesisFile);
 It looks for the file under app_level/genesis directory.

**Comment by mikkazan** [comment]
@romanman @mkalinin 
After adding some values into alloc in genesis file the exception is gone.

**Comment by romanman** [comment]
@mikkazan : thanks , for the second issue, we are 
running the genesis on the application
level in our test network (different genesis)
by adding it to: `/resources/genesis/frontier-test.json`

**Comment by mikkazan** [comment]
Looks like it was misunderstanding. My genesis file is also under /resources/genesis/. When you said put genesis into app level I thought that you mean put my_genesis.json directly  into app level.

**Comment by romanman** [comment]
@mikkazan : cool , I was kind of sure that you re-zip 
it to the ethereumj lib, if that is not the case , 
all good :+1:

**Comment by romanman** [comment]
@mikkazan : we fixed that will also for empy trie, 
you will see it soon in the new snapshoot version
