### ISSUE TITLE
Genesis block configuration is corrupted 

### ISSUE THREAD

**Issue by skydogch** [ethereum/ethereumj#315]
Hi guys,

I have added my custom genesis into the configuration file but I get an error:

"Genesis block configuration is corrupted or not found ./resources/genesis/..."

The genesis file works fine with geth

{
    "nonce": "0x0000000000000042", 
    "difficulty": "0x4", 
    "alloc": {
        "a354a8bee6b828b88ce9dab0b2ca45c7b51508d3": {
            "balance": "5000000000000000000000000"
        } 
    }, 
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
    "coinbase": "0x0000000000000000000000000000000000000000", 
    "timestamp": "0x00", 
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
    "extraData": "0x1100000000000000000000000000000000000000000000000000000000000000", 
    "gasLimit": "0xffff1388"
}

If needed, here the execution log: https://gist.github.com/skydogch/aa0e584e26284bd6d2e5

**Comment by mkalinin** [comment]
hi @skydogch 
There are two points you should notice when start using your custom Genesis file

1) There is a `genesis` property in `ethereumj.conf` file which should contain path to your Genesis related to `resources/genesis`
2) The name of the file should contain `frontier` word, this allows `ethereumj` to understand which environment is used and impacts on constants and other env related stuff

Please, check these two things first.

**Comment by skydogch** [comment]
Hi @mkalinin ,
thanks a lot for the information, it works!
