### ISSUE TITLE
Occasional NullPointerException in getPendingTransactions

### ISSUE THREAD

**Issue by kushti** [ethereum/ethereumj#316]
While running in a cycle, getPendingTransactions returns NullPointerException sometimes:

code example in Scala:

val eth = EthereumFactory.createEthereum()
eth.init()

actorSystem.scheduler.schedule(2.seconds, 1.seconds) {
     Try(eth.getPendingTransactions.filter(_.getData.length == 50)) match {
        case Success(txs) => println("50-bytes data field found")
        case Failure(e) => println(e)
      }
}

usually being run without problems, but sometimes prints java.lang.NullPointerException

**Comment by romanman** [comment]
@kushti : are you running the latest snapshot ?

**Comment by kushti** [comment]
@romanman yes, it was built from the source code yesterday

**Comment by romanman** [comment]
@kushti : ok , the pending transaction is still in 
testing stage , so maybe there is a bug there
we will check it over

**Comment by Nashatyrev** [comment]
`PendingTransactionImpl` has been refactored, so I believe this concrete bug should be gone. Feel free to reopen if still exists
