### ISSUE TITLE
Blockchain rollback interface to resolve stuck when it happens

### ISSUE THREAD

**Issue by kushti** [ethereum/ethereumj#317]
Got an error message

16:14:23.463 [state]  BLOCK: STATE CONFLICT! block: 377454 worldstate b4c9cb9d619330535fb6783a2ffe8eb725e189ed38bfb31aa4d4183d2537709e mismatch
CONFLICT: BLOCK #377454

Probably some method to throw away some number of last blocks  and then try to redownload them & reapply would be helpful. Otherwise a node could stuck for an arbitrary time.

**Comment by romanman** [comment]
@kushti : if you restart the system , 
are you getting it over and over again ?

**Comment by kushti** [comment]
@romanman yes, relaunching won't help with that

**Comment by romanman** [comment]
@kushti : so in that case removing  the db
and running from the start is the only way for 
you now

**Comment by kushti** [comment]
I see, but why not to have some rollback(int numberOfBlocks) method to provide repair possibility? I guess such a functionality is needed for the core as well for handling reorgs.

**Comment by romanman** [comment]
Yes , but I guess some rare bug cause the conflict to 
be saved to the database , so it's a corrupted state 
and you don't know how it will behave , so prefer to do 
a re-sync

**Comment by kushti** [comment]
Got that. Redownloading chain is slow process though, so what about state rebuilding from blocks in the db up to some height? eg. with eth.initWithRepair(int height) instead of ordinary init()
