### ISSUE TITLE
Split project into library and application

### ISSUE THREAD

**Issue by FranciscoE-Reuters** [ethereum/ethereumj#318]
Given that the library may be used in non-EE systems, it should be possible to do away with J2EE frameworks, and split it into a framework and a base program.

The starting point would be to do away with Spring, Hibernate, and consider how to bring huge helper collections like Apache Commons or Netty in smaller chunks.

**Comment by romanman** [comment]
Hey Francisco, 

We trying to build the library in a very modular
way , so it can be used in any type of java/scalla project.

I suggest that you will tell us more about 
special requirements and we will try to 
find the best solution for you.

**Comment by FranciscoE-Reuters** [comment]
It's not very special requirement, but the while the whole project has been written modularly, the whole component is coupled with those monolithic dependencies.

The objective would be to build a library that can be used from Java 9 REPL, or linked on a JavaFX or Android project, to do lightweight tasks like wallet management.

The project would need to have at least those functionalities separated, and network-framework agnostic. Other module would have to be mining, or interfacing with the compilation of the contracts.

**Comment by romanman** [comment]
I see well it's one option of building the core architecture , it's a bit complex but can be done.

**Comment by FranciscoE-Reuters** [comment]
It's way less complex than fitting Hibernate on Dalvik, trust me :D 

This proposal is only interesting if the objective of ethereumj is creating a toolset revolving etherium on the JVM, rather than just a program.

**Comment by romanman** [comment]
@FranciscoE-Reuters : that reminds me that we can 
get rid of Hibernate on that level already :+1: 
@Nashatyrev (can you please add it to the todo
: hibernate and all light dbs are not needed in the package anymore)

**Comment by btiernay** [comment]
I think it might also be a good idea to consolidate dependencies in general. For example, for JSON support I see 2 versions of Jackson being used (codehaus and fasterxml), and json.org. This also makes the application much heavier for constrained environments.

**Comment by btiernay** [comment]
Might I also suggest some greater static modularity:

- `ethereumj-client`
- `ethereumj-core`
- `ethereumj-net`
- `ethereumj-crypto`
- etc.

This will allow the project to better track and understand dependencies and help enforce internal modular boundaries.

**Comment by romanman** [comment]
@btiernay : nice structure, we need to see 
if it will be useful for the projects.

**Comment by btiernay** [comment]
This might be useful for something like https://github.com/ethereum/ethereumj/issues/379 where a very small subset of the functionality is required (perhaps just VM).
