### ISSUE TITLE
geth peer error: faild enc handshake: could not decrypt auth message (ecies: invalid message)

### ISSUE THREAD

**Issue by skydogch** [ethereum/ethereumj#321]
Hi guys,

I am connecting to a local go peer. 
During the connection, I don't see any error in the ethereumj protocol, but I am getting a geth-error: **"faild enc handshake: could not decrypt auth message (ecies: invalid message)"**. 

I don't know if the issue is really in geth or ethereumj

**Ethereumj protocol (no error):**
https://gist.github.com/skydogch/a298848efecb149c5ede

**Geth protocol (handshake error):**
$ geth --datadir="/home/merlin/zDev/peer_tmp3/dataDirPeerTmp3" --genesis=/home/merlin/zDev/frontier-custom.json -verbosity 9 --ipcdisable --port 30303 --rpcport 8103 --networkid 54321 --nodiscover console  
I1022 11:31:36.654865   11734 database.go:71] Alloted 16MB cache to /home/merlin/zDev/peer_tmp3/dataDirPeerTmp3/chaindata
I1022 11:31:36.674438   11734 database.go:71] Alloted 16MB cache to /home/merlin/zDev/peer_tmp3/dataDirPeerTmp3/dapp
I1022 11:31:36.679776   11734 backend.go:291] Protocol Versions: [62 61], Network Id: 54321
I1022 11:31:36.680638   11734 statedb.go:251] (+) a354a8bee6b828b88ce9dab0b2ca45c7b51508d3
I1022 11:31:36.680831   11734 state_object.go:188] a354a8bee6b828b88ce9dab0b2ca45c7b51508d3: #0 5000000000000000000000000 (+ 5000000000000000000000000)
I1022 11:31:36.682792   11734 genesis.go:88] Genesis block already in chain. Writing canonical number
I1022 11:31:36.683116   11734 backend.go:303] Successfully wrote genesis block. New genesis hash = 8103ce849520fe3faa39a0e889b09cc228582d69aaea0eee2a2d29b1ae193672
I1022 11:31:36.683434   11734 backend.go:333] Blockchain DB Version: 3
I1022 11:31:36.684585   11734 chain_manager.go:248] Last block (#2805) 325691b89da8816c894151dcf40232056fc8dbdb4e6e29e54cc737950578bbf5 TD=781689855
I1022 11:31:36.685714   11734 statedb.go:251] (+) 0000000000000000000000000000000000000000
I1022 11:31:36.691944   11734 state_object.go:220] 0000000000000000000000000000000000000000: gas (+ 276889099)
I1022 11:31:36.707059   11734 cmd.go:125] Starting Geth/v1.2.2/linux/go1.5
I1022 11:31:36.707367   11734 server.go:311] Starting Server
I1022 11:31:36.707606   11734 backend.go:559] Server started
I1022 11:31:36.707624   11734 server.go:552] Listening on [::]:30303
I1022 11:31:36.709755   11734 mergedapi.go:61] modules 
I1022 11:31:36.925441   11734 mergedapi.go:61] modules 
I1022 11:31:36.926433   11734 mergedapi.go:61] web3_clientVersion []
I1022 11:31:36.926507   11734 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=1) 2.0 Geth/v1.2.2/linux/go1.5}
instance: Geth/v1.2.2/linux/go1.5
I1022 11:31:36.927532   11734 mergedapi.go:61] admin_datadir []
I1022 11:31:36.927598   11734 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=2) 2.0 /home/merlin/zDev/peer_tmp3/dataDirPeerTmp3}
 datadir: /home/merlin/zDev/peer_tmp3/dataDirPeerTmp3
I1022 11:31:36.928388   11734 mergedapi.go:61] eth_coinbase []
I1022 11:31:36.928463   11734 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=3) 2.0 0x88f52b276e812f03bf7875eccb947f9d15dda270}
coinbase: 0x88f52b276e812f03bf7875eccb947f9d15dda270
I1022 11:31:36.929317   11734 mergedapi.go:61] eth_blockNumber []
I1022 11:31:36.929387   11734 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=4) 2.0 0xaf5}
I1022 11:31:36.938051   11734 mergedapi.go:61] eth_getBlockByNumber ["0xaf5",false]
I1022 11:31:36.938458   11734 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=5) 2.0 %!s(*api.BlockRes=&{false 0xc820c70f60 0xc820c70fc0 0xc820c71020 0xc820c71060 0xc820c710a0 0xc820c710e0 0xc820c71120 0xc820c71180 0xc820c711e0 0xc820c71240 0xc820c712a0 0xc820c712e0 0xc820c714c0 0xc820c71560 0xc820c715a0 0xc820c71600 0xc820c71660 [] []})}
I1022 11:31:36.969696   11734 mergedapi.go:61] eth_blockNumber []
I1022 11:31:36.969847   11734 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=6) 2.0 0xaf5}
at block: 2805 (Wed, 14 Oct 2015 23:23:19 CEST)
I1022 11:31:36.973013   11734 mergedapi.go:61] modules 
modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
> I1022 11:31:38.755986   11734 nat.go:109] network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
I1022 11:32:08.808994   11734 server.go:586] Accepted conn 127.0.0.1:38886
I1022 11:32:09.126001   11734 server.go:613] inbound conn 127.0.0.1:38886 faild enc handshake: could not decrypt auth message (ecies: invalid message)
I1022 11:32:17.636232   11734 server.go:586] Accepted conn 127.0.0.1:38887
I1022 11:32:17.931296   11734 server.go:475] <-posthandshake: inbound conn fe3fd3bfd5595ea4 127.0.0.1:38887
I1022 11:32:18.072031   11734 server.go:481] <-addpeer: inbound conn fe3fd3bfd5595ea4 127.0.0.1:38887
I1022 11:32:18.072324   11734 server.go:670] Added Peer fe3fd3bfd5595ea4 127.0.0.1:38887
I1022 11:32:18.072804   11734 peer.go:298] Peer fe3fd3bfd5595ea4 127.0.0.1:38887: Starting protocol eth/61
I1022 11:32:18.072976   11734 handler.go:187] Peer fe3fd3bfd5595ea4 [eth/61]: peer connected [Ethereum(J)/v1.0.0/Dev/Linux/Java]
I1022 11:32:18.240206   11734 handler.go:199] Peer fe3fd3bfd5595ea4 [eth/61]: adding peer
I1022 11:32:18.240617   11734 downloader.go:216] Registering peer fe3fd3bfd5595ea4
I1022 11:32:18.749322   11734 server.go:586] Accepted conn 127.0.0.1:38888
I1022 11:32:19.215982   11734 server.go:613] inbound conn 127.0.0.1:38888 faild enc handshake: could not decrypt auth message (ecies: invalid message)
I1022 11:32:26.963360   11734 peer.go:168] Peer fe3fd3bfd5595ea4 127.0.0.1:38887: read error: EOF
I1022 11:32:26.963742   11734 handler.go:219] Peer fe3fd3bfd5595ea4 [eth/61]: message handling failed: EOF
I1022 11:32:26.963866   11734 handler.go:138] Removing peer fe3fd3bfd5595ea4
I1022 11:32:26.963925   11734 downloader.go:227] Unregistering peer fe3fd3bfd5595ea4
I1022 11:32:26.964022   11734 server.go:686] Removed Peer fe3fd3bfd5595ea4 127.0.0.1:38887 (Network error)
I1022 11:32:26.964191   11734 server.go:497] <-delpeer: Peer fe3fd3bfd5595ea4 127.0.0.1:38887
I1022 11:46:36.707920   11734 nat.go:120] refresh port mapping tcp:30303 -> 30303 (ethereum p2p) using UPnP or NAT-PMP
I1022 11:46:36.708076   11734 nat.go:122] network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered

---------------------------------------------

All peers are using the same genesis
https://gist.github.com/skydogch/bdf004cf770b59a997af

**Comment by skydogch** [comment]
It is a go-ethereum issue

**Comment by romanman** [comment]
@skydogch, isbit the newest version of go ethereum? hope they didn't break something.

**Comment by madshell** [comment]
why is this issue closed without any comment? same problem here with default geth installation on Ubuntu 14.04 (https://install-geth.ethereum.org script)

**Comment by Nashatyrev** [comment]
Most likely the issue is in incorrect `nodeId` when connecting to geth peer

**Comment by skydogch** [comment]
Hello
@romanman , sorry for the late answer :-(, the problem was not in the java implementation as far as I remember
@madshell , there was a missing library in go-ethereum which was not installed by default, I don't remember which one it was, but the problem should be resolved. I reinstalled go-ethereum some weeks ago and it was working propertly. This issue is old, maybe the reason is what wrote @Nashatyrev , but I think the problem was related with the go-ethereum installation
@Nashatyrev , good point what you wrote about the nodeId, it is to take into consideration. Wrong nodeId can cause this issue too

**Comment by madshell** [comment]
I find out the issue. Indeed, it wasn't really the nodeId but the IP address not present in the enode URI. When I'm displaying "admin.nodeInfo", here is an example result:

enode://280cb677fda3d9dd1ef1751b0dfd1616dad17b813ab855aacd869832649b2c07d07d9929016d0a347e5f8a476b2f3b07e7e9e88fb8e21e047f117498897e2e1a@**[::]**:30303?discport=0

The IP is not found maybe because of a library problem or a networking issue (I reproduced the problem on 2 MacBook behind a router). Just replacing [::] with the right IP solved my issue.

**Comment by k00ka** [comment]
@madshell: We are trying to use geth to build a private chain and are receiving the same message. The call to addPeer is successful, but all messages result in:
inbound conn 10.0.1.13:42662 faild enc handshake: ecies: invalid message
[We were able to confirm that ecies#decrypt fails just after the call to messageTag.]
We're interested in trying your IP fix but wondered what steps you took. Thanks for any suggestions.

**Comment by jschweifer** [comment]
I was fighting with this problem, too. The solution turned out to be rather simple. For some reason the admin.nodeInfo.enode of the machine in question had changed. I suspect because the IP changed. Retrieving it again, making sure the IP was static, and adding the proper node allowed us to run the testnet smoothly.
