### ISSUE TITLE
BLOCK STATE CONFLICT in different block numbers after calling callConstantFunction

### ISSUE THREAD

**Issue by skydogch** [ethereum/ethereumj#324]
Hi guys,

I am calling callConstantFunction in order to get the return value of the function getBalance / getAccountName of my [contract](https://gist.github.com/skydogch/0aa2c96ae5d4dbfcde0d#file-accounttestcontract-sol-L22-L27):

```javascript
	function getBalance() constant returns (int o_Balance) {
		o_Balance = ov_Balance;
	}
	function getAccountName() constant returns (string o_AccountName) {
		o_AccountName = ov_AccountName;
	}
```

The issue is that after executing callConstantFunction, I get a block state conflict and the java process ends. The conflict is produced always in a different block number

For more info, here the [java code](https://gist.github.com/skydogch/b83273509f6231df9464) and the [execution log](https://gist.github.com/skydogch/0e6e3c5bdfe9e278765f#file-gistfile1-txt-L2194-L2255)

--------------------------------------------------------------------------------

```javascript
13:53:24.886 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	NEW_BLOCK [ number: 10358 hash:4c3490 difficulty: 03474456d8 ]
13:53:24.887 INFO  sync - New block received: block.index [10358]
13:53:24.915 INFO  blockqueue - Block hashes list size: [0]
13:53:24.918 INFO  net - From: 	localhost/127.0.0.1:30303 	Recv: 	[NEW_BLOCK_HASHES 4c349066e71bada4263a204ee283f8a43b17d4cae026c6d24db35f0e60f5a223...4c349066e71bada4263a204ee283f8a43b17d4cae026c6d24db35f0e60f5a223] (1)
13:53:24.921 INFO  blockqueue - BlockQueue size: 0
13:53:24.921 INFO  blockchain - Try connect block hash: 4c3490, number: 10358
13:53:24.922 INFO  blockchain - applyBlock: block: [10358] tx.list: [0]
13:53:24.923 INFO  blockchain - TD: updated to 14080562904
13:53:24.924 INFO  repository - updatingBatch: detailsCache.size: 1
13:53:24.924 INFO  repository - updated: detailsCache.size: 1
13:53:24.924 INFO  state - applied reward for block: [10358]  
  state: [b7aafc709d6fbae3de955131b465a6e060cfebcadb1aa807474913c92973af67]
13:53:24.924 INFO  blockchain - block: num: [10358] hash: [4c3490], executed after: [1857082]nano
13:53:24.924 INFO  repository - updatingBatch: detailsCache.size: 0
13:53:24.925 INFO  repository - updated: detailsCache.size: 0
13:53:24.925 ERROR state - BLOCK: STATE CONFLICT! block: 10358 worldstate b7aafc709d6fbae3de955131b465a6e060cfebcadb1aa807474913c92973af67 mismatch
CONFLICT: BLOCK #10358
Disconnected from the target VM, address: '127.0.0.1:33521', transport: 'socket'

Process finished with exit code 1

```

**Comment by skydogch** [comment]
Hi, I have updated the issue description above with an example to a constant function call

**Comment by romanman** [comment]
sure we have a known bug in 
a constant function call so you
can hold a bit untill we will fix it

**Comment by skydogch** [comment]
Hi @romanman , thanks for the reply. I was not sure if it is a bug or I was missing anything. Please let me know if I can support you in someway.

**Comment by skydogch** [comment]
Hi @Nashatyrev , thanks a lot, it works!

**Comment by Nashatyrev** [comment]
@skydogch BTW, we've recently implemented dynamic return types and multiple returns decoding in CallTransaction.Function, you may give it a try if you need that funcs

**Comment by skydogch** [comment]
Hi @Nashatyrev, thanks a lot!

I will test first the submit transaction, it was not working last week. After it I will test the new return functionality :+1:
