### ISSUE TITLE
NullPointerException in eth BlocksMessage

### ISSUE THREAD

**Issue by adrian-tiberius** [ethereum/ethereumj#329]
Got this exception with stage branch when running "./graddlew run". It doesn't seem to affect block importing. From what I could find, the BlocksMessage instance can contain null block items in the blocks list which is not taken into account when encoding them(line 47).

>13:42:54.780 [general]  Connecting to the block store
>13:42:55.816 [blockqueue]  Hash store loaded, size [0]
>13:42:55.844 [blockqueue]  Header store loaded, size [0]
>13:42:55.844 [blockqueue]  Block queue loaded, size [0]
>13:42:55.845 [sync]  Changing state from IDLE to HASH_RETRIEVING
>13:42:55.846 [sync]  
>
>13:42:55.846 [sync]  State HASH_RETRIEVING
>
>13:42:55.910 [discover]  Reading Node statistics from DB: 0 of 0 nodes.
>13:43:03.539 [sync]  Peer 98841ca1: its chain is better than previously known: 2283848631620169749 vs 17179869184, rotate master peer
>13:43:03.540 [sync]  Peer 98841ca1: HASH_RETRIEVING initiated, lastHashToAsk [b54be0730e4014d3e45d1b1952268cb893868b82159ceafc81bee1ef852e5d9c], askLimit [10000]
>13:43:03.540 [sync]  Peer 98841ca1: added to pool
>13:43:06.092 [discover]  Write Node statistics to DB: 18 nodes.
>13:43:11.541 [sync]  Peer 7f37942a: added to pool
>13:43:15.993 [discover]  Write Node statistics to DB: 87 nodes.
>13:43:16.541 [sync]  Peer 73f0bfbd: its chain is better than previously known: 3592012751291746942 vs 2283848631620169749, rotate master peer
>13:43:16.937 [sync]  Peer 73f0bfbd: HASH_RETRIEVING initiated, lastHashToAsk [29f25d916c99623fa18b826d455da31c5272610ce81704607df623d9e0f51776], askLimit [10000]
>13:43:16.938 [sync]  Peer 73f0bfbd: added to pool
>13:43:18.914 [net]  FrameCodec failed: 
>io.netty.handler.codec.EncoderException: java.lang.NullPointerException
>    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
>    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
>    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
>    at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
>    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
>    at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
>    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
>    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
>    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
>    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
>    at java.lang.Thread.run(Thread.java:745)
>Caused by: java.lang.NullPointerException
>    at org.ethereum.net.eth.message.BlocksMessage.encode(BlocksMessage.java:47)
>    at org.ethereum.net.eth.message.BlocksMessage.getEncoded(BlocksMessage.java:58)
>    at org.ethereum.net.rlpx.MessageCodec.encode(MessageCodec.java:155)
>    at org.ethereum.net.rlpx.MessageCodec.encode(MessageCodec.java:37)
>    at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
>    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
>    ... 10 more
>13:43:20.343 [blockqueue]  BlockQueue size: 99
>13:43:20.344 [blockqueue]  No parent on the chain for block.number: 9217 block.hash: 8d80dd
>13:43:22.444 [blockqueue]  BlockQueue size: 383
>13:43:22.447 [blockqueue]  Success importing BEST: block.number: 1, block.hash: 88e96d, tx.size: 0 
>13:43:22.447 [blockqueue]  BlockQueue size: 382
>13:43:22.447 [blockqueue]  Success importing BEST: block.number: 2, block.hash: b495a1, tx.size: 0 
>13:43:22.448 [blockqueue]  BlockQueue size: 381
>13:43:22.448 [blockqueue]  Success importing BEST: block.number: 3, block.hash: 3d6122, tx.size: 0 
>13:43:22.449 [blockqueue]  BlockQueue size: 380

**Comment by Nashatyrev** [comment]
Yep, this is our bug, thanks for reporting!

**Comment by Nashatyrev** [comment]
Seems not reproducible anymore with the latest release
