### ISSUE TITLE
Transaction not propagated to geth peer

### ISSUE THREAD

**Issue by skydogch** [ethereum/ethereumj#330]
Hi guys,

the **submitTransaction** is executed in ethereumj without propagating the changes to a geth peer. *Am I doing anything wrong or is it an issue?*

The test case is done using two nodes: one geth and another ethereumj 
- The transactions performed in the geth peer are propagated to ethereumj => OK
- The transactions performed in ethereumj are not propagated to geth => **ISSUE**

Here are the contract functions [setBalance and setAccountName](https://gist.github.com/skydogch/0aa2c96ae5d4dbfcde0d#file-accounttestcontract-sol-L15-L20) which are called from [AccountWriteTest.java](https://gist.github.com/skydogch/937bda38742d1939456f#file-accountwritetest002-java-L46-L57) and using [ethereum listener](https://gist.github.com/skydogch/9a6ff532df695360fe78)

[Execution_log_example1](https://gist.github.com/skydogch/c37316de960ea2fd6bcd#file-writeexample1-L129-L130), [Execution_log_example2](https://gist.github.com/skydogch/1cf101221b4f11356420#file-write_example2-L510-L511)

Additionally, I can't see any information in the [ethereum listener](https://gist.github.com/skydogch/9a6ff532df695360fe78) concerning the transactions submited. 

Please let me know if you need more information about this test case

**Comment by Nashatyrev** [comment]
Hi @skydogch 
your test looks fine from the first glance. We have the similar sample which works pretty stable with Frontier: https://github.com/ether-camp/feed.reporter.ether.camp/blob/master/src/main/java/com/ethercamp/feedreporter/scheduler/Scheduler.java#L122
One suspect might be calling two transactions at once. Can you try testing with only a single transaction?

**Comment by skydogch** [comment]
Hi @Nashatyrev,

it is still not working. 

I have created a new private testnet where I have deployed the same contract. In the [geth log](https://gist.github.com/skydogch/76cd45b6027a898ba57d#file-geth_max_verbosity-L125-L140), I can't see any transaction coming from ethereumj. (Note: Both peers are running in the same machine)

I have executed the [setBalance and setAccountName](https://gist.github.com/skydogch/0aa2c96ae5d4dbfcde0d#file-accounttestcontract-sol-L15-L20) methods in geth manually and the transaction is propagated from geth to ethereumj without problems. The [geth pendingTransactions](https://gist.github.com/skydogch/f207ad697cd9a860627c) are visible  in [ethereumj listener](https://gist.github.com/skydogch/51be2941fc5461aa23da) after a while (GETH --> ETHEREUMJ).

When I perform *callConstantFunction*, then I read the values propagated from geth to ethereumj.

But I don't know why the submitTransaction doesn't work in my example, it isn't propagated to geth, **although I have changed the [java example](https://gist.github.com/skydogch/47d8387de606eec4becd) to call only one transaction**

I have noticed that the *Transaction*  information is displayed in the console without no hash, [e.g](https://gist.github.com/skydogch/c58f3413c24f23e2b1d3#file-gistfile1-txt-L103-L105), is that a problem?:

````javascript
   TransactionData [hash=  nonce=00, gasPrice=104c533c00, gas=3b9aca00, receiveAddress=4d2430de51342288ce2042263f18198056dc24ac, value=0a, data=d83b066e00000000000000000000000000000000000000000000000000000000000007ba, signatureV=28, signatureR=4d64020edde450b4005e1ec34632a335471d54fd013f2ec05a8b7dde4c071421, signatureS=4b0a65de5b0d1877f0db51f21a404ac998614758cfe377c1fe98554c09f3a081]]
````

Any idea how to deal with this problem? I can read contracts locally, but the transactions aren't executed.

**Comment by Nashatyrev** [comment]
It's ok with `hash` - it should be calculated upon serialization a bit later after the log output. 
That could be some networking issue

**Comment by skydogch** [comment]
Hi @Nashatyrev, you are right. The transaction was wrong and it was not processed successfully by geth.
