### ISSUE TITLE
Creation of new account

### ISSUE THREAD

**Issue by ramtej** [ethereum/ethereumj#335]
Hi guys, 

I would like to create a ethereumj frontier account, but could not find any instructions, e.g. like for the go-ethereum - "geth account new". 

Any ideas ?

Thank you. 

Cheers, 
jj

**Comment by Nashatyrev** [comment]
The console/command line interface is now in pending state. 
Using Java API the account creation is as simple as just creating a random private key and getting its corresponding Ethereum address: 
```
ECKey key = new ECKey();
key.getAddress();
key.getPrivateBytes();
```

**Comment by ramtej** [comment]
Hi, 

thank you, works for me. Just for someone else who has a similar issue and need some conversions of the key representations : 

        ECKey key = new ECKey();

        byte[] addr = key.getAddress();
        byte[] priv = key.getPrivKeyBytes();

        String addrBase16 = Hex.toHexString(addr);
        String privBase16 = Hex.toHexString(priv);

        System.out.println("Address     : " + addrBase16 );
        System.out.println("Private Key : " + privBase16 );

Thanks again. 

Cheers, 
jj

**Comment by blmalone** [comment]
How would I add ether to this account?

**Comment by abhiram-mishra** [comment]
how do you provide the password ?
