### ISSUE TITLE
database.dir value

### ISSUE THREAD

**Issue by mtgran** [ethereum/ethereumj#336]
Hello guys,

the value database.dir (ethereum.conf) works fine if it contains a relative path, e.g. my_working_dir

If the value contains an absolute path (e.g. /home/mtgran/workspace/project/ethereumjdirs/my_working_dir) then only the directory "blocks" is created under database.dir, but not blockqueue, details, hashstore, headerstore and state

1.0.0-stage_2-SNAPSHOT / git.hash: [7dabbcd] / build.time: [GMT]-[25/Dec/2015]-[16:38]

**Comment by Nashatyrev** [comment]
Committed to the nearest release
