### ISSUE TITLE
Error creating bean with name 'nodeManager': Injection of autowired dependencies failed

### ISSUE THREAD

**Issue by mtgran** [ethereum/ethereumj#338]
Hi guys, I've downloaded the last stage jars (build.time: [GMT]-[08/Jan/2016]-[15:56]) and I am getting new errors concerning the dependency injections. I am using currently a quite simple gradle file for my development, but is it needed a new dependency in the gradle file or is the current stage version unstable?

https://gist.github.com/mtgran/3a87fef890a680eb4c6e#file-build-time-gmt-08-jan-2016-15-56-L15

**Comment by mtgran** [comment]
Hi guys, I am using the last stage from yesterday (26.01.2016) and it works fine. I suppose I had problems with the dependency injections on the 08/Jan because of the path configuration, but I am not sure about it. I close the issue

**Comment by Nashatyrev** [comment]
Thanks for update!
