### ISSUE TITLE
Null Pointer exception at wallet.save()

### ISSUE THREAD

**Issue by ygnr** [ethereum/ethereumj#339]
I was trying to add a new account to wallet and save it in wallet using the following functions.

	Ethereum ether = EthereumFactory.createEthereum();
        Wallet wallet = ether.getWallet();
	wallet.addNewAccount();
	wallet.save();

I am getting a null pointer exception in the save method when the code reaches this point in Wallet.java.
value.setTextContent(account.getBalance().toString());

Exception in thread "main" java.lang.NullPointerException
	at org.ethereum.core.Account.getBalance(Account.java:54)
	at org.ethereum.core.Wallet.save(Wallet.java:301)
	at Start.main(Start.java:34)

Because of which I am unable to save accounts to wallet. Am I calling these functions in the right way?

**Comment by Nashatyrev** [comment]
Wallet was removed from the core
