### ISSUE TITLE
Stuck on blockchain download, after second transaction from same sender

### ISSUE THREAD

**Issue by ijohanne** [ethereum/ethereumj#343]
Hi,

I seem to have stumbled over an issue when running EthereumJ on a private network of two geth/1.4.2 clients (one of them is running as a CPU miner).

After sending the second transaction from the same sender, when EthereumJ gets the newest block mined by the miner - it can't connect the block, and spews out the following errors:
505629 INFO  blockchain - Try connect block hash: b3f2cf, number: 10
505629 ERROR blockchain - BlockHeader invalid: #10: difficulty != calcDifficulty
505630 WARN  blockchain - Invalid block with number: 10

After this error it's simply stuck at block# 9 - and can't get any further.

The two accounts in EthereumJ was created using the following code ("test123" for the first address, also in the genesis block, and "test1234" for the second the receiver):
```
public String createNewAddress( String password)  {
    byte[] sec = HashUtil.sha3(password.getBytes());
    ethereum.getWallet().importKey(sec);
    try {
        ethereum.getWallet().save();
    } catch( ParserConfigurationException|TransformerException e ) {
        return null;
    }
    ECKey key = ECKey.fromPrivate(sec);
    String address = Hex.toHexString(key.getAddress());
    return address;
}
```

The transactions was sent using the following method (input the address gotten in th previous in hex without "0x", 0 and 1 for nonce, 1000000000000000000 as amount, and the password for the first account "test123" as the password to sign with):
```
public String sendTx( String toAddy, long nonce, String amount, String password) {
    Transaction tx = ethereum.createTransaction(BigInteger.valueOf(nonce), new BigInteger("10000000000000"), BigInteger.valueOf(21000L), Hex.decode(toAddy), new BigInteger(amount), new byte[]{});
    ECKey key = ECKey.fromPrivate(HashUtil.sha3(password.getBytes()));
    tx.sign(key.getPrivKeyBytes());
    Future<Transaction> netTx = ethereum.submitTransaction(tx);
    while( !netTx.isDone()) {
        System.out.println("Waiting for network for tx " + tx.getHash());
    }
    try {
        return Hex.toHexString(netTx.get().getHash());
    } catch( InterruptedException|ExecutionException e ) {
        return null;
    }
}
```

The genesis file I used was as follows:
```
{
    "alloc": {
        "2679bb15ab1768dd96d4db5ce422a48853318083": {
            "balance": "10000000000000000000"
        },
        "d871db2091b0f41c52cce5c75d224837e5961111" : {
            "balance" : "10000000000000000000"
        }
    },
    "nonce": "0x0000000000000042",
    "difficulty": "0x400000",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "gasLimit": "0x4c4b40"
}
```

All the code is in a gradle project using this dependency for ethereumj-code (which I assume is either the master or stage branch to be found on github):
```
compile ("org.ethereum:ethereumj-core:1.1.0-RELEASE"){
    exclude group: "log4j"
    exclude group: "org.slf4j", module: "log4j-over-slf4j"
    exclude group: "org.slf4j", module: "slf4j-log4j12"
}
```

To me this clearly seems like a big - though I haven't been able to narrow it down further in the ethereumj-core code.

**Comment by Nashatyrev** [comment]
`BigInteger.valueOf(21000L)`: looks like a starting txt nonce for Morden. Can you please share the `geth` command you are running. If you have, try to remove the `--testnet` option

**Comment by Nashatyrev** [comment]
... and change the initial tx nonce to `0`

**Comment by ijohanne** [comment]
For the first tx the nonce is 0, and for the second 1 
The 21000 is used as gasPrice, according to the signature I found in the source for createTransaction:
```
Transaction createTransaction(BigInteger nonce,
                                 BigInteger gasPrice,
                                 BigInteger gas,
                                 byte[] receiveAddress,
                                 BigInteger value, byte[] data);
```
The args I use for geth is 
`build/bin/geth --networkid "31337" --port "30302" --datadir "/home/ij/eth-testnet" --verbosity "1" --genesis genesis.json console`

**Comment by Nashatyrev** [comment]
Oh, I see, my miss. 
That's strange, the similar net configuration works pretty fine for me. 
It seem the only way to debug this problem is to share logs with us. Just lower the following logger levels: 
```
blockqueue = TRACE
wire =  DEBUG
```
That will logs processed blocks and incoming messages to pick the 'bad' header

**Comment by ijohanne** [comment]
I had quite a bit of fun trying to get log4j overridden properly, so instead I checked out the master branch of ethereumj, put in my config and genesis (both attached - one of the peers is globally reachable, so you can re-run this if needed, passwords and anything else in the files are random generated just for this test, so no problems either just reusing it straight off the bat).

I managed to find out that I somewhere along the testing put blockchain.only to true, and if it's set to false (the default) I get an entirely different error (separate log attached for this).

The blockchain in these logfiles doesn't even have the transactions in there - only the two geth nodes, where one is mining (as soon as the mining geth node manages to complete the DTAG and push one block onto the chain - ethereumj starts spewing out these errors).


[Logs+config.zip](https://github.com/ethereum/ethereumj/files/134536/Logs.config.zip)

**Comment by ijohanne** [comment]
@Nashatyrev - I still have one of those nodes running publicly accessible, so I was curious if you had any time to test this (or look through the logs) ?

**Comment by ijohanne** [comment]
@Nashatyrev - I tried a few things, including using the same genesis they use for the morden network, and the error is the same with this. Could the bug I've reported be related to #345 or #346 possibly?

**Comment by Nashatyrev** [comment]
Hi @ijohanne, couldn't connect to your node `enode://9c91e56acd864e39571a79028c34cd1b449cde57aa9f7245e8c78cb47fc07b9a354872e6f9d36d81f8eefc9f28ec4121ac647c1423fd7b1fa1db97978d338649@5.196.33.170:30302`
Is it still running?

**Comment by Nashatyrev** [comment]
It opens connection however I got no response on `AuthInitiate` message. Can you please check your nodeId?

**Comment by ijohanne** [comment]
Hi @Nashatyrev, I tried quite a few things since then - and had to use that node for that. However I've recreated the test (and verified ethereumj still spews out the same error). The enode URL is now:
enode://97345380ad9c00eba5032f31450fd77d17d50b97d642755f087fe73f5ede32786bc18922e17519ac3e0f408c45bd0487765fcfa7012d4a7fa504d5fdb3ced924@5.196.33.170:30302

**Comment by Nashatyrev** [comment]
Ok, found the problem: try renaming genesis file so it contains 'frontier' string, this is the way we are currently identifying the frontier constants which are not in the genesis file. In your case this is DURATION_LIMIT. 
That should be definitely fixed

**Comment by ijohanne** [comment]
@Nashatyrev that was spot on, not a thing I even noticed was a requirement. It now works for me. Thanks a lot!

**Comment by Nashatyrev** [comment]
Fixed in branch. Now we have separate Blockchain settings not bound to genesis file name
