### ISSUE TITLE
Morden's IAN

### ISSUE THREAD

**Issue by mtgran** [ethereum/ethereumj#345]
Hi guys,

ethereumj can't connect to Morden because Morden's IAN is 2^20

The nonces of the accounts contained in the genesis play a role in the genesis' hash. If it is not configured to 2^20 then the connection with e.g Geth doesn't work.

@bitledger has a version for morden change:

https://github.com/bitledger/ethereumj/blob/morden/ethereumj-core/src/main/java/org/ethereum/core/AccountState.java#L48-L57

https://github.com/ethereum/ethereumj/blob/68b5b462fc0a4e21600f5cd2cbb9c0fe7723a697/ethereumj-core/src/main/java/org/ethereum/core/Block.java#L34-L36

https://github.com/ethereum/ethereumj/blob/68b5b462fc0a4e21600f5cd2cbb9c0fe7723a697/ethereumj-core/src/main/java/org/ethereum/core/genesis/GenesisLoader.java#L103

https://github.com/ethereum/ethereumj/commit/68b5b462fc0a4e21600f5cd2cbb9c0fe7723a697

**Comment by Nashatyrev** [comment]
Mikhail is working on this right now :)

**Comment by mtgran** [comment]
Great!

Guys, you are doing an amazing job ...

**Comment by mtbitcoin** [comment]
Thank you!!

**Comment by mtgran** [comment]
I am using the last stage version and the connection to morden works fine :+1:

**Comment by mtbitcoin** [comment]
yes, connection works now.
