### ISSUE TITLE
Testnet Morden

### ISSUE THREAD

**Issue by mtbitcoin** [ethereum/ethereumj#349]
I am unable to get testnet morden running with following modifications in ethereumj.conf . I am running the lastest ethereumj-core:1.1.0-stage-SNAPSHOT 

ip.list = [
        "94.242.229.4:40404",
        "94.242.229.203:30303"
    ]
genesis = frontier-morden.json

database {
    # place to save physical storage files
    dir = database-morden
}

# Network id
    networkId = 2

---
The errors loop I am currently running into are :

10:41:10.642 INFO  com.ethercamp.starter.Application - Started Application in 14
.444 seconds (JVM running for 15.431)
10:41:31.183 WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() eve
nt was fired, and it reached at the tail of the pipeline. It usually means the l
ast handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException: null

**Comment by Nashatyrev** [comment]
Strange... 
I see you are running `starter.Application` Did you try running the pure EthereumJ app with the same Mordern settings:
```
> git clone https://github.com/ethereum/ethereumj
> cd ethereumj
> gradlew run [-PmainClass=<sample class>]
```

**Comment by mkalinin** [comment]
or you can run it with
```
gradlew runMorden
```
if it's convenient to you

**Comment by mtbitcoin** [comment]
@mkalinin Thanks. That seem to have worked.

**Comment by mtbitcoin** [comment]
Just to add a note for those running into similar issues.. it seems after few minutes the error message went away and it was able to process the blocks.

**Comment by mtbitcoin** [comment]
reopened
