### ISSUE TITLE
Morden - First Nonce for 0xaed50e8d2637b08b2b29c70da003bfd7d5578ecb is 0

### ISSUE THREAD

**Issue by mtgran** [ethereum/ethereumj#350]
Hi guys,

I have assigned 27 ETH to the address aed50e8d2637b08b2b29c70da003bfd7d5578ecb using this [webpage](https://zerogox.com/ethereum/wei_faucet).

Geth returns a balance of 27000000000000000000 for that address

Although I still have not performed any transaction, nonce **0** is returned from getRepository().getNonce(Hex.decode("aed50e8d2637b08b2b29c70da003bfd7d5578ecb")). 
It should return Morden's IAN

**Comment by mkalinin** [comment]
Hi @mtgran,
I've checked your address via my peer which is in sync with Morden. And it has `1048576` nonce. Had your peer finished sync before you checked nonce?

**Comment by mtgran** [comment]
Hi @mkalinin , I am synchronizing now my node, and I am doing a test with two accounts and this are the returned nonces:

0xaed50e8d2637b08b2b29c70da003bfd7d5578ecb -> 1048576
0x53ad733c96ac22846c3b843e2c674579158b786d -> 0

I suppose that if information about 0x53ad733c96ac22846c3b843e2c674579158b786d has not been synchronized in EthereumJ, then it returns 0. 

Maybe because `getAccountState(addr)` don't find the address?

**Comment by mtgran** [comment]
Hi guys, 

I've downloaded the last stage version and even before synchronizing the node, it returns 2^20 for aed50e8d2637b08b2b29c70da003bfd7d5578ec :+1: 

Thanks a lot!
