### ISSUE TITLE
Consensus failure; ecrecover precompiled contract

### ISSUE THREAD

**Issue by holiman** [ethereum/ethereumj#353]
The ecrecover contract suffers from a lot of the same issues that also affected C++/Python issues reported here: http://martin.swende.se/blog/Devcon1-and-contract-security.html .

Anyway, here's the code

        public byte[] execute(byte[] data) {

            byte[] h = new byte[32];
            byte[] v = new byte[32];
            byte[] r = new byte[32];
            byte[] s = new byte[32];

            DataWord out = null;

            try {
                System.arraycopy(data, 0, h, 0, 32);
                System.arraycopy(data, 32, v, 0, 32);
                System.arraycopy(data, 64, r, 0, 32);

                int sLength = data.length < 128 ? data.length - 96 : 32;
                System.arraycopy(data, 96, s, 0, sLength);

                ECKey.ECDSASignature signature = ECKey.ECDSASignature.fromComponents(r, s, v[31]);

                ECKey key = ECKey.signatureToKey(h, signature.toBase64());
                out = new DataWord(key.getAddress());
            } catch (Throwable any) {
            	any.printStackTrace();
            }

            if (out == null) out = new DataWord(0);

            return out.getData();
        }
    }

You can compare with python here: https://github.com/ethereum/pyethereum/blob/develop/ethereum/specials.py. 

Problems:
- `v`, `r` and `s` are not validated (e.g. if v!=27)
- If error occurs, it will return `new DataWord(0)`, instead of empty byte-array. There's a subtle difference, which can cause consensus fork if the return value is set to overwrite a memory location which is non-zero. The emtpy byte array won't overwrite, whereas the zero-filled bytearray will.

**Comment by holiman** [comment]
I'm still trying to get the framework running, exploring it a bit. To fix it properly there should be supporting testcases aswell. Sorry, but I think it's better fixed properly by existing developers.

**Comment by romanman** [comment]
@holiman : ok we will include it to our task list :+1: 
thank you for the report

**Comment by mkalinin** [comment]
The fix is here https://github.com/ethereum/ethereumj/commit/e85d8c3199bc13405ff4ba180697165751fe8e6a
