### ISSUE TITLE
Consensus failure; double suicide

### ISSUE THREAD

**Issue by holiman** [ethereum/ethereumj#354]
The java-client _appears_ to suffer from the issue reported here: http://martin.swende.se/blog/Another_ethereum_vulnerability.html . 

Caveat: I've not verified this, only browsed the code. From what I can see, suicides are added to a list. At finalization, the list size is simply counted, and rewards are calculated; basically exactly what the python client did earlier. 

Apologies if I've misunderstood something here.

**Comment by Nashatyrev** [comment]
@holiman Thanks for reporting. You was completely right. The issue is fixed now in `stage` and `develop`
