### ISSUE TITLE
Updating to Java 8

### ISSUE THREAD

**Issue by loxal** [ethereum/ethereumj#357]
Thanks for merging my PRs, Anton!

I would like to do further contributions. I see that the source code is not using any Java 8 language constructs, like native lambdas (w/ native bytecode lambda representation that might further improve performance). I would like to replace anonymous inner classes with lambdas if you do not object :)

**Comment by romanman** [comment]
@loxal we intentionally stay on 7 level , 
for android compatibility

**Comment by loxal** [comment]
@romanman Ok, understand. With Android 7, Google is going do dump Dalvik in favor of OpenJDKs VM (big news, a month ago…) which would enable Java 8 support. Do you still want to stay Java 7 compatible for some time or for a much longer period of time?

**Comment by romanman** [comment]
@loxal yeah want to see it first

**Comment by Nashatyrev** [comment]
Ok, closing this for now
