### ISSUE TITLE
Excluded IntelliJ IDEA project meta-data

### ISSUE THREAD

**Issue by loxal** [ethereum/ethereumj#359]
Is there a reason why IntelliJ IDEA’s project metadata is excluded via .gitignore? Including it would improve startup times of the IDE, assure that a project is not imported in an undesirable way and would also make it possible to share Run Configurations, copyright headers, coding styles, artifact configurations etc. 

And TeamCity CI can even use .idea to build a project and its artifacts.

**Comment by loxal** [comment]
I know that in the time as Eclipse was more popular than today, it would not make sense to commit these files as Eclipse stored something like “C:\myveryownfolder/myproject” (absolute paths) and user data like which tabs are open and which buttons are visible. That’s not the case with IntlliJ. wokspace.xml is the only file that needs to be excluded.

This would really improve the out-of-the-box experience and make development easier even for those who know IntelliJ very well.

**Comment by romanman** [comment]
@loxal this days all the IDEs
has very good import tools
so no need to add this files
to the core.

**Comment by Nashatyrev** [comment]
Agree with @romanman, all project deps are managed by the gradle and imported to IDEA with two mouse clicks. Putting IDEA project would duplicate that information and additionally will require us extra efforts to keep this in sync. 
As well everyone tunes his project on his choice and cleaning it up before commit would be annoying

**Comment by loxal** [comment]
Actually I made very good experience in multi-years project in multiple teams with this approach. There are no sync issues as the IDE should always sync to the changes from SCM and not otherwise (this is the actual intent).

The obvious disadvantage in auto-imports is that folders like `build` are not excluded so the auto-import could be better… Also the information of other excluded folders like the database folder (done by experienced developers) does not reach novice developers. When the settings are messed up one cannot simply do a `get reset` and reimporting the projects is not an option as many fine-adjustments are lost this way. Well actually there are many other advantages and IntelliJ guys themselves commit the folders to SCM. 

Well, but as you decide…
