### ISSUE TITLE
Failing tests in “develop” branch

### ISSUE THREAD

**Issue by loxal** [ethereum/ethereumj#360]
These tests are failing when I run the tests locally on my Mac:

> org.ethereum.core.TransactionTest#multiSuicideTest
> org.ethereum.solidity.CompilerTest#simpleTest

The code cannot deal with an empty string that is returned but I guess the problem is that an empty string is returned at all. Also org.ethereum.solidity.CompilerTest#simpleTest should get an assertion. I’ve fixed the tests in a way that they way because of not fulfilled assertions but not because of some unexpected behavior. A corresponding PR follow in minutes :)

**Comment by Nashatyrev** [comment]
Thanks for PR! 
Solc on Mac should work from 1.2.0
