### ISSUE TITLE
App crashes after a while

### ISSUE THREAD

**Issue by loxal** [ethereum/ethereumj#362]
This is the last few lines one sees when running the app for a while using `java -jar target/ethereumj-v1.1.0-SNAPSHOT-jar-with-dependencies.jar -listen 8545 -db databasenew -reset no -listen 20202`:

> 19:04:48.570 INFO [blockqueue]  Success importing BEST: block.number: 1149144, block.hash: 9e7f2d, tx.size: 7 
> 19:04:48.581 INFO [blockqueue]  Success importing BEST: block.number: 1149145, block.hash: ae8972, tx.size: 1 
> 19:04:48.702 INFO [blockqueue]  Success importing BEST: block.number: 1149146, block.hash: 8238a6, tx.size: 14 
> 19:04:48.775 INFO [blockqueue]  Success importing BEST: block.number: 1149147, block.hash: 0a8d7c, tx.size: 4 
> 19:04:48.780 INFO [blockqueue]  Success importing BEST: block.number: 1149148, block.hash: 70c4c7, tx.size: 1 
> 19:04:48.879 INFO [blockqueue]  Success importing BEST: block.number: 1149149, block.hash: c3091b, tx.size: 5 
> 19:04:48.933 ERROR [blockchain]  Block's given Receipt Hash doesn't match: 927e20837679eece7160879210a3634d7446c4d52a5689ff47da345c213b8351 != a8396f1859a16d84e386d1536edffee5829891ce5bf633a8511f06bb9ba6776a
> 19:04:48.933 ERROR [state]  BLOCK: STATE CONFLICT! block: 1149150 worldstate 2e0e488cb7b49e319e0941b75a9a2bf5a9a767b92a17e6c1ba86e1f34714c651 mismatch
> 19:04:48.933 ERROR [state]  Conflict block dump: f905caf90219a0c3091b4857e93211651f798df7f41ed1a77d56b8f3ef5904cb2a8a8ee7e58f46a05d06bdea930da3e8e14e8769506c733bd8c40af87676370c3ab4aafb4cff15b294bed5ff5133ab2cf914476f0bff8d6d29fee13b0ea04cf644c50f4b6ea94109a86dcfc070ef31a89ead608fa37f3595b0f2f42c2992a03dcbdf608b14191dde2928e525ccb0aa878e58e2b75743c8967e780c29c873cfa0927e20837679eece7160879210a3634d7446c4d52a5689ff47da345c213b8351b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000861281176a7a4c831188de8347e7c4827c4d8456e6d1069ad983010305844765746887676f312e352e318777696e646f7773a0f51d76a0ad9ad081e97701d1442f0dd90bad79c5ddee30081a4587c1d0956fd3887e62ff8d0b63ef1df90190f9018d8204ab850ba43b740083015f9094c2d7e0d1e7d545ad0db3a34570344410988ca20780b90124cffafd890000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001ffbe3df0cf030655d817a89936850d1cc00c07c35d3b21be73cfe9a730ea8b75362d73b6a92ac23ff514315fad795bbac6d485481d356329d71467e93c87dfa422386f26fc1000000000000000000000000000000000000000000000000000000a74d69c0aef9166aca23d563f38cbf85fe3e39a60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ba089700c12a4c0c427cd152e23fc2aee5710a960b3599ea0ebc013cb155f538819a012990dc6c756b6f541248c2653d172d36ee58c2e901eafbf8bd35fb0dafca3a9f90218f90215a00a8d7c9498d94808e085a9915db6e5a252fa61a210bdf4114ddbf6ffec8c093ba01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479468795c4aa09d6f4ed3e5deddf8c2ad3049a601daa0bef4574634e2047d161e837c8a68ded304f64ddfd96cf44ddfcf148aec198bd5a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000086127c780283cc831188dc8347d6c1808456e6d0fa98d783010400844765746887676f312e352e31856c696e7578a0e77a3a99079c163a2808a169254fec3146f7488ab815f1e56e5a001526dfb51b8885b17662a961c8e3
> CONFLICT: BLOCK #1149150, dump: f905caf90219a0c3091b4857e93211651f798df7f41ed1a77d56b8f3ef5904cb2a8a8ee7e58f46a05d06bdea930da3e8e14e8769506c733bd8c40af87676370c3ab4aafb4cff15b294bed5ff5133ab2cf914476f0bff8d6d29fee13b0ea04cf644c50f4b6ea94109a86dcfc070ef31a89ead608fa37f3595b0f2f42c2992a03dcbdf608b14191dde2928e525ccb0aa878e58e2b75743c8967e780c29c873cfa0927e20837679eece7160879210a3634d7446c4d52a5689ff47da345c213b8351b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000861281176a7a4c831188de8347e7c4827c4d8456e6d1069ad983010305844765746887676f312e352e318777696e646f7773a0f51d76a0ad9ad081e97701d1442f0dd90bad79c5ddee30081a4587c1d0956fd3887e62ff8d0b63ef1df90190f9018d8204ab850ba43b740083015f9094c2d7e0d1e7d545ad0db3a34570344410988ca20780b90124cffafd890000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001ffbe3df0cf030655d817a89936850d1cc00c07c35d3b21be73cfe9a730ea8b75362d73b6a92ac23ff514315fad795bbac6d485481d356329d71467e93c87dfa422386f26fc1000000000000000000000000000000000000000000000000000000a74d69c0aef9166aca23d563f38cbf85fe3e39a60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ba089700c12a4c0c427cd152e23fc2aee5710a960b3599ea0ebc013cb155f538819a012990dc6c756b6f541248c2653d172d36ee58c2e901eafbf8bd35fb0dafca3a9f90218f90215a00a8d7c9498d94808e085a9915db6e5a252fa61a210bdf4114ddbf6ffec8c093ba01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479468795c4aa09d6f4ed3e5deddf8c2ad3049a601daa0bef4574634e2047d161e837c8a68ded304f64ddfd96cf44ddfcf148aec198bd5a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000086127c780283cc831188dc8347d6c1808456e6d0fa98d783010400844765746887676f312e352e31856c696e7578a0e77a3a99079c163a2808a169254fec3146f7488ab815f1e56e5a001526dfb51b8885b17662a961c8e3

**Comment by Nashatyrev** [comment]
Hi, I suppose you are using `develop` branch? You would better work with the `stage` branch (the corresponding artifact is `1.1.0-stage-SNAPSHOT`) since all the fresh fixes goes there. A bunch of conflicts were resolved there last days. Please try to run with the `stage`

**Comment by loxal** [comment]
develop, master, stage… I’m a bit confused… I suppose: master = release; develop = integration; stage = feature branch?

**Comment by Nashatyrev** [comment]
Ok I believe we fixed all known conflicts for now. `develop` is the only working branch now
