### ISSUE TITLE
Critical: Local JSON RPCs are not working

### ISSUE THREAD

**Issue by loxal** [ethereum/ethereumj#371]
Doing 
```
curl -X POST -d '{
    "jsonrpc":"2.0",
    "method":"eth_getBalance",
    "params":[
        "0xfff43434509ed7be4151f69158b9050c7af331a8", "latest"
        ],
    "id":1
}' "http://localhost:8545"
```
gives me a timeout on latest “stage” code. I remember this was broken in Parity in a pre-1.0 phase but it works w/ Parity. This is is just an example. I guess every other REST call will timeout as well. Works with Parity v1.0.1:

```
curl -X POST -d '{
    "jsonrpc":"2.0",
    "method":"eth_getBalance",
    "params":[
        "0xfff43434509ed7be4151f69158b9050c7af331a8", "latest"
        ],
    "id":1
}' "http://sky.loxal.net:8545"
```

It looks like EthereumJ server is saturated and is out of free threads. To start the server, I’ve used 
`java -jar build/libs/ethereumj-core-1.1.0-stage-SNAPSHOT-all.jar -listen 8545`. The database is populated up to the latest Ethereum block.

**Comment by romanman** [comment]
Hi @loxal ,

Thanks for reporting,
the thing is that core
lib doesn't support
RPC and it is in develop 
subject, in wrapper lib

**Comment by loxal** [comment]
Haven’t got the last one “subject, in wrapper lib”? For me this feature is pretty crucial as this is what would make many users switch to EthereumJ who cannot use GPLv3ed Parity and want to develop closed-source software.

**Comment by romanman** [comment]
@loxal that is right, this is 
a different beeimg developed
project. Soon to be released

**Comment by loxal** [comment]
So will this feature  be soon available as part of the EthereumJ server?

**Comment by romanman** [comment]
Alex my dear, java support
for Ethereum json rpc is our
wrapper project, and will be
available soon
