### ISSUE TITLE
Ethereum.close() implementation 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#385]
Subj

**Comment by Nashatyrev** [comment]
Rose Toomey: my definition of a successful shutdown is that when i call close() all resources are dealt with: file handles are closed, locks are released, thread pools are shut down, listeners are stopped, etc - imagine i have an external application which is doing a hot deploy (since we're in Java-land, say i'm using JRebel) - when there is a hot redeploy of my code, then my application server's stop method is called, and then the start method is called

**Comment by rktoomey** [comment]
Trying to fix this in our fork and submit an upstream PR

**Comment by rktoomey** [comment]
This has been merged into the gemini fork for testing locally and will be submitted upstream shortly
