### ISSUE TITLE
TransactionReceipt needs clear indication on whether the Transaction was successful 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#386]
If a block contains transaction with e.g. low gas, the `TransactionReceipt` has no indication that tx was not completed successfully. The only mean to find this out is to compare `txStateRoot` with the previous transaction. If this value has not changed then something went wrong

**Comment by Melvillian** [comment]
I think you can close this one because of commit 2da0f6bc2eae383ac12b876641169ffe0316d2b8

**Comment by Nashatyrev** [comment]
@Melvillian oh, yes, thanks!
