### ISSUE TITLE
CreateContractSample hangs when I run it

### ISSUE THREAD

**Issue by adridadou** [ethereum/ethereumj#390]
When I run CreateContractSample I keep getting:

> 14:44:39.864 INFO [sample]  No Eth nodes found so far. Keep searching...
> 14:44:44.869 INFO [sample]  No Eth nodes found so far. Keep searching...
> 14:44:49.874 INFO [sample]  No Eth nodes found so far. Keep searching...
> 14:44:54.876 INFO [sample]  No Eth nodes found so far. Keep searching...
> 14:44:59.880 INFO [sample]  No Eth nodes found so far. Keep searching...
> 14:45:04.884 INFO [sample]  No Eth nodes found so far. Keep searching...

It seems that the configuration for the testnet and morden is out of date because when I run it without any special config I get the blocks from the main net.

I ran the CreateContractSample from the master branch

**Comment by Nashatyrev** [comment]
If you are still observing this problem please feel free to reopen
