### ISSUE TITLE
Getting "No parent on the chain" error on sync

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#409]
Hello. My DB crashed. I've deleted old one and tried to start again, but it failed on 1150001 block. I've deleted DB again, started over and the same issue repeats.

Here's the log:
> INFO SyncQueueThread blockqueue.produceQueue - Success importing BEST: block.number: 1150000, block.hash: c4efcc, tx.size: 0 
> ERROR SyncQueueThread blockchain.logErrors - BlockHeader invalid: #1150001: difficulty != calcDifficulty
> WARN SyncQueueThread blockchain.add - Invalid block with number: 1150001
> INFO SyncQueueThread blockqueue.produceQueue - No parent on the chain for block.number: 1150002 block.hash: f91b13
> INFO SyncQueueThread blockqueue.produceQueue - No parent on the chain for block.number: 1150002 block.hash: f91b13
> INFO SyncQueueThread blockqueue.produceQueue - No parent on the chain for block.number: 1150002 block.hash: f91b13

Any suggestions how to fix it?
Thank you

**Comment by Nashatyrev** [comment]
Hi @zilm13, the block `1150000` is the starting point for Homestead (for the main and test networks), it seems your config has some problems. For the test network I've fix the bug (in `develop`) which resolves the similar issue, please check you are using the latest develop build. 
What network are you running on and did you change the config?

**Comment by zilm13** [comment]
I'm using 1.2.5-RELEASE, config is the same as test.conf from the package. 
Should I switch to develop version?

**Comment by Nashatyrev** [comment]
Yep, please try the develop version

**Comment by zilm13** [comment]
Great, it works.
Thank you!

**Comment by himanshuoodles** [comment]
@zlim and @Nashatyrev  I am using org.ethereum:ethereumj-core:1.2.5-SNAPSHOT and getting error .
ERROR [sync] No parent on the chain for block.number: 1240068 block.hash: fb5c95. What should i do .

**Comment by zilm13** [comment]
@himanshuoodles 
1.2.5 is very old version. It doesn't include latest hard fork logic, fixes for latest attacks, many improvements etc.
You should resync with latest version (1.3.6-RELEASE). DB was changed, so you will need to reset it.
