### ISSUE TITLE
Groovy convert of Miner sample 

### ISSUE THREAD

**Issue by romanman** [ethereum/ethereumj#413]
`amiracam [9:38 PM]
Yesterday at 9:38 PM`
Hi, I’m trying to convert the PrivateMinerSample to Groovy , everything compiles and my mods have 
been minor, as a matter of fact just class renaming since I just copied the original file. Everything at 
first glance seems to startup fine, but closer inspection shows that the private config classes i.e. for the Miner and Regular config classes are apparently ignored. I have attached the logs, I would appreciate somebody confirming that, I also have attached the modified code as well, thanks. 

log: 
https://slack-files.com/T0CTBDBQ8-F1ETD9WDA-c9c39e7e31

**Comment by Nashatyrev** [comment]
Why do you think the config classes are ignored? 
@romanman Can we add amiracam to this issue CC?

**Comment by romanman** [comment]
@Nashatyrev yep referred him to that link, 
I guess he will push more info for us

**Comment by romanman** [comment]
```
amiracam [6:05 PM]  
@romanj: that’s the point I have not changed the code but made some name changes to avoid name conflicts  but I’m using Groovy, Groovy is a cross compiler. I don’t get any compilation errors but if  you look at the log it seems that the   configurations passed in are being ignored and that it thus defaults to the use of the EthJ system default conf i.e. ethereum.conf, frankly I don’t care to use the static classes for config, so I just need to figure out what the expected interface so that I can create an entity that can abide
```

**Comment by amiracam** [comment]
ok, FYI, my process for absorbing this was to do a build as per your instructions a project in IDEA , I then added Grooyy as a dependency and IDEA configured the project for Groovy i.e. the Groovy compiler is used. To test Groovy I would simply change the file extension from .java to .groovy and then handle what ever inconsistencies, I can do that again btw, do you all have a new build ?

**Comment by amiracam** [comment]
btw, being able to use EthereumJ through a clean dynamic language style interface I feel would be very attractive to everybody else already trying to do so via other means but not running on a powerful VM  i.e. the JVM

**Comment by Nashatyrev** [comment]
@amiracam, regarding your config issue: from your logs everything looks good. The log is the same as with a clean Java run. What problems are you experiencing?

**Comment by amiracam** [comment]
then pardon my ignorance, the output seems to indicate that the default  ethereum.conf was used as opposed to a passed in config e.g. RegularConfig, MInerConfig 

  ```
public static void main(String[] args) throws Exception {
        BasicSample.sLogger.info("Starting EthtereumJ miner instance!");
        EthereumFactory.createEthereum(MinerConfigGroovy.class);

        BasicSample.sLogger.info("Starting EthtereumJ regular instance!");
        EthereumFactory.createEthereum(RegularConfigGroovy.class);
    }
```
and as assumed from here:

> :22:46.771 INFO [sample]  Starting EthtereumJ miner instance!
> 14:22:46.896 INFO [general]  Config ( yes ): default properties from resource 'ethereumj.conf'
> 14:22:46.896 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.res resource 'null'
> 14:22:46.897 INFO [general]  Config ( no  ): user properties from resource 'user.conf'
> 14:22:46.899 INFO [general]  Config ( no  ): user properties from file '/Users/charles/IdeaProjects/ethereumj/config/ethereumj.conf'
> 14:22:46.899 INFO [general]  Config ( no  ): test properties from resource 'test-ethereumj.conf'
> 14:22:46.899 INFO [general]  Config ( no  ): test properties from resource 'test-user.conf'
> 14:22:46.900 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.file file 'null'
> 14:22:46.900 INFO [general]  Config ( no  ): config passed via constructor

Now I attempted to compare results with the clean Java version i.e. PrivateMinerSample however, at the moment I'm having an issue with a no class def found for that class and furthermore to have a totally controlled experiment I should really have a second clean copy of EthereumJ i.e. not under Groovy control. I'll do so now.

**Comment by Nashatyrev** [comment]
@amiracam You actually need a Spring config mostly to run several nodes in a single JVM. This kind of configuration is not reflected in logs. 
In all other cases you may configure the node statically (reflected in this log) You may check the options: https://github.com/ethereum/ethereumj#configuring-ethereumj

**Comment by amiracam** [comment]
np, I'll attempt the non Spring configs, in the meanwhile I am encountering an error in attempting to create a new IDEA project from the latest git repo, I started a new issue for that. thanks
