### ISSUE TITLE
can't import into IDEA

### ISSUE THREAD

**Issue by amiracam** [ethereum/ethereumj#414]
from latest git repo, and after following the instructions provided I get:

http://www.screencast.com/t/dtkjENtb

**Comment by Nashatyrev** [comment]
Reproduced with `Use local gradle distribution`, but works fine with option `Use default gradle wrapper`

**Comment by amiracam** [comment]
fine, thanks

**Comment by Nashatyrev** [comment]
@amiracam Did you have `Use local gradle distribution` as a default option in IDEA?

**Comment by amiracam** [comment]
well actually no, looking back at the attached pic now , and also reproducing the process IDEA seems to by default have "Use default grade wrapper" selected

**Comment by amiracam** [comment]
ok, I built successfully now, not a very controlled experiment , but what I did is that I invalidated my IDEA cache and also closed all other projects and went to the start page wizard and ran the import wizard i.e. as opposed to proceeding via the File > import from existing source method, now i have a clean Java build , and will now create a second build which I will configure for Groovy use
