### ISSUE TITLE
Mining failed after mined 30,000 blocks, and can not restart mining again

### ISSUE THREAD

**Issue by mhoudg** [ethereum/ethereumj#420]
[mine_30k_bug.txt](https://github.com/ethereum/ethereumj/files/315326/mine_30k_bug.txt)

I created a pure private blockchain to test smart contract, after several days, when the block creased to 30,000 block, the miner not work any more.

I have to remove all the database dir, and lost all data before.

**Comment by Nashatyrev** [comment]
Sounds like the issue with new DAG calculation for the new epoch (each 30K blocks). We are lacking precalc for now so it should take ~10min to calculate a new one

**Comment by Nashatyrev** [comment]
Reproduced in `master`, in `develop` it is already fixed
The issues was in incorrect caching of the DAG in file. To workaround this issue you just needed to remove `database/mine-dag.dat` file
