### ISSUE TITLE
Move 'jsontestsuite' package to test 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#422]

**Comment by romanman** [comment]
There is option to run the tests in gradle
I think in test location it wont work

**Comment by zilm13** [comment]
Tried to move, looks like gradle handles tckRun from tests #479

**Comment by Nashatyrev** [comment]
@zilm13 Thanks for PR. I guess we can close this issue?

**Comment by zilm13** [comment]
@Nashatyrev sure
