### ISSUE TITLE
keystore implementation

### ISSUE THREAD

**Issue by The-Neo-Noir** [ethereum/ethereumj#423]
How about a keystore implementation just like geth with support of password to encrypt the keystore file.

**Comment by Nashatyrev** [comment]
@cupuyc I think we are on the way to implement this

**Comment by cupuyc** [comment]
@The-Neo-Noir you can find that feature at https://github.com/ether-camp/ethereum-harmony/tree/master/src/main/java/com/ethercamp/harmony/keystore
It is still under construction.

**Comment by Nashatyrev** [comment]
Keystore is now in the Ethereum Harmony project: https://github.com/ether-camp/ethereum-harmony
Welcome to test!

**Comment by yossikolel** [comment]
Hi, 

looks good, when it will be integrated into ethereumj project?

**Comment by cupuyc** [comment]
@yossikolel our plan is to not keep extra features in core library. That's why JSON-RPC and keystore will be maintained in the Harmony repo.
