### ISSUE TITLE
ContractDetailsImpl leveldb persistence bug

### ISSUE THREAD

**Issue by oscarguindzberg** [ethereum/ethereumj#425]
There is a race condition if 2 threads are using the same contract at the same time.
Eg. I am sending a tx to contract via web3/rpc interface and at the same time I receive a block with a tx to the same contract.

Thread 1: Sends a tx to a contract:  
- JsonRpcImpl.eth_sendTransaction()
- EthereumImpl.submitTransaction()
- PendingStateImpl.addPendingTransaction(transaction);
- PendingStateImpl.executeTx()
- ...
- RepositoryImpl.getStorageValue(): Before calling ContractDetailsCacheImpl.get(), this calls RepositoryImpl.getContractDetails() which calls DetailsDataStore.get() which calls new ContractDetailsImpl(byte[] rlpCode) which calls ContractDetailsImpl.decode() which calls ContractDetailsImpl.getExternalStorageDataSource(): this opens the leveldb db if not already opened
- ContractDetailsCacheImpl.get()
- ContractDetailsImpl.get()
- TrieImpl.get()
- Cache.get()
- LevelDbDataSource.get(): this uses the leveldb db

Thread 2: Receives a block:
- BlockchainImpl.add(Block block)
- BlockchainImpl.flush()
- ...
- RepositoryImpl.flush()
- DetailsDataStore.flush()
- DetailsDataStore.flushInternal()
...
- ContractDetailsImpl.syncStorage(): This opens the leveldb db (if not already opened), saves contract data to it, then closes it.

The race condition is
Thread 1: ContractDetailsImpl.decode() which calls ContractDetailsImpl.getExternalStorageDataSource(): this opens the leveldb db if not already opened
Thread 2: ContractDetailsImpl.syncStorage(): This opens the leveldb db (if not already opened), saves contract data to it, then closes it. 
Thread 1: LevelDbDataSource.get(): this tries to use the leveldb db but throws an exception because the db was closed by thread 2.

**Comment by Nashatyrev** [comment]
We need to get back to this issue after resolving the Issue #427 . Most likely the problem will be fixed

**Comment by Nashatyrev** [comment]
Thanks for detailed description! 
Shouldn't be reproducible any more: 
- no open/close db any more ( #427 )
- `DetailsDataStore` is now synchronized
