### ISSUE TITLE
Potential syncing bottleneck

### ISSUE THREAD

**Issue by jlopp** [ethereum/ethereumj#430]
This is just an informational point; not sure if you'll find it helpful. I was profiling EthereumJ 1.3.0 snapshot syncing the main network with none of our app code activated and noticed that a substantial portion of the CPU time is spent in the Transaction.getSender() function. Just an FYI - it might be low hanging fruit for a performance optimization.
![screen shot 2016-06-28 at 6 31 36 pm](https://cloud.githubusercontent.com/assets/288011/16434605/e1028734-3d5e-11e6-844f-03255229547a.png)

**Comment by Nashatyrev** [comment]
Yep, this is CPU hard operation, that's why it is currently executed in parallel via `ExecutorPipeline` (you see it on top the stack)
BTW if you any better EC_RECOVER java implementation would be great!

**Comment by Nashatyrev** [comment]
The major syncing bottleneck is DB access
