### ISSUE TITLE
Wrong behavior when Spring context restarts

### ISSUE THREAD

**Issue by cupuyc** [ethereum/ethereumj#446]
EthereumJ became broken after Spring context did restart. For example when `logback.xml` was modified.

In https://github.com/ether-camp/ethereum-harmony project I used `org.ethereum:ethereumj-core:1.3.0-RC5-RELEASE`. I run server with `./gradlew bootRun`. When I edit `logback.xml` - my beans restart correctly, while EthereumJ fails and stop working.

Here the log with link to spring restart https://gist.github.com/cupuyc/5218a85029cc4f596688691d436b3d6d#file-ethissue123123-log-L1146

@Nashatyrev you told that it should work correctly

**Comment by zilm13** [comment]
Pull request added #491 
@Nashatyrev please, take a look.
