### ISSUE TITLE
EthereumJ bestBlock on .close() not equal to bestBlock on startup

### ISSUE THREAD

**Issue by Melvillian** [ethereum/ethereumj#455]
In my project I have a `shutdown()` function which calls `close()` on the ethereumj object created by `EthereumFactory.createEthereum()`. After it successfully closes I log the ethereumJ bestBlock value so I can compare it to what ethereumJ thinks the bestBlock value is when it starts up again, since I have some startup logic which uses ethereumJ's `bestBlock` value.

In one test run of the `shutdown()` logic, I see that after it closed it reported the block at height `1803` as ethereumJ's bestBlock. However, when I started my project back up and ethereumJ loaded its bestBlock in the `loadBlockchain()` method of `WorldManager`, I see the following log line:

```
07-31 13:06:51.180 [main] INFO  general - *** Loaded up to block [1638] totalDifficulty [42834374438742] with stateRoot [2579565c6abca8e08f3795113219773faf916c0ca781e5d34a242c08752eb2f5]
```

Why when ethereumJ shuts down does it think its block is `1803`, yet when it starts back up it thinks it's a different block (block `1638`)? I've tested this twice and seen it both times.

**Comment by Nashatyrev** [comment]
@Melvillian Try the following workaround: each `onBlock()` call `BlockchainImpl.flush()`. But I'd recommend doing this only after `onSyncDone()` else this will dramatically decrease the speed of long chain sync

**Comment by Melvillian** [comment]
My pull request at https://github.com/ethereum/ethereumj/pull/482 handles issue manually, or the commit at https://github.com/ethereum/ethereumj/commit/11c3e8832a57b30f99f30d232bbd5d0646a0f23e handles it in an automated fashion

**Comment by Nashatyrev** [comment]
@Melvillian thanks for feedback. Closing this then

**Comment by Melvillian** [comment]
Heads up to everyone in the future, I ended up removing this manual call to `flush()` because I saw a large increase in `DBException`'s once I added it, and these disappeared when I removed it. Please be cautious if you decide to use it.

**Comment by Nashatyrev** [comment]
Shouldn't be a issue since next release. We removed separate DBs for storage.
