### ISSUE TITLE
Autorepair corrupted leveldb

### ISSUE THREAD

**Issue by splix** [ethereum/ethereumj#457]
After some experiments I got my LevelDB database corrupted, probably because by stopping the process during flush. When first time it happened I just resynced db from the beginning. 

Then it happened second time, and I decided to a fix in the code that tries to repair database when it got exception from leveldb driver. That worked fine for me and I didn't notice any problem after that. 

I'd like to add it as a PR, but there're few moments to discuss:

1. This probably requires a config option, and it's not clear for me should it be enabled by default or not
2. I don't think there it a way to make any real world tests for this scenario, just because "db corruption" can be anything. So what about tests?
3. Repaired after corrupted db may contain invalid data. That probably means that it requires full db revalidation, from block 0 (or tx 0, depends actually on which db was corrupted). 
4. later can be done in background or foreground, or maybe it should require a special config or command line option. I have no idea. Maybe it isn't required at all

PS That was a quick fix for my situation so obviously I don't have any configs or tests at this moment

**Comment by Nashatyrev** [comment]
Hi @splix,
this is very good suggestion. We are meeting that problem rarely, but it highly affects users when happened. I would do the following:  if DB corruption is detected are repairing it immediately in synchronous manner (i.e. during KeyValueDataSource bean creation) so all other initialization is suspended. Also I would print a large noticeable warning (to logs and to stderr), something like: 'WARNING: DB 'name' corrupted. Trying to recover. The process may take a while. Please also note that there is no guarantee all the data will be recovered correctly!'

Thanks for your contribution!

**Comment by cupuyc** [comment]
Plan of work:
 - find cases when LevelDB could be corrupted;
 - verify LevelDB `batchUpdate` consistency when terminated with `SIGRTERM` & `SIGKILL`;
Note that behavior could be different depending on OS platform.

**Comment by zilm13** [comment]
@cupuyc I guess signals and thing like this are handled in LevelDB library (and should)
We could try something like this:
1) repair DB with .repair() function
2) rollback everything 1000 blocks behind or for pruned DB maximum possible number for which we have all data (192?)
I've tried to research it, but accidentally deleted DB repaired from corruption. Btw, after repair db failed to open with LOCK error, but after some actions, not sure which, this error gone.

**Comment by splix** [comment]
Sorry, I didn't make a PR for this as I didn't think my quick fix was tested enough and it doesn't include any integrity check. 

But I'll put it here, just as a reference, hope it will be useful. _ethereumj-core/src/main/java/org/ethereum/datasource/LevelDbDataSource.java_:
```
-                db = factory.open(dbPath.toFile(), options);
+                try {
+                    db = factory.open(dbPath.toFile(), options);
+                } catch (IOException e) {
+                    logger.error("Can't read database {}. Trying to repair...", name);
+                    factory.repair(dbPath.toFile(), options);
+                    logger.info("Database {} was successfully repaired", name);
+                    db = factory.open(dbPath.toFile(), options);
+                }
```

**Comment by cupuyc** [comment]
@Nashatyrev I wasn't able to produce corrupted DB on linux with big batch write.
I used Ubuntu 15 Desktop in VirtualBox. Full levelDB database size 1.3GB. I terminated process with `SIGKILL` and power off.
