### ISSUE TITLE
contract creation transaction fails via JSON-RPC

### ISSUE THREAD

**Issue by amiracam** [ethereum/ethereumj#459]
Steps taken all via JSON-RPC to testnet 

Assumes a sufficiently funded account 

1. Compile simple solidity contract
2. Send compiled contract in transaction
3. Attempt to get transaction receipt immediately for previous transaction

The following JSON exchanges should illustrate the above process:

```
contract SimpleStorage {
    uint storedData;

    function set(uint x) {
        storedData = x;
    }

    function get() constant returns (uint retVal) {
        return storedData;
    }
}
Compiling Solidity contract:  : 
{
  "id": 7,
  "jsonrpc": "2.0",
  "method": "eth_compileSolidity",
  "params": [
    "contract SimpleStorage {\n    uint storedData;\n\n    function set(uint x) {\n        storedData = x;\n    }\n\n    function get() constant returns (uint retVal) {\n        return storedData;\n    }\n}"
  ]
}
Result is:  : 
{
  "jsonrpc": "2.0",
  "id": 7,
  "result": {
    "code": "0x606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",
    "info": {
      "source": "contract SimpleStorage {\n    uint storedData;\n\n    function set(uint x) {\n        storedData = x;\n    }\n\n    function get() constant returns (uint retVal) {\n        return storedData;\n    }\n}",
      "language": "Solidity",
      "languageVersion": "0",
      "compilerVersion": "0.3.1-33b95459/Release-Windows/msvc/JIT linked to libethereum-",
      "abiDefinition": [
        {
          "anonymous": false,
          "constant": false,
          "name": "set",
          "inputs": [
            {
              "name": "x",
              "type": "uint256"
            }
          ],
          "outputs": [

          ],
          "type": "function"
        },
        {
          "anonymous": false,
          "constant": true,
          "name": "get",
          "inputs": [

          ],
          "outputs": [
            {
              "name": "retVal",
              "type": "uint256"
            }
          ],
          "type": "function"
        }
      ],
      "userDoc": null,
      "developerDoc": null
    }
  }
}
Sending transaction: 
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "params": [
    {
      "from": "0xa1c3724878ab26fb11d2378d78b54a37fbae48a7",
      "data": "0x606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056"
    }
  ]
}
Result is:  : 
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0xaf81cb2cc98b0e5ddf6f3467ddfc2f87a7c31bc6ae740832c6e546c21c083fe2"
}
Requesting transaction receipt: 
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionReceipt",
  "params": [
    "0xaf81cb2cc98b0e5ddf6f3467ddfc2f87a7c31bc6ae740832c6e546c21c083fe2"
  ]
}
Result is:  : 
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": null
}


```

**Comment by Nashatyrev** [comment]
@amiracam as a workaround try adding the following params to RPC request:
```
     "gasLimit": "0x100000",
     "gasPrice": "0x20000000000"
```
When implementing I missed the point that those params are optional.
BTW another bug here: should be `gas` instead of `gasLimit`

**Comment by amiracam** [comment]
no worries and perhaps in real practice I would not have those left out.
I’ll let you know, thanks

-- 
Charles Monteiro


On August 4, 2016 at 8:31:27 PM, Anton Nashatyrev (notifications@github.com)
wrote:

@amiracam <https://github.com/amiracam> as a workaround try adding the
following params to RPC request:

     "gasLimit": "0x100000",
     "gasPrice": "0x20000000000"

When implementing I missed the point that those params are optional.
BTW another bug here: should be gas instead of gasLimit

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/ethereumj/issues/459#issuecomment-237725405>,
or mute the thread

**Comment by Nashatyrev** [comment]
Fixed by https://github.com/ethereum/ethereumj/commit/30102b205142e1f72ab545c3bc3d1459a2aef904
notes: 
- default `gas` as specified in RPC doc is 90000. It is not enough for your tx, so you need to set it explicitly 
- Now you can view pending transactions receipts (i.e. when they are not mined yet)
- I added extension RPC method `ethj_getTransactionReceipt` which additionally includes error (if tx encountered any problem, and function return value)

**Comment by amiracam** [comment]
first of all the project that I had downloaded as per Roman was peer.ether.camp, is this fix been applied to that branch/module ?

the contract I published was barely 10 lines l, so u r saying that the "default" will not work for something as basic ? Not questioning , just that it seems that the default is not appropriate. 
So I would call the eth_getEstimate method then prior to determine the amount that needs to be explicitly set ?

I personally do appreciate the extended transaction receipt method.

Can you pls provide a link to the repo I need to clone, the core Repo did not to my recollection provide for RPC. thanks

**Comment by amiracam** [comment]
FYI, the workaround as provided does not seem to be working, I don't see the transaction count incremented, and yes I did use "gas" instead of "gasLimit"

**Comment by Nashatyrev** [comment]
This has been fixed in ethereumj core develop. If you are using the develop branch just try to relaunch and gradle should download the latest develop core build

**Comment by Nashatyrev** [comment]
Try to call ethj_getTransactionReceipt to make sure you are using the right core version

**Comment by amiracam** [comment]
Specifically , what I had downloaded to run the EthJ RPC as per Roman  was
this:


https://github.com/ether-camp/peer.ether.camp/tree/develop


so I will go ahead and do “gradle run” and then check if the
ethj_getTransactionReceipt is indeed available, thanks

-- 
Charles Monteiro


On August 5, 2016 at 12:58:03 PM, Anton Nashatyrev (notifications@github.com)
wrote:

Try to call ethj_getTransactionReceipt to make sure you are using the right
core version

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/ethereumj/issues/459#issuecomment-237904109>,
or mute the thread

**Comment by amiracam** [comment]
gradlew run , blew away my accounts on that node, so I added an account and
had it funded, then yes, I do get a receipt based on
ethj_getTransactionReceipt :


Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result": {

    "transactionHash":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7",

    "transactionIndex": 0,

    "blockHash": null,

    "blockNumber": 0,

    "cumulativeGasUsed": 92181,

    "gasUsed": 92181,

    "contractAddress": "0x893fccec4e74029386915c02e54d47a125983a59",


    "logs": [


    ],

    "returnData":
"0x60606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "error": ""

  }

}


however, when I go check with my “Manage subscription” page I only see 1
transaction whereas I’m expecting two , First for funding of account, and
second for the contract creation transaction that I just sent.


Below is the full JSON exchanges:


Compiling Solidity contract:  :

{

  "id": 7,

  "jsonrpc": "2.0",

  "method": "eth_compileSolidity",

  "params": [

    "contract SimpleStorage {\n    uint storedData;\n\n    function
set(uint x) {\n        storedData = x;\n    }\n\n    function get()
constant returns (uint retVal) {\n        return storedData;\n    }\n}"

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 7,

  "result": {

    "code":
"0x606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "info": {

      "source": "contract SimpleStorage {\n    uint storedData;\n\n    function
set(uint x) {\n        storedData = x;\n    }\n\n    function get()
constant returns (uint retVal) {\n        return storedData;\n    }\n}",

      "language": "Solidity",

      "languageVersion": "0",

      "compilerVersion": "0.3.1-33b95459/Release-Windows/msvc/JIT linked to
libethereum-",

      "abiDefinition": [

        {

          "anonymous": false,

          "constant": false,

          "name": "set",

          "inputs": [

            {

              "name": "x",

              "type": "uint256"

            }

          ],

          "outputs": [


          ],

          "type": "function"

        },

        {

          "anonymous": false,

          "constant": true,

          "name": "get",

          "inputs": [


          ],

          "outputs": [

            {

              "name": "retVal",

              "type": "uint256"

            }

          ],

          "type": "function"

        }

      ],

      "userDoc": null,

      "developerDoc": null

    }

  }

}

Sending transaction:

{

  "id": 1,

  "jsonrpc": "2.0",

  "method": "eth_sendTransaction",

  "params": [

    {

      "from": "0x8f0af1b94d7be557a940b2c3375d2e2f7151399d",

      "gas": "0x100000",

      "gasPrice": "0x20000000000",

      "data":
"0x606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056"

    }

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7"

}

Requesting transaction receipt:

{

  "id": 1,

  "jsonrpc": "2.0",

  "method": "ethj_getTransactionReceipt",

  "params": [

    "0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7"

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result": {

    "transactionHash":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7",

    "transactionIndex": 0,

    "blockHash": null,

    "blockNumber": 0,

    "cumulativeGasUsed": 92181,

    "gasUsed": 92181,

    "contractAddress": "0x893fccec4e74029386915c02e54d47a125983a59",

    "logs": [


    ],

    "returnData":
"0x60606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "error": ""

  }

}








-- 
Charles Monteiro


On August 5, 2016 at 1:11:12 PM, Charles Monteiro (
charles.monteiro@gmail.com) wrote:

Specifically , what I had downloaded to run the EthJ RPC as per Roman  was
this:


https://github.com/ether-camp/peer.ether.camp/tree/develop


so I will go ahead and do “gradle run” and then check if the
ethj_getTransactionReceipt is indeed available, thanks

-- 
Charles Monteiro


On August 5, 2016 at 12:58:03 PM, Anton Nashatyrev (notifications@github.com)
wrote:

Try to call ethj_getTransactionReceipt to make sure you are using the right
core version

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/ethereumj/issues/459#issuecomment-237904109>,
or mute the thread

**Comment by amiracam** [comment]
Sorry, now I do see the second transaction , I guess there’s a huge latency
that I’m not expecting

-- 
Charles Monteiro


On August 5, 2016 at 1:34:34 PM, Charles Monteiro (
charles.monteiro@gmail.com) wrote:

gradlew run , blew away my accounts on that node, so I added an account and
had it funded, then yes, I do get a receipt based on
ethj_getTransactionReceipt :


Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result": {

    "transactionHash":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7",

    "transactionIndex": 0,

    "blockHash": null,

    "blockNumber": 0,

    "cumulativeGasUsed": 92181,

    "gasUsed": 92181,

    "contractAddress": "0x893fccec4e74029386915c02e54d47a125983a59",


    "logs": [


    ],

    "returnData":
"0x60606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "error": ""

  }

}


however, when I go check with my “Manage subscription” page I only see 1
transaction whereas I’m expecting two , First for funding of account, and
second for the contract creation transaction that I just sent.


Below is the full JSON exchanges:


Compiling Solidity contract:  :

{

  "id": 7,

  "jsonrpc": "2.0",

  "method": "eth_compileSolidity",

  "params": [

    "contract SimpleStorage {\n    uint storedData;\n\n    function
set(uint x) {\n        storedData = x;\n    }\n\n    function get()
constant returns (uint retVal) {\n        return storedData;\n    }\n}"

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 7,

  "result": {

    "code":
"0x606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "info": {

      "source": "contract SimpleStorage {\n    uint storedData;\n\n
function set(uint x) {\n        storedData = x;\n    }\n\n    function
get() constant returns (uint retVal) {\n        return storedData;\n
}\n}",

      "language": "Solidity",

      "languageVersion": "0",

      "compilerVersion": "0.3.1-33b95459/Release-Windows/msvc/JIT linked to
libethereum-",

      "abiDefinition": [

        {

          "anonymous": false,

          "constant": false,

          "name": "set",

          "inputs": [

            {

              "name": "x",

              "type": "uint256"

            }

          ],

          "outputs": [


          ],

          "type": "function"

        },

        {

          "anonymous": false,

          "constant": true,

          "name": "get",

          "inputs": [


          ],

          "outputs": [

            {

              "name": "retVal",

              "type": "uint256"

            }

          ],

          "type": "function"

        }

      ],

      "userDoc": null,

      "developerDoc": null

    }

  }

}

Sending transaction:

{

  "id": 1,

  "jsonrpc": "2.0",

  "method": "eth_sendTransaction",

  "params": [

    {

      "from": "0x8f0af1b94d7be557a940b2c3375d2e2f7151399d",

      "gas": "0x100000",

      "gasPrice": "0x20000000000",

      "data":
"0x606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056"

    }

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7"

}

Requesting transaction receipt:

{

  "id": 1,

  "jsonrpc": "2.0",

  "method": "ethj_getTransactionReceipt",

  "params": [

    "0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7"

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result": {

    "transactionHash":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7",

    "transactionIndex": 0,

    "blockHash": null,

    "blockNumber": 0,

    "cumulativeGasUsed": 92181,

    "gasUsed": 92181,

    "contractAddress": "0x893fccec4e74029386915c02e54d47a125983a59",

    "logs": [


    ],

    "returnData":
"0x60606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "error": ""

  }

}








-- 
Charles Monteiro


On August 5, 2016 at 1:11:12 PM, Charles Monteiro (
charles.monteiro@gmail.com) wrote:

Specifically , what I had downloaded to run the EthJ RPC as per Roman  was
this:


https://github.com/ether-camp/peer.ether.camp/tree/develop


so I will go ahead and do “gradle run” and then check if the
ethj_getTransactionReceipt is indeed available, thanks

-- 
Charles Monteiro


On August 5, 2016 at 12:58:03 PM, Anton Nashatyrev (notifications@github.com)
wrote:

Try to call ethj_getTransactionReceipt to make sure you are using the right
core version

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/ethereumj/issues/459#issuecomment-237904109>,
or mute the thread

**Comment by amiracam** [comment]
btw, the account is 8f0af1b94d7be557a940b2c3375d2e2f7151399d , I have added
another transaction and it has been successfully recorded, I guess I was a
bit naive about how quickly transactions got recorded



-- 
Charles Monteiro


On August 5, 2016 at 1:36:13 PM, Charles Monteiro (
charles.monteiro@gmail.com) wrote:

Sorry, now I do see the second transaction , I guess there’s a huge latency
that I’m not expecting

-- 
Charles Monteiro


On August 5, 2016 at 1:34:34 PM, Charles Monteiro (
charles.monteiro@gmail.com) wrote:

gradlew run , blew away my accounts on that node, so I added an account and
had it funded, then yes, I do get a receipt based on
ethj_getTransactionReceipt :


Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result": {

    "transactionHash":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7",

    "transactionIndex": 0,

    "blockHash": null,

    "blockNumber": 0,

    "cumulativeGasUsed": 92181,

    "gasUsed": 92181,

    "contractAddress": "0x893fccec4e74029386915c02e54d47a125983a59",


    "logs": [


    ],

    "returnData":
"0x60606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "error": ""

  }

}


however, when I go check with my “Manage subscription” page I only see 1
transaction whereas I’m expecting two , First for funding of account, and
second for the contract creation transaction that I just sent.


Below is the full JSON exchanges:


Compiling Solidity contract:  :

{

  "id": 7,

  "jsonrpc": "2.0",

  "method": "eth_compileSolidity",

  "params": [

    "contract SimpleStorage {\n    uint storedData;\n\n    function
set(uint x) {\n        storedData = x;\n    }\n\n    function get()
constant returns (uint retVal) {\n        return storedData;\n    }\n}"

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 7,

  "result": {

    "code":
"0x606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "info": {

      "source": "contract SimpleStorage {\n    uint storedData;\n\n
function set(uint x) {\n        storedData = x;\n    }\n\n    function
get() constant returns (uint retVal) {\n        return storedData;\n
}\n}",

      "language": "Solidity",

      "languageVersion": "0",

      "compilerVersion": "0.3.1-33b95459/Release-Windows/msvc/JIT linked to
libethereum-",

      "abiDefinition": [

        {

          "anonymous": false,

          "constant": false,

          "name": "set",

          "inputs": [

            {

              "name": "x",

              "type": "uint256"

            }

          ],

          "outputs": [


          ],

          "type": "function"

        },

        {

          "anonymous": false,

          "constant": true,

          "name": "get",

          "inputs": [


          ],

          "outputs": [

            {

              "name": "retVal",

              "type": "uint256"

            }

          ],

          "type": "function"

        }

      ],

      "userDoc": null,

      "developerDoc": null

    }

  }

}

Sending transaction:

{

  "id": 1,

  "jsonrpc": "2.0",

  "method": "eth_sendTransaction",

  "params": [

    {

      "from": "0x8f0af1b94d7be557a940b2c3375d2e2f7151399d",

      "gas": "0x100000",

      "gasPrice": "0x20000000000",

      "data":
"0x606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056"

    }

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7"

}

Requesting transaction receipt:

{

  "id": 1,

  "jsonrpc": "2.0",

  "method": "ethj_getTransactionReceipt",

  "params": [

    "0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7"

  ]

}

Result is:  :

{

  "jsonrpc": "2.0",

  "id": 1,

  "result": {

    "transactionHash":
"0x453db1c1ae0b2acd82b5756d9ef889c22143899c6908cc3a0ef95ae749518ff7",

    "transactionIndex": 0,

    "blockHash": null,

    "blockNumber": 0,

    "cumulativeGasUsed": 92181,

    "gasUsed": 92181,

    "contractAddress": "0x893fccec4e74029386915c02e54d47a125983a59",

    "logs": [


    ],

    "returnData":
"0x60606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056",

    "error": ""

  }

}








-- 
Charles Monteiro


On August 5, 2016 at 1:11:12 PM, Charles Monteiro (
charles.monteiro@gmail.com) wrote:

Specifically , what I had downloaded to run the EthJ RPC as per Roman  was
this:


https://github.com/ether-camp/peer.ether.camp/tree/develop


so I will go ahead and do “gradle run” and then check if the
ethj_getTransactionReceipt is indeed available, thanks

-- 
Charles Monteiro


On August 5, 2016 at 12:58:03 PM, Anton Nashatyrev (notifications@github.com)
wrote:

Try to call ethj_getTransactionReceipt to make sure you are using the right
core version

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/ethereumj/issues/459#issuecomment-237904109>,
or mute the thread
