### ISSUE TITLE
Error in BLOCKHASH opcode can lead to network partition attack

### ISSUE THREAD

**Issue by SergioDemianLerner** [ethereum/ethereumj#460]
Ethereumj EVM implementation implements the BLOCKHASH opcode in a way that is not in sync with the yellow paper. The current implementation reads the 256-bit block index number from the stack, truncates it to the 4 least-significant bytes, and then looks-up the block at that index.
This means that a smart program that tries to obtain the hash of the block 0x0100000001 gets the hash of the block 0x01. It should get zero, but it does not.

This is the flawed line of code in VM.java: 
case BLOCKHASH: {
  int blockIndex = program.stackPop().intValue()

A range check shoud be performed before casting, and take special care of negative values also.

Best wishes to the Ethereumj team, from SDL.
Courtesy of RSK Labs

**Comment by Nashatyrev** [comment]
Hello!
Nice catch! Thanks for reporting this! 
I've discovered a family of such bugs in VM code
To fix this I've changed conversion method to analogs which just return MAX_VALUE (for int and long) if integral type overflow takes place. MAX_VALUE is still large enough to not fall into reasonable boundaries and thus should behave as expected.
