### ISSUE TITLE
transaction not signed by user private key while calling constant function

### ISSUE THREAD

**Issue by prodiptag** [ethereum/ethereumj#462]
Why in org.ethereum.facade.EthereumImpl.callConstantFunction(String, Function, Object...)
transactions are signed using below:
tx.sign(new byte[32]);
Lets say you set some value against msg.sender by calling normal function and sign the transaction with your private key. so at contract end, contract store that value against msg.sender in some hashtable (solidity mapping).
Now if you fire callConstantFunction to get the same value will not return you the same result as msg.sender is not same between two calls.
Is there any specific reason?

**Comment by Nashatyrev** [comment]
Closed by accident

**Comment by prodiptag** [comment]
@Nashatyrev, Thanks for including this feature. Could you please tell me in which release version will you include this feature?

**Comment by Nashatyrev** [comment]
This will be in 1.3.0, which I believe will be published in 2-3 weeks

**Comment by epsstan** [comment]
Looks like this bug is also in the latest StandaloneBlockchain.java:callConstFunction

        public Object[] callConstFunction(Block callBlock, String functionName, Object... args) {

            CallTransaction.Function func = contract.getByName(functionName);
            if (func == null) throw new RuntimeException("No function with name '" + functionName + "'");
            Transaction tx = CallTransaction.createCallTransaction(0, 0, 100000000000000L,
                    Hex.toHexString(getAddress()), 0, func, convertArgs(args));

            tx.sign(new byte[32]);   <---------------

I can submit a PR if the fix is the same as https://github.com/ethereum/ethereumj/commit/6183769dee268b9747dd3951b88f1144d53a1f04

**Comment by redskate** [comment]
Is this solved?
It would be nice to submit a ethereum.callConstantFunction WITH a specific sender address ...

**Comment by mkalinin** [comment]
@redskate it must be!
