### ISSUE TITLE
Ethereumj miner and DB auto reset

### ISSUE THREAD

**Issue by ranjan008** [ethereum/ethereumj#465]
I am creating an address through jsonrpc but again when i restart the project the addresses are getting lost think the db is resetting even after i have set the reset attribute under database as false and also not able to start the miner is miner implemented yet because my best block is always coming as 0.

**Comment by Nashatyrev** [comment]
Current JSON-RPC implementation doesn't support keystore. 
The Harmony project is on the way which should be full-featured peer: https://github.com/ether-camp/ethereum-harmony/
Stay tuned!
