### ISSUE TITLE
send transaction  with ethereumj

### ISSUE THREAD

**Issue by chainrui** [ethereum/ethereumj#470]
Hi guys,

I would like to send ether from my ethereum address to another one with ethereumj, but could not find any instructions, e.g. like for the go-ethereum - "eth.sendTransaction(from, to, value)".

Thanks :)

**Comment by Nashatyrev** [comment]
You may check that sample: https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/samples/PendingStateSample.java#L82

**Comment by chainrui** [comment]
yes, it works in the testnet :), Thanks. :)
Then how to configure it so that it is capable to send transactions could be included in the main net.
Thanks
