### ISSUE TITLE
Convert ECDSASignature to hex

### ISSUE THREAD

**Issue by csdodd** [ethereum/ethereumj#483]
When signing an `ECKey` with a 32 byte keccak hash of data an `ECDSASignature` is returned. I was attempting to convert this `ECDSASignature` to the hex string that is returned when doing `web3.eth.sign` with geth.

I ended up writing code to do this -- did I overlook something in ethereumj, does the ability to do this exist already? If not I am happy to submit a pull request with my code.

**Comment by Nashatyrev** [comment]
Hi Colin, 
can you please post your code here? 
I think we currently have some kind of stub for JSON RPC `eth_sign` implementation: https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/jsonrpc/JsonRpcImpl.java#L495
Or please make a PR, we would very appreciate!

**Comment by cupuyc** [comment]
For note `ECKey` operates with base64 encoding to convert bytes to string. Then it is possible to use next snippet to convert to hex:
        ```
        ECKey.ECDSASignature signature = account.getEcKey().sign(hashBytes);
        byte[] signatureBytes = signatureToBytes(signature);
        Hex.toHexString(signatureBytes);
```
NOTE: That implementation may not match other ethereum nodes result.

@csdodd Could you please paste your code and let me know how do you use hex string or test it.

**Comment by csdodd** [comment]
I have created a pull request here: https://github.com/ethereum/ethereumj/pull/512
I am going to close this issue and we can instead continue the conversation there. It may be the case that my code is redundant and there exists code already to achieve what I am attempting.
