### ISSUE TITLE
Full Blockchain sync takes over 24 hours to complete

### ISSUE THREAD

**Issue by vikulin** [ethereum/ethereumj#487]
Full Blockchain sync takes over 24 hours to complete.

I ran BasicSample and my Blockchain sync very slow with good the Internet connection (>50MBps)

import org.ethereum.samples.BasicSample;

public class App
{

public static void main( String[] args ) throws Exception
{

    BasicSample.main(null);

}

}

The log:
`07:55:48.299 INFO [sample] Blockchain sync in progress. Last imported block: #1460328 (1f775e <~ 6171c7) Txs:10, Unc: 0

07:55:58.299 INFO [sample] Blockchain sync in progress. Last imported block: #1460429 (b8ea6d <~ 2c15b5) Txs:8, Unc: 1

07:56:08.299 INFO [sample] Blockchain sync in progress. Last imported block: #1460498 (85b2c9 <~ e82b84) Txs:0, Unc: 0

07:56:18.299 INFO [sample] Blockchain sync in progress. Last imported block: #1460605 (9c9fd4 <~ ae2b8c) Txs:3, Unc: 0

07:56:28.299 INFO [sample] Blockchain sync in progress. Last imported block: #1460711 (1c9f01 <~ 374bec) Txs:8, Unc: 0

07:56:38.299 INFO [sample] Blockchain sync in progress. Last imported block: #1460730 (4ce6fe <~ 01929b) Txs:0, Unc: 0

07:56:48.299 INFO [sample] Blockchain sync in progress. Last imported block: #1460784 (f550cf <~ bed215) Txs:0, Unc: 0

07:56:58.299 INFO [sample] Blockchain sync in progress. Last imported block: #1460837 (9afd81 <~ 7dd7c7) Txs:4, Unc: 0

07:57:08.300 INFO [sample] Blockchain sync in progress. Last imported block: #1460886 (c5ef79 <~ ff4b30) Txs:4, Unc: 0

07:57:18.300 INFO [sample] Blockchain sync in progress. Last imported block: #1460932 (b7edbe <~ 42be17) Txs:4, Unc: 0

07:57:28.300 INFO [sample] Blockchain sync in progress. Last imported block: #1460975 (82400f <~ 3c9f94) Txs:12, Unc: 0

07:57:38.300 INFO [sample] Blockchain sync in progress. Last imported block: #1461001 (103b82 <~ 1f4221) Txs:1, Unc: 0

07:57:48.300 INFO [sample] Blockchain sync in progress. Last imported block: #1461018 (0e7e77 <~ 3c0d6a) Txs:11, Unc: 0

07:57:58.300 INFO [sample] Blockchain sync in progress. Last imported block: #1461058 (780bae <~ cdac04) Txs:9, Unc: 0

07:58:08.300 INFO [sample] Blockchain sync in progress. Last imported block: #1461095 (c46e10 <~ 8a7606) Txs:2, Unc: 0

07:58:18.300 INFO [sample] Blockchain sync in progress. Last imported block: #1461116 (5aae14 <~ 534bbc) Txs:3, Unc: 0`

Data size is more 36GB:

`vadym@vadym-work:~/work/workspace/ethereum$ du -sh database/
36G database/

vadym@vadym-work:~/work/workspace/ethereum$`

**Comment by vikulin** [comment]
I could not reopen #485 so I filled up a new issue here.

**Comment by vikulin** [comment]
I ran sync from scratch and the issue reproduced. Syncing become very slow.

**Comment by vikulin** [comment]
@Nashatyrev , please re-open the original issue #485 again.

**Comment by Nashatyrev** [comment]
Reopened
