### ISSUE TITLE
Database versioning

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#488]
We need to persist the DB version, so after core upgrade we can either reset older incompatible db or make a warning and let the user reset DB manually

**Comment by Nashatyrev** [comment]
What I think we can do here: 
- add config option (smthng like `database.autoResetOldVersion`) which is `false` by default 
- when incompatible db version detected:
  - if `autoResetOldVersion` is false just log a big warning and shutdown 
  - if `autoResetOldVersion` is true then make DB reset

I don't think we should add any command line interactivity to the core library

**Comment by cupuyc** [comment]
Info for thinking and later discussing:

1. What should be behavior if user run old core vs newer database? I suppose reset logic should also take place and property could be renamed to `autoResetIncompatibleVersion`.

2. I store database version under `${databaseDir}/version.properties` as numbers:
`databaseVersion = 1`
Same line is put to `src/main/resources/version.properties`

3. Supposing we enable this logic immediately. After that all users will have to re-download blockchain database. As alternative, I added logic for only storing version number without reset.

**Comment by Nashatyrev** [comment]
1. Ok
2. Ok
3. Let's assume `databaseVersion = 1` and the absence of `${databaseDir}/version.properties` is the same. So reset logic will take place only when we upgrade `databaseVersion` to `2` What do you think?
