### ISSUE TITLE
Need consistent Spring app context initialization process 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#492]
We are having a number of interdependent Spring components which are mostly injected to each other by autowiring and initialized via @PostConstruct methods asynchronously with a number of hacky hooks to maintain desired initialization order. 
This way we are periodically hit (after some harmless changes) into situations when autowired fields are not initialized or @PostConstruct methods are executed in wrong order 
One of options is to have a single `@PostConstruct WorldManager.init()` where all `init()` methods are invoked synchronously in the desired order. 
But the most preferred way would be using the right Spring DI patterns

**Comment by zilm13** [comment]
We could make @Configuration class for it and expose them as Beans
http://docs.spring.io/autorepo/docs/spring/4.1.3.RELEASE/javadoc-api/org/springframework/context/annotation/Bean.html
It will give all needed control like dependsOn on and will not be messed among many classes.

**Comment by Nashatyrev** [comment]
Unfortunately (if I'm not mistaking) the `dependsOn` doesn't affect `@PostConstruct` methods execution order.

**Comment by Nashatyrev** [comment]
I believe Spring automatically builds dependency graph based on injected fields, so `dependsOn` doesn't help much

**Comment by zilm13** [comment]
Yeah, but sometimes it has difficulties when building this graph, like in cases when build of the same version runs correctly on most systems and fails to be constructed on others.

I mean to use it in conjunction with @Autowired constructors and throw out postConstruct methods. The only thing I don't like in such approach is the number of constructor parameters and lines like `this.bean = bean;`; But it will be safer and will give us the ability to eliminate cases when Spring fails to correctly construct bean graph.

**Comment by zilm13** [comment]
Please, take a look PR #520
