### ISSUE TITLE
Slow Blockchain Sync process v 1.3.0-RELEASE

### ISSUE THREAD

**Issue by vikulin** [ethereum/ethereumj#494]
http://m.uploadedit.com/ba3s/147333578174.txt

14:40:52.073 INFO [sample]  Blockchain sync in progress. Last imported block: #2034554 (b1ea17 <~ 9bc271) Txs:0, Unc: 0 (Total: txs: 278, gas: 33783k)
14:41:02.073 INFO [sample]  Blockchain sync in progress. Last imported block: #2034589 (f39f17 <~ cdee36) Txs:5, Unc: 0 (Total: txs: 143, gas: 20760k)
14:41:12.073 INFO [sample]  Blockchain sync in progress. Last imported block: #2034599 (d02cd7 <~ f95ff9) Txs:1, Unc: 0 (Total: txs: 69, gas: 10091k)
14:41:22.074 INFO [sample]  Blockchain sync in progress. Last imported block: #2034693 (3eccac <~ f9ca37) Txs:5, Unc: 0 (Total: txs: 408, gas: 90204k)
14:41:32.074 INFO [sample]  Blockchain sync in progress. Last imported block: #2034739 (f1f97e <~ 71ef4d) Txs:4, Unc: 0 (Total: txs: 466, gas: 44408k)
14:41:42.074 INFO [sample]  Blockchain sync in progress. Last imported block: #2034823 (11b863 <~ e6538f) Txs:20, Unc: 0 (Total: txs: 330, gas: 70444k)
14:41:52.075 INFO [sample]  Blockchain sync in progress. Last imported block: #2034854 (971acc <~ a54170) Txs:1, Unc: 0 (Total: txs: 128, gas: 24591k)
14:42:02.075 INFO [sample]  Blockchain sync in progress. Last imported block: #2034879 (6dc78a <~ 4f9b4c) Txs:14, Unc: 0 (Total: txs: 97, gas: 13543k)
14:42:12.076 INFO [sample]  Blockchain sync in progress. Last imported block: #2034950 (3c4826 <~ c5db4e) Txs:0, Unc: 0 (Total: txs: 346, gas: 59749k)
14:42:22.076 INFO [sample]  Blockchain sync in progress. Last imported block: #2034999 (f88a80 <~ 9edb15) Txs:1, Unc: 1 (Total: txs: 238, gas: 49262k)
14:42:32.106 INFO [sample]  Blockchain sync in progress. Last imported block: #2035032 (8e8eb3 <~ 9d9c38) Txs:1, Unc: 0 (Total: txs: 107, gas: 30300k)

**Comment by Nashatyrev** [comment]
Yep, indeed looks really slow.
What's you platform? (Arch, OS, RAM, disk)
Sync performance is pretty sensitive to DB operations so we were observing similar behavior on either machines with slow disk or machines with tight RAM restrictions (DB files are poorly cached) 
Also try to run the sample with -Xmx2G (`./gradlew -PjvmArgs="-Xmx2G"`), there is chance that you have speed degradation due to continuous JVM FullGC efforts (you may check if the java process periodically consumes 100% CPU on all cores)

**Comment by Nashatyrev** [comment]
And please double-check you were syncing from the empty DB on `1.3.0`

**Comment by vikulin** [comment]
Yes, I synced from empty DB:

Linux Ubuntu 16.0.4 x86_64, 8GB RAM, 1TB disk
Java 1.8
Trying with  Xmx settings

**Comment by Melvillian** [comment]
@jlopp and I are also seeing slow block loading times, which get slower as the indexer continues to run. We are now trying with the -Xmx=2G option.

System Info:
Linux Ubuntu 14.04 x86_64
Java 1.8
120GB disk
8G RAM

**Comment by romanman** [comment]
@Melvillian can we close it ? 

The big RAM really helps , 
but today we have all the DDoS 
attacks which slow down all of the peers.
