### ISSUE TITLE
Duplicated threads in SendTransaction.java

### ISSUE THREAD

**Issue by vikulin** [ethereum/ethereumj#499]
09:02:30.757 INFO [general]  Starting EthereumJ...
09:02:34.556 INFO [general]  Config ( yes ): default properties from resource 'ethereumj.conf'
09:02:34.556 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.res resource 'null'
09:02:34.556 INFO [general]  Config ( no  ): user properties from resource 'user.conf'
09:02:34.557 INFO [general]  Config ( no  ): user properties from file '/home/vadym/work/workspace/ethereum/config/ethereumj.conf'
09:02:34.558 INFO [general]  Config ( no  ): test properties from resource 'test-ethereumj.conf'
09:02:34.558 INFO [general]  Config ( no  ): test properties from resource 'test-user.conf'
09:02:34.558 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.file file 'null'
09:02:34.558 INFO [general]  Config ( no  ): config passed via constructor
09:02:39.214 INFO [general]  Running frontier.json,  core version: 1.3.0-RELEASE
09:02:39.217 INFO [general]  git.hash: [39ad7af]
09:02:39.217 INFO [general]  build.time: [GMT]-[06/Sep/2016]-[15:09]
09:02:39.218 INFO [general]  capability eth version: [62]
09:02:39.218 INFO [general]  capability shh version: [3]
09:02:39.218 INFO [general]  capability bzz version: [0]

09:02:39.462 INFO [general]  leveldb key-value data source created.
09:02:40.515 INFO [general]  leveldb key-value data source created.
09:02:41.081 INFO [general]  leveldb key-value data source created.
09:02:41.081 INFO [general]  leveldb key-value data source created.
09:02:44.815 INFO [general]  leveldb key-value data source created.
09:02:51.943 INFO [general]  External IP wasn't set, using checkip.amazonaws.com to identify it...
09:03:03.164 INFO [general]  External address identified: 213.231.4.18
09:03:03.402 INFO [sync]  Sync Manager: ON
09:03:03.410 INFO [general]  Bind address wasn't set, Punching to identify it...
09:03:03.472 INFO [general]  UDP local bound to: 172.16.0.107
09:03:03.473 INFO [discover]  Discovery UDPListener started
09:03:03.758 INFO [general]  *** Loaded up to block [2225685] totalDifficulty [58198312156659996323] with stateRoot [a7ed660ea2ca862dd93b73cf18ba521e13584d0da787316b376768952de96dde]
09:03:03.758 INFO [sync]  Initializing SyncManager.
09:03:03.898 INFO [general]  EthereumJ node started: enode://07b226efea4ab2a37ef863baa0dd703804c0aa1034086ed78d992a9880974dc3c9c90d8d032e16fe7b78bb888d2ec4f21d0e3affd39aedf026aaeed2ad662db2@213.231.4.18:30303
09:03:03.900 INFO [sample]  Sample component created. Listening for ethereum events...
09:03:03.906 INFO [sample]  Sample worker thread started.
09:03:03.918 INFO [sample]  Waiting for nodes discovery...
09:03:04.406 INFO [sample]  Sample component created. Listening for ethereum events...
09:03:04.406 INFO [sample]  Sample worker thread started.
09:03:04.408 INFO [sample]  Waiting for nodes discovery...
09:03:04.411 INFO [sample]  Sample component created. Listening for ethereum events...
09:03:04.415 INFO [sample]  Sample worker thread started.
09:03:04.416 INFO [sample]  Waiting for nodes discovery...
09:03:10.830 INFO [sample]  [v] Discovery works, new nodes started being discovered.
09:03:10.830 INFO [sample]  [v] Discovery works, new nodes started being discovered.
09:03:10.830 INFO [sample]  [v] Discovery works, new nodes started being discovered.
09:03:10.831 INFO [sample]  Waiting for available Eth capable nodes...
09:03:10.832 INFO [sample]  Waiting for available Eth capable nodes...
09:03:10.832 INFO [sample]  Waiting for available Eth capable nodes...
09:03:24.730 INFO [sample]  [v] Available Eth nodes found.
09:03:24.730 INFO [sample]  Searching for peers to sync with...
09:03:24.730 INFO [sample]  [v] Available Eth nodes found.
09:03:24.730 INFO [sample]  Searching for peers to sync with...
09:03:24.730 INFO [sample]  [v] Available Eth nodes found.
09:03:24.730 INFO [sample]  Searching for peers to sync with...
09:03:38.253 INFO [sample]  [v] At least one sync peer found.
09:03:38.253 INFO [sample]  [v] At least one sync peer found.
09:03:38.253 INFO [sample]  [v] At least one sync peer found.
09:03:38.254 INFO [sample]  Current BEST block: #2225685 (48f1bb <~ a5bd7e) Txs:9, Unc: 1
09:03:38.254 INFO [sample]  Waiting for blocks start importing (may take a while)...
09:03:38.254 INFO [sample]  Current BEST block: #2225685 (48f1bb <~ a5bd7e) Txs:9, Unc: 1
09:03:38.254 INFO [sample]  Waiting for blocks start importing (may take a while)...
09:03:38.254 INFO [sample]  Current BEST block: #2225685 (48f1bb <~ a5bd7e) Txs:9, Unc: 1
09:03:38.254 INFO [sample]  Waiting for blocks start importing (may take a while)...
09:04:03.309 INFO [sample]  [v] Blocks import started.
09:04:03.309 INFO [sample]  Waiting for the whole blockchain sync (will take up to several hours for the whole chain)...
09:04:03.309 INFO [sample]  [v] Blocks import started.
09:04:03.309 INFO [sample]  Waiting for the whole blockchain sync (will take up to several hours for the whole chain)...
09:04:03.309 INFO [sample]  [v] Blocks import started.
09:04:03.309 INFO [sample]  Waiting for the whole blockchain sync (will take up to several hours for the whole chain)...
09:04:13.309 INFO [sample]  Blockchain sync in progress. Last imported block: #2225689 (35f301 <~ d89049) Txs:1, Unc: 0 (Total: txs: 22, gas: 615k)
09:04:13.309 INFO [sample]  Blockchain sync in progress. Last imported block: #2225689 (35f301 <~ d89049) Txs:1, Unc: 0 (Total: txs: 22, gas: 615k)
09:04:13.309 INFO [sample]  Blockchain sync in progress. Last imported block: #2225689 (35f301 <~ d89049) Txs:1, Unc: 0 (Total: txs: 22, gas: 615k)
09:04:23.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225690 (87e6d4 <~ 35f301) Txs:12, Unc: 0 (Total: txs: 12, gas: 368k)
09:04:23.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225690 (87e6d4 <~ 35f301) Txs:12, Unc: 0 (Total: txs: 12, gas: 368k)
09:04:23.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225690 (87e6d4 <~ 35f301) Txs:12, Unc: 0 (Total: txs: 12, gas: 368k)
09:04:33.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225690 (87e6d4 <~ 35f301) Txs:12, Unc: 0 (Total: txs: 0, gas: 0k)
09:04:33.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225690 (87e6d4 <~ 35f301) Txs:12, Unc: 0 (Total: txs: 0, gas: 0k)
09:04:33.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225690 (87e6d4 <~ 35f301) Txs:12, Unc: 0 (Total: txs: 0, gas: 0k)
09:04:43.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225691 (ac8dfc <~ 87e6d4) Txs:0, Unc: 0 (Total: txs: 0, gas: 0k)
09:04:43.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225691 (ac8dfc <~ 87e6d4) Txs:0, Unc: 0 (Total: txs: 0, gas: 0k)
09:04:43.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225691 (ac8dfc <~ 87e6d4) Txs:0, Unc: 0 (Total: txs: 0, gas: 0k)
09:04:53.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225699 (2e4759 <~ 0d058a) Txs:10, Unc: 0 (Total: txs: 37, gas: 1256k)
09:04:53.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225699 (2e4759 <~ 0d058a) Txs:10, Unc: 0 (Total: txs: 37, gas: 1256k)
09:04:53.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225699 (2e4759 <~ 0d058a) Txs:10, Unc: 0 (Total: txs: 37, gas: 1256k)
09:05:03.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225715 (f3980d <~ 2d5acd) Txs:1, Unc: 0 (Total: txs: 57, gas: 2164k)
09:05:03.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225715 (f3980d <~ 2d5acd) Txs:1, Unc: 0 (Total: txs: 57, gas: 2164k)
09:05:03.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225715 (f3980d <~ 2d5acd) Txs:1, Unc: 0 (Total: txs: 57, gas: 2164k)
09:05:13.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225723 (b13a51 <~ f90d52) Txs:16, Unc: 0 (Total: txs: 46, gas: 2037k)
09:05:13.310 INFO [sample]  Blockchain sync in progress. Last imported block: #2225723 (b13a51 <~ f90d52) Txs:16, Unc: 0 (Total: txs: 46, gas: 2037k)
09:05:13.311 INFO [sample]  Blockchain sync in progress. Last imported block: #2225723 (b13a51 <~ f90d52) Txs:16, Unc: 0 (Total: txs: 46, gas: 2037k)
09:05:23.311 INFO [sample]  Blockchain sync in progress. Last imported block: #2225744 (6d1ff5 <~ ba16f3) Txs:0, Unc: 1 (Total: txs: 69, gas: 1838k)
09:05:23.311 INFO [sample]  Blockchain sync in progress. Last imported block: #2225744 (6d1ff5 <~ ba16f3) Txs:0, Unc: 1 (Total: txs: 69, gas: 1838k)
09:05:23.311 INFO [sample]  Blockchain sync in progress. Last imported block: #2225744 (6d1ff5 <~ ba16f3) Txs:0, Unc: 1 (Total: txs: 69, gas: 1838k)

**Comment by vikulin** [comment]
I run https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/samples/SendTransaction.java

**Comment by a7ex12** [comment]
Fix with #502
