### ISSUE TITLE
Broadcast pending txs from other peers 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#506]
We are currently broadcasting only own submitted transactions. 
There are rules for tx broadcasting:
- broadcast only validated txs (i.e. those included to `PendingState`)
- don't resend back txs to peers they were received from

**Comment by zilm13** [comment]
Please, take a look at #526

**Comment by Nashatyrev** [comment]
One more thing: once a new peer is connected we should transfer all the pending txs to it. I believe this how the `geth` peer functioning. 
This case is visible when in `BlockTxForwardTest` one peer loose connection and then reconnects. After reconnect all pending txs are lost

**Comment by zilm13** [comment]
@Nashatyrev 
Please, take a look at #551
