### ISSUE TITLE
Make Genesis.json file values reading compatible with other clients 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#508]
EthJ and Geth treats some values in the Genesis.json file differently. 
Need to check values like `0x`, `0x0`, `0x00` in different fields 
Geth also accepts values with odd number of hex letters adding one leading `0` if required 
Also need to check if the fields with amount of leading zeroes are treated equally (like `0x0000000000000042`)

**Comment by zilm13** [comment]
Please, take a look #515

**Comment by Nashatyrev** [comment]
@zilm13 Can you please check the genesis mentioned here as well: https://gitter.im/ethereum/ethereumj?at=56e0d739618c335373ea6ed1
The genesis block hash differs between Geth & EthereumJ

**Comment by zilm13** [comment]
@Nashatyrev Pushed update

**Comment by Nashatyrev** [comment]
@zilm13 Can you please also check the nonce `0x00` results in the same hash for both EthJ and Geth?

**Comment by zilm13** [comment]
Unchanged in both.
Add case in BlockTest?

**Comment by Nashatyrev** [comment]
Cool! Yep, another one test is always welcomed :)
