### ISSUE TITLE
Skip parameter of GET_BLOCK_HEADERS is handling incorrectly

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#534]
In Geth and Parity `Skip` param is treating as a number between consecutive headers, so when you ask for block headers with params:
```
blockNumber=1000
amount=5
skip=15
reverse=false
```
you'll get [1000. 1016, 1032, 1048, 1064] blocks. 
Instead of this we will send [1015, 1016, 1017, 1018, 1019].
Also verification of answer for such request should be checked to not fail after.

**Comment by Nashatyrev** [comment]
Are not we checking the response? Normally we should validate, see the wrong response and drop the peer

**Comment by zilm13** [comment]
I mean we should verify answer with skip parameter involved like it will be handled after fix.

**Comment by zilm13** [comment]
Take a look at #537

**Comment by Nashatyrev** [comment]
Need this fix in the nearest release sine we may lack peers due to this error as almost all Geth peers were updated to the latest release
