### ISSUE TITLE
ethereumj log prints partial lines

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/ethereumj#553]
```bash
gs@box:~/misc$ tail -n 2 /home/gs/ethereumj/screenlog.0 
20:16:20.529 INFO [sync]  Success importing BEST: block.number: 2334983, block.hash: b86741, tx.size: 21 
20:16:20.532 INFO [sync]  Success importing BEST: block.number:gs@box:~/misc$ 
```

If ethereumj would log line-by-line it would be much easier to use standard unix tools on it's logs.

**Comment by romanman** [comment]
@Nashatyrev we break lines sometimes strange to see it in the BEST import output.

**Comment by cupuyc** [comment]
@Gustav-Simonsson Line you mentioned, is printed as single line:
```
logger.info("Success importing BEST: block.number: {}, block.hash: {}, tx.size: {} ",
                            wrapper.getNumber(), wrapper.getBlock().getShortHash(),
                            wrapper.getBlock().getTransactionsList().size());
```
Then it must be flushed as single line as well. I suppose there are could be rare cases with partitial line, when process forced to quite. 

I noticed you use screenlog log. Maybe it causes issue? You could also use `tail -n 2 logs/ethereum.log`

Are you just monitoring logs or building logic on top of logs output?
