### ISSUE TITLE
How do I exit program after SendTransaction

### ISSUE THREAD

**Issue by cheershendtco** [ethereum/ethereumj#556]
Hi
I use this sample to sand a transaction
https://github.com/ethereum/ethereumj/blob/db0654881c7ebb5411abf5702d14d63f6fe2fcbb/ethereumj-core/src/main/java/org/ethereum/samples/SendTransaction.java

after I see the log `Transaction included!`
it means that I sync finish to the block number that include my Transaction.
how can I exit program at that time.

I want to have a function or an object .
I can make a request to send a transaction and finish.
and I can call it when ever I have a request.
Thanks

**Comment by cupuyc** [comment]
It looks like more Java related question. You can exit program with `System.exit(0);`

If you need to define some send transaction method, you could submit transaction without waiting for processing result:
`Transaction tx = new Transaction(...)`
`ethereum.submitTransaction(tx);`
Note: sending transactions is only possible after sync is fully finished.

**Comment by Nashatyrev** [comment]
You may also want to call `Ethereum.close()` before exit to gracefully shutdown. 
Please ask technical EthereumJ questions on our public slack channel: https://gitter.im/ethereum/ethereumj
