### ISSUE TITLE
Unexpected fields in ABI

### ISSUE THREAD

**Issue by kivanov82** [ethereum/ethereumj#572]
After generation of ABI for my contract (pretty much standard 'token' contract) using browser-solidity I see that some fields are not expected by EthJ, as:
- "payable":true/false for CallTransaction.Function
- "type":"fallback" for CallTransaction.Function.FunctionType

**Comment by martintreurnicht** [comment]
This is related to https://github.com/ethereum/ethereumj/pull/579

**Comment by Nashatyrev** [comment]
I believe this had been resolved with #579
