### ISSUE TITLE
How to use the CPU miner ?

### ISSUE THREAD

**Issue by nsiatras** [ethereum/ethereumj#581]
Hello,

I have built a stratum client using the NiceHash stratum protocol implementation and I wonder how can I use the ethereumJ to do the **CPU** mining.

So far I have build a new maven project that includes the ethereumJ inside the dependencies but I don't really know how to make it mine...

I saw that the **org.ethereum.mine.Miner** class has a boolean mine method which takes 2 parameters
a) **Block** newBlock 
b) **byte[]** difficulty

I suppose that from the stratum data I should build a block and then pass it to the miner. Can someone that knows how this miner works guide me ?

Thank you in advanced

PS. From the stratum protocol I get the following:
1) **JobID** (small hex)
2) **Seed Hash** (64bit Hex)
3) **Header Hash** (64bit hex)
4) **Target** (I build this from Difficulty, 64bits hex)
5) **Extranonce** (hex)
6) **Difficulty** (double)

**Comment by Nashatyrev** [comment]
@nsiatras EthereumJ has nothing to do with NiceHash. It's Ethereum Java protocol implementation

**Comment by Nashatyrev** [comment]
Ok, closing this issue as not relevant
