### ISSUE TITLE
"$UnsafeComparer" is missing from class??

### ISSUE THREAD

**Issue by footloosejava** [ethereum/ethereumj#582]
I don't see the enum for "$UnsafeComparer".

Unless I'm missing something, it looks like it will always fetch the standby pure java version.

see org/ethereum/util/FastByteComparisons.java

**Comment by Nashatyrev** [comment]
Heh nice, you are right. 
However this method is definitely far from top hotspot methods, so leaving it as is for now. 
Thanks for reporting!
