### ISSUE TITLE
eth_call has not implemented the method with pending state.

### ISSUE THREAD

**Issue by YESPPG** [ethereum/ethereumj#588]

**Comment by Nashatyrev** [comment]
Yep, this is the miss. 
@cupuyc Can you please take a look? That shouldn't be a big deal to fix

**Comment by Nashatyrev** [comment]
@YESPPG How are you using JSON-RPC? Via Harmony?

**Comment by Nashatyrev** [comment]
Fixed with https://github.com/ethereum/ethereumj/pull/603
