### ISSUE TITLE
ERROR [sync]  No parent on the chain for block.number

### ISSUE THREAD

**Issue by arass** [ethereum/ethereumj#589]
Got the latest tree couple hours ago.
Still shows it's the latest version (so it wasn't a partial check-in).

Had to delete old DB (versioning).
Connecting to Morden, I get a ton of (for each block number):
**00:54:20.972 ERROR [sync]  No parent on the chain for block.number: 59382 block.hash: b6702c**
This happen when I run my code or the MordenSample.

Is this something I'm doing wrong? Or are others having same problem introduced in the last couple of days?
Should I just wait for sync to finish? Or is it dead?

Also, is there a way to specify a starting block so I don't have to sync the whole 10 gigs every time? I so geth gives one that option.... is that done through "sync.fast.pivotBlockHash" (tried that, but it still starts from block 0)?

Thanks.

**Comment by Nashatyrev** [comment]
@arass The `develop` branch was recently merged with large feature so it might be not very stable for now
For fast sync (still in alpha stage) try to switch it on by setting `sync.fast.enabled = true`

**Comment by Nashatyrev** [comment]
I will check `MordenSample` shortly on the new version

**Comment by arass** [comment]
Tried to use the sync.fast.
Got this. There's an explicit cast at FastSyncManager.java:231 to Eth63 which blows up.
Tried swapping for Eth62, but that doesn't have the requestTrieNodes() method on it.

13:44:49.126 ERROR [sync]  Error
java.lang.ClassCastException: org.ethereum.net.eth.handler.Eth62 cannot be cast to org.ethereum.net.eth.handler.Eth63
	at org.ethereum.sync.FastSyncManager.requestNextNodes(FastSyncManager.java:231)
	at org.ethereum.sync.FastSyncManager.retrieveLoop(FastSyncManager.java:287)
	at org.ethereum.sync.FastSyncManager.main(FastSyncManager.java:344)
	at org.ethereum.sync.FastSyncManager$2.run(FastSyncManager.java:97)

Any luck fixing Morden yet?

**Comment by arass** [comment]
Anton, do you have a fix for this? (even if I have to patch locally).
Would like to continue debugging my stuff.

**Comment by Nashatyrev** [comment]
Hi, Alex! Sorry currently working on delivering new features and HF release. Will get back to bugs later

**Comment by arass** [comment]
Tried to use an earlier version and failed same way. Any idea which version/hash worked on Morden last? I just need something I can work off of. And I need a recent compiler that supports pragma and modifiers.

**Comment by zilm13** [comment]
@arass Have you tried 1.3.6-RELEASE?

**Comment by arass** [comment]
@zilm13 If I'm not mistaken it doesn't support modifiers in contracts.
