### ISSUE TITLE
eth_call always uses 0x0 as the sender

### ISSUE THREAD

**Issue by crazyquark** [ethereum/ethereumj#598]
This would be fine except if you have a method like this:

```
function modifyStorage(uint256 param)  public returns (bool) {
        // owner is set in the constructor
        if (msg.sender != owner) {
            return false;
        }

       // do stuff, modify storage

        return true;
    }
```
eth_call will always return false on this function so you cannot dry run.

go-ethereum handles this properly.

**Comment by cupuyc** [comment]
@Nashatyrev are we going to fix this?
Dmitry told that you discussed that and it could have side effects.
As for me we could leave current behavior and only apply custom sender if its value passed. I don't see side effects because we could change code only in jsonrpc.

**Comment by Nashatyrev** [comment]
@crazyquark How are you using JSON RPC interface? Via Harmony HTTP?

**Comment by cupuyc** [comment]
Fixed in Harmony

**Comment by cupuyc** [comment]
@Nashatyrev applied correct fix. In Harmony we don't require signature when sending local transaction (constant). So user may invoke constant call on behalf of any account.

**Comment by Nashatyrev** [comment]
If fixed, then closing this
