### ISSUE TITLE
handle function types 

### ISSUE THREAD

**Issue by adridadou** [ethereum/ethereumj#604]
It would be actually pretty cool to be able to give the method of a proxied contract as a parameter.

https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI
https://solidity.readthedocs.io/en/develop/types.html#function-types

**Comment by Nashatyrev** [comment]
@adridadou  sorry, I forget what this issue is about. Could you please remind what you was talking about?

**Comment by adridadou** [comment]
In Solidity, you can now pass a function pointer as a parameter. This issue is about handling this

**Comment by Nashatyrev** [comment]
Oh cool, nice feature! Missed it
