### ISSUE TITLE
Can't use tilda for referencing home dir in config

### ISSUE THREAD

**Issue by cupuyc** [ethereum/ethereumj#611]
I want to keep my database at some directory from user home directory.
When I set `database.dir = ~/ethereumj/testnetSampleDb`, it resolves to `/Users/stan/work/workspace-ether/ethereumj/~/ethereumj/testnetSampleDb`, and this is unexpected for me.

**Comment by Nashatyrev** [comment]
`~` is purely bash shortcut and has nothing to do with java

**Comment by cupuyc** [comment]
I see.
We could consider replacing `~` with user home, like in Stackoverflow answer:
`path = path.replaceFirst("^~",System.getProperty("user.home"));`

**Comment by romanman** [comment]
solution:

```${user.home}/.../```
