### ISSUE TITLE
Contract deploying tuto

### ISSUE THREAD

**Issue by MethylHaine** [ethereum/ethereumj#612]
Hi everyone,
I assume this is not the place for posting about this, sorry about that..
I'm completely new to the blockchain technology and would like to create a contract with parameters, and submit it to the blockchain (Ropsten). I managed to obtain a relatively satisfying result with the geth cli (on Morden testnet), but ethereumj fits well most to my needs. However, I wasn't able to find a single **simple** tutorial that describes steps by steps the specific methods to use in each specifics cases.. i'm aware that samples are given with ethereumj and I really tried to completely understand how it works, but I couldn't even manage to compile my contract without issues (when it compiles just fine with an online solc compiler).
Could someone give me a link with an understandable tutorial, or give me some basics indications on how to proceed ? I need to compile a contract, deploy it to Ropsten, and call its function later.
Sorry for the long post, in the wrong place, with poor language usage..
Best regards.

**Comment by zilm13** [comment]
@MethylHaine what errors do you have? EthereumJ is bundled with pretty old Solc compiler, maybe the issue is in it? What you don't understand in deploy contract sample?

**Comment by MethylHaine** [comment]
Thanks very much for replying.
I think i understood how to globally process. I create a contract which I put in a string, then compile it and I try to deploy it on the blockchian via a submitTransaction, as described in the various samples.
The contract does not compile on my laptop, however it does on my co-worker's one (two man team project..).
We have the exacts same config, so I assume this is a memory issue with my computer. Our main issue remains to deploy the contract on Ropsten : when we launch transaction, our nonce is null or void, the transaction is submitted but nothing happen next. We also are unable to get info about our transaction hash, i.e tracking it, and the transaction ain't deployed on Ropsten (checked with etherscan) Could I possibly send you our code so that you read it shortly ?

**Comment by zilm13** [comment]
There should be some errors output here:
https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/samples/CreateContractSample.java#L55-L59
What do you see, could you paste it?

Do you have funds on address, which is the sender of contract?

Yeah, share it.

**Comment by MethylHaine** [comment]
This is exactly where I have my error. It works fine with my co-worker laptop however.
We do have funds on sender address (mined with ropsten-miner).
Thanks again for everything, here is the code of our simple transaction attempt : 

`
import java.math.BigInteger;
import org.ethereum.core.Transaction;
import org.ethereum.crypto.ECKey;
import org.ethereum.facade.Ethereum;
import org.ethereum.facade.EthereumFactory;
import org.ethereum.util.ByteUtil;
import org.spongycastle.util.encoders.Hex;

public class Start {

	public static void main(String[] arg) {
		
		//Sync BlockChain
		Ethereum ethereum = EthereumFactory.createEthereum() ;
		
		//Init Sender and Receipt Address
		ECKey sender = ECKey.fromPrivate(Hex.decode("287fc6941394e06872850966e20fe190ad43b3d0a3caa82e42cd077a6aaeb8b5")) ;
		byte[] receipt = Hex.decode("49a337147d9249ffe437a780fd6ba1ffd3e2bdad") ;
		
		//Create tx to send ether
		Transaction tx = new Transaction(
				ByteUtil.bigIntegerToBytes(ethereum.getRepository().getNonce(sender.getAddress())),
				ByteUtil.longToBytesNoLeadZeroes(ethereum.getGasPrice()),
				ByteUtil.longToBytesNoLeadZeroes(200000),
				receipt,
				ByteUtil.bigIntegerToBytes(BigInteger.valueOf(1)),
				new byte[0],
				ethereum.getChainIdForNextBlock()) ;
		
		//Sign it
		tx.sign(sender);
		
		//Submit it
		ethereum.submitTransaction(tx) ;	
	}
}`

**Comment by zilm13** [comment]
@MethylHaine 
what version do you use?

**Comment by MethylHaine** [comment]
1.3.9-RELEASE

**Comment by zilm13** [comment]
I've successfully sent the tx: https://testnet.etherscan.io/tx/0xf51b78f4140cd8b7edba5bdb29006ee3655530c57f7dbd067f2d19e7bd77f6d8

1) Check that private key, is correct, Hex.toHexString(sender.getAddress()) should match your sender address
2) Maybe you are sending tx without full sync. If so, you are getting incorrect nonce from repository, you should send txs only when sync is done. For example, this way (better way with getting tx status is in samples)

```java
package org.ethereum;

import org.ethereum.cli.CLIInterface;
import org.ethereum.config.SystemProperties;
import org.ethereum.core.Block;
import org.ethereum.core.BlockSummary;
import org.ethereum.core.PendingState;
import org.ethereum.core.Transaction;
import org.ethereum.core.TransactionExecutionSummary;
import org.ethereum.core.TransactionReceipt;
import org.ethereum.crypto.ECKey;
import org.ethereum.facade.Ethereum;
import org.ethereum.facade.EthereumFactory;
import org.ethereum.listener.EthereumListener;
import org.ethereum.net.eth.message.StatusMessage;
import org.ethereum.net.message.Message;
import org.ethereum.net.p2p.HelloMessage;
import org.ethereum.net.rlpx.Node;
import org.ethereum.net.server.Channel;
import org.ethereum.util.ByteUtil;
import org.spongycastle.util.encoders.Hex;

import java.io.IOException;
import java.math.BigInteger;
import java.net.URISyntaxException;
import java.util.List;

import static java.lang.Thread.sleep;
import static org.ethereum.crypto.HashUtil.sha3;

/**
 * @author Roman Mandeleil
 * @since 14.11.2014
 */
public class Start {

    private static Ethereum ethereum;
    private static boolean isSyncDone = false;

    public static void main(String args[]) throws IOException, URISyntaxException {
        CLIInterface.call(args);

        if (!SystemProperties.getDefault().blocksLoader().equals("")) {
            SystemProperties.getDefault().setSyncEnabled(false);
            SystemProperties.getDefault().setDiscoveryEnabled(false);
        }

        ethereum = EthereumFactory.createEthereum();
        ethereum.addListener(new EthereumListener() {
            @Override
            public void trace(String output) {

            }

            @Override
            public void onNodeDiscovered(Node node) {

            }

            @Override
            public void onHandShakePeer(Channel channel, HelloMessage helloMessage) {

            }

            @Override
            public void onEthStatusUpdated(Channel channel, StatusMessage status) {

            }

            @Override
            public void onRecvMessage(Channel channel, Message message) {

            }

            @Override
            public void onSendMessage(Channel channel, Message message) {

            }

            @Override
            public void onBlock(BlockSummary blockSummary) {

            }

            @Override
            public void onPeerDisconnect(String host, long port) {

            }

            @Override
            public void onPendingTransactionsReceived(List<Transaction> transactions) {

            }

            @Override
            public void onPendingStateChanged(PendingState pendingState) {

            }

            @Override
            public void onPendingTransactionUpdate(TransactionReceipt txReceipt, PendingTransactionState state, Block block) {

            }

            @Override
            public void onSyncDone() {
                isSyncDone = true;
            }

            @Override
            public void onNoConnections() {

            }

            @Override
            public void onVMTraceCreated(String transactionHash, String trace) {

            }

            @Override
            public void onTransactionExecuted(TransactionExecutionSummary summary) {

            }

            @Override
            public void onPeerAddedToSyncPool(Channel peer) {

            }
        });

        if (!SystemProperties.getDefault().blocksLoader().equals(""))
            ethereum.getBlockLoader().loadBlocks();
        new Thread(new SendTx(), "SampleWorkThread").start();
    }

    public static class SendTx implements Runnable {


        @Override
        public void run() {
            while (true) {
                if (!isSyncDone) {
                    try {
                        sleep(5000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                } else {
                    //Init Sender and Receipt Address
                    ECKey sender = ECKey.fromPrivate(sha3("cow".getBytes()));
                    byte[] receipt = Hex.decode("49a337147d9249ffe437a780fd6ba1ffd3e2bdad");

                    //Create tx to send ether
                    Transaction tx = new Transaction(
                            ByteUtil.bigIntegerToBytes(ethereum.getRepository().getNonce(sender.getAddress())),
                            ByteUtil.longToBytesNoLeadZeroes(ethereum.getGasPrice()),
                            ByteUtil.longToBytesNoLeadZeroes(200000),
                            receipt,
                            ByteUtil.bigIntegerToBytes(BigInteger.valueOf(1)),
                            new byte[0],
                            ethereum.getChainIdForNextBlock());

                    //Sign it
                    tx.sign(sender);

                    //Submit it
                    ethereum.submitTransaction(tx);
                    try {
                        sleep(5000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    ethereum.close();
                    System.exit(13);
                }
            }
        }
    }

}
```

**Comment by MethylHaine** [comment]
Thanks a lot, you are really helping us there. The address is correct, we saw the transaction on etherscan when you submitted it. We'll immediately try to fully understand your modifications so that we can correctly advance in our contract submission, and we'll keep you posted if it's okay with you.
Could you just explain the usage (or utility) of all the @override functions you added in the ethereum listener ?
We will check the samples, I assume usage of sendTxAndWait is recommended ?
Thanks a lot for your patience and you investment, we were really beginning to lose hope, we can finally advance thanks to you.

**Comment by zilm13** [comment]
@MethylHaine 
I've overrided only this in listener
```java
            @Override
            public void onSyncDone() {
                isSyncDone = true;
            }
```
So when sync is done, I know it. You could listen to any other ethereum events like this.

Yes, look through the code, Samples in the samples folder are waiting till the sync is done (but handles other events, just to let you know about), then push transaction to the net, then parse every new block arrived to find your tx inside, and when it's found in some block, you could be sure, that it's in the blockchain.

**Comment by MethylHaine** [comment]
You made the whole thing a lot more understandable.
We are trying to implement our submission contract protocol with your advices, hope it will lead to something, we'll keep you posted.
Thanks for everything.

**Comment by zilm13** [comment]
@MethylHaine you are welcome!

**Comment by MethylHaine** [comment]
So we managed to deploy a simple contract an we'll begin to test our own contract.
We used tx status and management functions from samples and everything seems to works fine.
However I do have a problem with the compilation of the contract on my machine when it works fine with my co-worker laptop..
call of function _SolidityCompiler.compile_ returns the following error : 

```
java.lang.RuntimeException: Contract compilation failed:
/tmp/solc/solc: 3: /tmp/solc/solc: Syntax error: word unexpected (expecting ")")
```
I'm running EthereumJ with 

> export _JAVA_OPTIONS="-Xms512m -Xmx512m" 

option because it seems I have some memories issues with my JVM.
Could the issue be unavoidably dependent of my system config' ? Or is there a way to get around the problem ?

**Comment by zilm13** [comment]
On what OS are you running it (with version)?

**Comment by MethylHaine** [comment]
Linux Mint 18 (Sarah) cinnamon

**Comment by zilm13** [comment]
@MethylHaine Sorry, missed your answer
Looks like you have problems with solc compiler

Could you run `solc --version` with it in tmp. It should look something like that but with another version:
```bash
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.4+commit.4633f3de.Darwin.appleclang
```
Do you see all files from [this folder](https://github.com/ethereum/ethereumj/tree/master/ethereumj-core/src/main/resources/native/linux/solc) there?

If you have compatibility issues with it, you have several options:
1. Use develop SNAPSHOT ethereumj library (currently develop is unstable, but we should release it in a few weeks)
	```
	repositories {
	// add snapshot repository
	    maven { url "https://oss.jfrog.org/libs-snapshot" }
	}

	dependencies {
	// use develop snapshot version
	    compile "org.ethereum:ethereumj-core:1.4.0-SNAPSHOT"
	}
	```
   It uses binaries from [solcJ package](https://github.com/ether-camp/solcJ) package, you can try different versions. Also you could [compile solc](https://github.com/ethereum/solidity) yourself and use `solc.path` option for your binaries.
2. Fork ethereumj, and change solc binaries in resources.
3. [Add solcJ dependency](https://github.com/ether-camp/ethereum-harmony/blob/master/build.gradle#L44) like it's done in our Harmony project, to your project. You will need to [extract it](https://github.com/ether-camp/ethereum-harmony/blob/master/build.gradle#L173-L176), then [copy and use all logic from EthereumJ](https://github.com/ether-camp/ethereum-harmony/tree/master/src/main/java/com/ethercamp/harmony/service/contracts/compiler) to work with it.
4. Possibly discover, why bundled solc binary is not working on your system (maybe some libraries conflict) and solve this issue.

**Comment by MethylHaine** [comment]
Hi, sorry I've been really busy lately..
I tried the various solutions you gave me, but the issue remains, I sometimes get a "broken pipe" error instead of usual "expected ")"". I will soon change my computer, so I'll give it another shot and keep you posted, thanks again for your answers

**Comment by adridadou** [comment]
Sorry for the self promotion but maybe have a look at the library I've written: github.com/adridadou/eth-contract-api

I'm using EthereumJ but I have a nice  API to deploy contracts. It can also help understanding how it is done I think

**Comment by MethylHaine** [comment]
Thanks for the suggestion.
We managed to write something functional, but we'll take a look at your code, seems really interesting.

**Comment by adridadou** [comment]
Cool. Feel free to contact me if you need any help or have any question. I'm @adridadou on gitter
