### ISSUE TITLE
gasUsed inconsistent in TransactionExecutionSummary and TransactionReceipt

### ISSUE THREAD

**Issue by LeonSpark** [ethereum/ethereumj#613]
In BlockSummary,  the same transaction in TransactionExecutionSummary and TransactionReceipt return different gasUsed. 
Most of the time, gasUsed in TransactionExecutionSummary is 0

**Comment by zilm13** [comment]
Hi @LeonSpark could you please provide steps to reproduce it? I didn't find such behaviour during the sync.

**Comment by Nashatyrev** [comment]
I saw either 0 or the same value as in `TransactionReceipt`
`TransactionExecutionSummary` is intended primarily for information about contract execution and creates kind of stub for value transfer txs. However I don't see any reasons why this stub couldn't contain the right gasUsed for value transfers
