### ISSUE TITLE
RepositoryTest.testMultiThread fails periodically 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#618]
```
Running test: test testMultiThread(org.ethereum.db.RepositoryTest)
org.ethereum.db.RepositoryTest > testMultiThread STANDARD_ERROR
   java.lang.AssertionError: expected:<26143> but was:<26142>
       at org.junit.Assert.fail(Assert.java:88)
       at org.junit.Assert.failNotEquals(Assert.java:743)
       at org.junit.Assert.assertEquals(Assert.java:118)
       at org.junit.Assert.assertEquals(Assert.java:144)
       at org.ethereum.db.RepositoryTest$2.run(RepositoryTest.java:980)
       at java.lang.Thread.run(Thread.java:745)
org.ethereum.db.RepositoryTest > testMultiThread FAILED
   java.lang.RuntimeException: Test failed.
       at org.ethereum.db.RepositoryTest.testMultiThread(RepositoryTest.java:1000)
```

**Comment by zilm13** [comment]
Version that fails all the time in https://github.com/ethereum/ethereumj/tree/fix/multithread-sources plus some comments

**Comment by Nashatyrev** [comment]
When Repository doing commit it consequently flushes different sources so the parent repo is in inconsistent state during this process. 
The parallel threads in the test call `RepositoryRoot.getRoot()` which causes `RepositoryImpl.commit()` (it is not committing to the backing store but need all sources to be flushed to the state trie to obtain root)
So when the main testing thread does `track.commit()` and another thread causes `repository.commit()` there is a race. 
Actually this test shouldn't reflect the real situation: any concurrent repository modifications should occur on different snapshot `RepositoryRoot` instances 
Resolved with https://github.com/ethereum/ethereumj/commit/d42565548f421eb25efce9c1ae08533039895e64

**Comment by zilm13** [comment]
@Nashatyrev yeah I've tried to sync both getRoot and flush/commit but it didn't helped alone
