### ISSUE TITLE
Cover ethereumJ with integration testing

### ISSUE THREAD

**Issue by cupuyc** [ethereum/ethereumj#619]
Anton proposed to use https://github.com/karalabe/hive
Let's try.

So far I was able to run on Azure Ubuntu 16.
I experienced problems running on Mac, but got it working in some kind after installing beta version of Docker 1.13.0-rc3. It hangs on some tests on Mac. I guess it is related to heavy using of docker in docker feature which differs for Mac.

From initial look I noticed that hive tests use not compatible genesis content. Will try to update core `develop`

**Comment by cupuyc** [comment]
So far we can run tests over Harmony master branch on Ubuntu with:
`hive --client=ethereumj:master --smoke --docker-noshell=true --test=.`

I've adjusted genesis files to meet ethereumJ `master` compatibility. I put my changes to https://github.com/ether-camp/hive 
Many of tests still fails because of different CLI to to geth. For example our node can't load separate database and blocks data.

I still have problems with hive on Mac, so I'm using rsync to update files on Ubuntu.

@Nashatyrev what is expected result of this task?

**Comment by cupuyc** [comment]
BTW `geth` uses addition field in genesis:
```
	"config"     : {
		"daoForkBlock"   : 314,
		"daoForkSupport" : false
	}
```
Just for info.

**Comment by Nashatyrev** [comment]
I suppose the expected result is that we can do running Hive test suite as a part of our testing process (ideally the part of CI) 
I think we can adjust our CLI options to geth and adjust genesis format if required
