### ISSUE TITLE
RLP Decoding Error

### ISSUE THREAD

**Issue by ntallar** [ethereum/ethereumj#636]
I think there might be a bug on the RLP decoding implementation:

## Test that fails

```Java
@Test
public void decodingTest(){
    String testString = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"; //String of length 55
    byte[] obtained = encode(testString);
    String res = new String((byte[])decode(obtained, 0).getDecoded());
    assertEquals(testString, res); //Fails
}
```

## Cause

```Java
public static DecodeResult decode(byte[] data, int pos) {
    ...
   } else if (prefix < OFFSET_LONG_ITEM) {
        int len = prefix - OFFSET_SHORT_ITEM; // length of the encoded bytes
        return new DecodeResult(pos + 1 + len, copyOfRange(data, pos + 1, pos + 1 + len));
    ...
}
```

On the if condition that checks for the case in which a short string (with lenght lower than 56), previously encoded, is decoded, the upper bound for should be OFFSET_LONG_ITEM+1 (184) insead of OFFSET_LONG_ITEM (183). This causes the test case to be wrongly detected as a long string.

**Comment by zilm13** [comment]
@ntallar fixed in latest develop. Thank you for feedback.

**Comment by tinchou** [comment]
I just found this same bug in a different RLP implementation. They use https://github.com/ethereum/tests to test it, but it seems that corner cases such as this one haven't been moved to the common tests.

What is the policy on these types of tests? Shouldn't this have been added to the common tests suite so every implementation can benefit? Do you think I should send a PR to the `tests` repo to add this corner case test?

**Comment by tinchou** [comment]
Sorry for the spam: I think this same bug is affecting https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/util/RLP.java#L787.

RLP is critical to the correct functioning of Ethereum and it doesn't seem to be well tested. Maybe it's time to come up with a full test suite?
