### ISSUE TITLE
handle smart contract metadata (Solidity + metadata object)

### ISSUE THREAD

**Issue by adridadou** [ethereum/ethereumj#637]
Solidity has a new output type 'metadata'
http://solidity.readthedocs.io/en/develop/miscellaneous.html#contract-metadata

It should be possible to:
- use the compilation option "--metadata" to generate it
- have access to it (same as ABI today)

**Comment by cupuyc** [comment]
@adridadou I see that `ContractMetadata` already has a `metadata` string property in _develop_ branch. Is it suitable for you?
```
        String contract = ...
        SolidityCompiler.Result res = SolidityCompiler.compile(
                contract.getBytes(), true, ABI, BIN, INTERFACE, METADATA);
        CompilationResult result = CompilationResult.parse(res.output);
        final CompilationResult.ContractMetadata contractMetadata = result.contracts.get("a");
        System.out.println(contractMetadata.metadata);
```

**Comment by adridadou** [comment]
yes sorry. I forgot to close this

**Comment by cupuyc** [comment]
Yeah, I forgot to link commit.
https://github.com/ethereum/ethereumj/commit/16304d3
