### ISSUE TITLE
Repository singleton bean needs to be returned back

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#641]
After refactoring we moved away from the notion of `Repository` as a singleton. Now the `Repository` instance is mainly a snapshot. 
We likely need to make a proxy `Repository` singleton which always refers to the best blockchain block snapshot

**Comment by adridadou** [comment]
fix it also in org.ethereum.facade.Ethereum.getRepository

**Comment by Nashatyrev** [comment]
@adridadou, yes sure. 
M.b. it make sense to rename and change semantics of this method? I.e. `Ethereum.getLatestRepository()`

**Comment by adridadou** [comment]
I think that getRepository should always return the latest one. A method that returns a snapshot should be called getRepositorySnapshot or something like that

**Comment by adridadou** [comment]
I don't know if it make sense to do it as part of this issue or create a new one  but,
BlockchainImpl.getRepository is not accessible from the Blockchain interface.
This means that I need to cast the object to access it, voiding the benefits of having an interface.
I would add the method to the interface if there is no good reason not to
