### ISSUE TITLE
Fast sync doesn't follow up chain when loading headers

### ISSUE THREAD

**Issue by cupuyc** [ethereum/ethereumj#678]
I noticed several times next behavior:
First Harmony loads state nodes and synced up to last block;
Then Harmony doesn't update best block for few minutes. At this time it loads headers.
Finally it shows correct best blocks.

<img width="795" alt="2ecc2ax4yc" src="https://cloud.githubusercontent.com/assets/54808/21566856/c2ec3212-ceaf-11e6-98cf-b0fdbd8ef223.png">

**Comment by Nashatyrev** [comment]
Yep, this is known behavior. 
To get SECURE sync as fast as possible `HeadersDownloader` works in aggressive manner, i.e. it loads as many IDLE peers as possible, thus a bit less aggressive regular sync working in parallel can fail getting any IDLE peer for a long time

**Comment by cupuyc** [comment]
With current `develop` I observed long out of sync time during blocks and receipts download phase of fast sync.

![pasted image at 2017_03_07 01_53 pm](https://cloud.githubusercontent.com/assets/54808/23661000/f344c202-0353-11e7-99b7-bbc92813bac7.png)
