### ISSUE TITLE
Make BlockchainConfig hierarchy more flexible for configuration 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/ethereumj#707]
Currently with every new fork we are doing a number of inheritance/delegate tweaks to avoid code duplication when the fork (or it's modification) is applied to different networks (ETH, ETC, Ropsten, etc)
I believe this could be made much easier

**Comment by romanman** [comment]
- Need to discuss -

**Comment by cupuyc** [comment]
Now complex blockchain config could look:
```
      new BaseNetConfig() {{
            add(0, new FrontierConfig());
            add(5, new HomesteadConfig());
            add(8, new DaoHFConfig(new HomesteadConfig(), 8));
            add(10, new Eip150HFConfig(new DaoHFConfig(new HomesteadConfig(), 8)));

      }}
```

**Comment by mkalinin** [comment]
Superseded by https://github.com/ethereum/ethereumj/issues/707
