### ISSUE TITLE
solidity compiler, make it possible to use import "...."

### ISSUE THREAD

**Issue by adridadou** [ethereum/ethereumj#713]
Right now, the only API for solidity compilation is passing a String.
Therefore, there is no way to have the code spread out multiple files. 

I think that anything that makes import works is fine but my personal preference would be to have an API that looks like this:
compile(File file) where it takes the file's current folder as the current directory for the process

**Comment by Nashatyrev** [comment]
@cupuyc can you please handle this if have free time slot?
