### ISSUE TITLE
My cpp miner can't connect to 127.0.0.1:8545

### ISSUE THREAD

**Issue by mit7577** [ethereum/ethereumj#717]
Hi!  I am a newbie, just installed a cpp etherium miner.  It cannot connect to 127.0.0.1:8545.  
Also geth cant syncronize
Does anyone know how to fix this?  Thanks!

**Comment by cupuyc** [comment]
EthereumJ core doesn't provide JSON-RPC interface. If you going to use EthereumJ peer, please see use [Harmony](http://github.com/ether-camp/ethereum-harmony)

`ethminer -F http://localhost:8080`
, note that it runs on 8080 port by default

**Comment by Nashatyrev** [comment]
@cupuyc I think JSON-RPC should run on other port than `8080`?

**Comment by cupuyc** [comment]
Now Harmony uses 8080 for presenting web GUI and JSON-RPC.

@Nashatyrev do you propose to add / move JSON-RPC to 8545?

**Comment by Nashatyrev** [comment]
Oh, yes you are right. 
I'm not sure, but I believe `8545` is the standard port for JSON-RPC. Are there any reasons you made it on 8080?

**Comment by cupuyc** [comment]
No special reason, it was easier from developer point of view (spring based project).

There is no default port for JSON-RPC, but it looks that most Ethereum peers selected 8545.

**Comment by mit7577** [comment]
I downloaded Harmony but see no instruction so have no clue what to do next.  Could you help?

**Comment by cupuyc** [comment]
Running instructions is placed in the readme.

To run private peer with mining, you can use `gradlew runMain` on Win or `./gradlew runMain` on Mac. Embedded CPU mining will start in 5-7 mins.

**Comment by mit7577** [comment]
With what editor do I open *.md?

**Comment by mit7577** [comment]
Thanks!
