### ISSUE TITLE
Can't connect from geth client to ethereumJ miner

### ISSUE THREAD

**Issue by dsapaev** [ethereum/ethereumj#718]
LOG from ethereumJ miner:
DISCONNECT reason=INCOMPATIBLE_PROTOCOL

genesis.json:

{
  "config":{
      "homesteadBlock":5
   },
  "nonce": "0x0000000000000042",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "difficulty": "0x400",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x8000000",
  "extraData": "0x1000000",
  "alloc":
  {
    "2644116ef02ee27563a8478052f5ff00ad6d24ad": { "balance": "1000000000000000000000000000000000000"
    }
  }
}

There are different hash at java miner and geth client

**Comment by dsapaev** [comment]
**Genesis block from geth:**

I0131 10:59:52.102257 eth/backend.go:191] Protocol Versions: [63 62], Network Id: 331188
I0131 10:59:52.102379 eth/backend.go:219] Chain config: {ChainID: 0 Homestead: 5 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: <nil> EIP158: <nil>}
I0131 10:59:52.102599 core/blockchain.go:219] Last header: #0 [e6c67fa9..] TD=1024
I0131 10:59:52.102616 core/blockchain.go:220] Last block: #0 [e6c67fa9..] TD=1024
I0131 10:59:52.102627 core/blockchain.go:221] Fast block: #0 [e6c67fa9..] TD=1024
I0131 10:59:52.103141 p2p/server.go:342] Starting Server
I0131 10:59:52.103301 p2p/server.go:610] Listening on [::]:30303
I0131 10:59:52.104283 node/node.go:341] IPC endpoint opened: /home/blockchain/privatedatadir/geth.ipc
Welcome to the Geth JavaScript console!
instance: Geth/v1.5.5-stable-ff07d548/linux/go1.7.4
coinbase: 0x2644116ef02ee27563a8478052f5ff00ad6d24ad
at block: 0 (Thu, 01 Jan 1970 00:00:00 UTC)
 datadir: /home/blockchain/privatedatadir
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
> eth.getBlock(0);
{
  difficulty: 1024,
  extraData: "0x01000000",
  gasLimit: 134217728,
  gasUsed: 0,
  hash: "0xe6c67fa91e088945ecc7e4c21954ab77b3980664a94d5aeb33220c9878f9c0fe",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000042",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 511,
  stateRoot: "0xbd74105152983be2a298d52e5f07f6f2a5895ac0e3a9bd57e88e6bc9941f6c5b",
  timestamp: 0,
  totalDifficulty: 1024,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}

**Genesis block from java miner:**
 f90208f90203a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347a00000000000000000000000000000000000000000000000000000000000000000a0bd74105152983be2a298d52e5f07f6f2a5895ac0e3a9bd57e88e6bc9941f6c5ba056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000082040080840800000080808401000000a00000000000000000000000000000000000000000000000000000000000000000880000000000000042c0c0
BlockData [ hash=4f49c208d1e9e5f0dae4a67e5751c4f1e7bb6dd2d84128245258a0e5519f4e65
  hash=4f49c208d1e9e5f0dae4a67e5751c4f1e7bb6dd2d84128245258a0e5519f4e65
  parentHash=0000000000000000000000000000000000000000000000000000000000000000
  unclesHash=1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
  coinbase=0000000000000000000000000000000000000000000000000000000000000000
  stateRoot=bd74105152983be2a298d52e5f07f6f2a5895ac0e3a9bd57e88e6bc9941f6c5b
  txTrieHash=56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
  receiptsTrieHash=56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
  difficulty=0400
  number=0
  gasLimit=08000000
  gasUsed=0
  timestamp=0 (1970.01.01 03:00:00)
  extraData=01000000
  mixHash=0000000000000000000000000000000000000000000000000000000000000000
  nonce=0000000000000042
Uncles []
Txs []
]

**Comment by Nashatyrev** [comment]
`coinbase` in genesis should be 20 bytes. Geth truncates it, Java don't. 
Use the following genesis:
```
{
"config":{
"homesteadBlock":5
},
"nonce": "0x0000000000000042",
"timestamp": "0x00",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"difficulty": "0x400",
"mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"coinbase": "0x0000000000000000000000000000000000000000",
"gasLimit": "0x8000000",
"extraData": "0x1000000",
"alloc":
{
"2644116ef02ee27563a8478052f5ff00ad6d24ad": { "balance": "1000000000000000000000000000000000000"
}
}
}
```
