### ISSUE TITLE
Support `code` and `nonce` in genesis `alloc`

### ISSUE THREAD

**Issue by holiman** [ethereum/ethereumj#728]
I'm trying to get ethereumJ to run through consensus-testing on Hive. I noticed that it does not support `code` in alloc, nor `nonce` . The former is pretty important, and the latter is a nice-to-have. Geth and Parity supports both options (I recently added `nonce` -support in genesis alloc there) - though it's not mandatory. 

Could you please implement that? 
Relevant section of geth: https://github.com/ethereum/go-ethereum/blob/master/core/genesis.go#L56

**Comment by cupuyc** [comment]
@holiman thanks for pointing to spec.

On our side we tried to cover ethereumJ with hive as well. Unfortunately I had to apply a lot of changes to EthereumJ, as well as some to hive. These changes will be included to `develop` soon.

My changes in *karalabe/hive* were related to DAG file caching. EthereumJ uses other binary format for storing DAG data.

**Comment by holiman** [comment]
Yep, I saw that there was some work in that direction - that's where my docker file and startup script comes from :)

**Comment by romanman** [comment]
... to describe latest structure of genesis

**Comment by romanman** [comment]
TODO duplicate 
https://github.com/ethereum/ethereumj/issues/698
```

We have constraint check like in DAO HF/NHF configs https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/config/blockchain/DaoNoHFConfig.java#L19-L21

It would be good to add ability to define any number of constraint checks via json config. So anyone will be able to switch to any branch on poor mining networks like Ropsten w/o updates of library classes.
Include #694 in this pull (fixes error when there are more than 1 constraint)
```

**Comment by holiman** [comment]
You may want to be inspired by this: https://github.com/ethereum/wiki/wiki/Ethereum-Chain-Spec-Format 

I think both Parity and Cpp-ethereum uses this format (or close to it)

**Comment by cupuyc** [comment]
@holiman I'm checking our peer with `hive` `simulation/consensus` test suite.

Even if I run in verbose mode, it is hard to understand what was wrong. For example I receive this fatal:

```
INFO[02-28|14:15:20] message from simulator                   client=ethereumj:develop simulator=ethereum/consensus log="Starting node for test InChainUncleGreatGreatGreatGreatGrandPa"
DBUG[02-28|14:15:20] new simulator request                    client=ethereumj:develop simulator=ethereum/consensus req-id=23 from=172.17.0.2:60222 method=POST endpoint=/nodes
DBUG[02-28|14:15:20] starting new client                      client=ethereumj:develop simulator=ethereum/consensus req-id=23
[fd3a609f] 
[fd3a609f] Hive simulator: http://172.17.0.1:37493
[fd3a609f] 
[fd3a609f] Client version: Harmony/v1.5.0/Linux/Java1.8/SNAPSHOT-7ac77de
[fd3a609f] Traceback (most recent call last):
[fd3a609f]   File "/simulator.py", line 100, in <module>
[fd3a609f]     main(sys.argv[1:])
[fd3a609f]   File "/simulator.py", line 78, in main
[fd3a609f]     executor = hivemodel.BlockTestExecutor(hive , Rules.RULES_FRONTIER))
[fd3a609f]   File "/hivemodel.py", line 119, in blockTests
[fd3a609f]     return self._performTests(start,end,whitelist, blacklist, testfiles, executor)
[fd3a609f]   File "/hivemodel.py", line 178, in _performTests
[fd3a609f]     pool.map(perform_work, [x for x in iterator()])
[fd3a609f]   File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
[fd3a609f]     return self.map_async(func, iterable, chunksize).get()
[fd3a609f]   File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
[fd3a609f]     raise self._value
[fd3a609f] Exception: Failed to POST req (404):not found
```

Could you please suggest how to troubleshot issue in that case.
