### ISSUE TITLE
Error resolving plugin [id: 'com.github.johnrengelman.shadow', version: '1.2.3']

### ISSUE THREAD

**Issue by CsterKuroi** [ethereum/ethereumj#733]
jihao@iZ25g9famsqZ:~/ethereumj$ ./gradlew build
Building version: 1.5.0-SNAPSHOT (from branch develop)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jihao/ethereumj/ethereumj-core/build.gradle' line: 18

* What went wrong:
Error resolving plugin [id: 'com.github.johnrengelman.shadow', version: '1.2.3']
> Could not GET 'https://plugins.gradle.org/api/gradle/2.8/plugin/use/com.github.johnrengelman.shadow/1.2.3'.
   > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.547 secs

**Comment by Nashatyrev** [comment]
Is it still reproducible (was not a connectivity issue)? If yes, which java version do you use?

**Comment by cupuyc** [comment]
This connectivity issue happens for me very often when I run ethereumj with clean gradle cache.
Maybe `jcenter.bintray.com` has rate limit.
Usually happens on `shadow-1.2.3.jar` and `netty` jars.
