### ISSUE TITLE
CPU mining stopped unexpectedly. Sync is off for miner. Might be related to newly connected `geth` peer.

### ISSUE THREAD

**Issue by cupuyc** [ethereum/ethereumj#736]
Logs are here:
https://gist.github.com/cupuyc/037e5adc053d17f7737bf115d0e7564f

Mining node synced from zero from other peers. Note that sync is disabled on this miner.
Mining looks worked on line 707. 
But after restart / context reload - it hanged on block 83472. 
Started working correctly after user restarted.

TODO Stan ensure spring context reload is disabled by default !!!
TODO Stan remove `sync.enabled=false` from `private.conf` to not confuse users which could use it as miner sample in private network.

**Comment by romanman** [comment]
To check Geth miner and Harmony miner.
