### ISSUE TITLE
configuring ethereumjwith private network

### ISSUE THREAD

**Issue by latifa1** [ethereum/ethereumj#746]
i add ethereumj to my project spring mvc and didn't know how to configure ethereumj.conf to connect with private network .please any help

**Comment by cupuyc** [comment]
EthereumJ have short configuration description at the bottom of readme.
https://github.com/ethereum/ethereumj#configuring-ethereumj

Most properties are located inside `.conf` file.

**Comment by latifa1** [comment]
my problem is i didn't know witch properties to be change that i could connect from java code to geth client testnet

**Comment by cupuyc** [comment]
Full list of properties with description:
https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/resources/ethereumj.conf

You could find connection properties here:
https://github.com/ether-camp/ethereum-harmony/wiki/Connecting-to-private-network
1. Set genesis
2. Configure blockchain settings
3. Set connection nodes.

**Comment by latifa1** [comment]
ok thank you for your help
