### ISSUE TITLE
Contract not responding as expected to function invocations on Private network

### ISSUE THREAD

**Issue by blmalone** [ethereum/ethereumj#763]
Please see this sample [`ethereumj private network`](https://github.com/blmalone/ethj-privatenet) starter project that I have put together. It will give you the steps to recreate. 

After updating my code to use the latest release, I am unable to retrieve the correct return value from a contracts function call. Logs look healthy with not sign of errors.

I use the following contract 
```
contract SimpleStorage {
  int storedData;

  function set(int x) {
    storedData = x;
  }
  function get() returns (int) {
    return storedData;
  }
}
```
**Steps:**
1. Deploy contract - wait for it to be mined
2. Write value using set(x) function (I use `515`) - wait for tx to be mined
3. Read new value by invoking get()

**Expected :** get() returns 515
**Actual :** get() returns 0

Result from running:
![screen shot 2017-03-14 at 14 26 32](https://cloud.githubusercontent.com/assets/15608778/23905267/590e1f16-08c2-11e7-9b51-583a18b11401.png)

**Comment by blmalone** [comment]
@Nashatyrev fyi

**Comment by Nashatyrev** [comment]
@blmalone 
Found this in your code: 
```
        Transaction contractTransaction =
                sendTransaction(null, senderKey, ETHER_TO_TRANSFER_IN_WEI, decode(contractBinary.bin));
```
where `ETHER_TO_TRANSFER_IN_WEI = 1`
Make sure you are either sending `0` value or marking the function as `payable`

**Comment by Nashatyrev** [comment]
BTW you may catch you Tx in the `onPendingTransactionUpdate` and check the execution result with `TransactionReceipt.getError()`

**Comment by blmalone** [comment]
Excellent spot, thanks @Nashatyrev!

Works with this contract and removing the Ether.
```
pragma solidity ^0.4.0;

contract SimpleStorage {
    uint storedData;

    function set(uint x) {
        storedData = x;
    }

    function get() constant returns (uint) {
        return storedData;
    }
}
```

I remember a while back I had to add 1 Eth to all my txs in order to make them work. This is clearly fixed now with the new version.
`onPendingTransactionUpdate` very useful also. Thanks, I'll close the issue.
