### ISSUE TITLE
upgrade google guava

### ISSUE THREAD

**Issue by adridadou** [ethereum/ethereumj#867]
Currently, ethj is using guava 16.0.1
The issue is that ethj is using some functions (something about threads) that don't exist anymore in guava 21

As a result, if your project imports ethj + guava 21, then mining silently fails. If you debug, you realize that you get an exception "MethodNotFound" while starting light mining but the application hangs because it happens in a separate thread

**Comment by jnorthrup** [comment]
i would be happy to drive this into an overall push via #878 and see where it leads.  right now i have general sweeping dependency upgrades not complaining relying on the maven versions-plugin to pick the latest and greatest libs and fixing breakage incrementally.

**Comment by adridadou** [comment]
I've created a PR for that

**Comment by jnorthrup** [comment]
which?
