### ISSUE TITLE
Many duplicated blocks comes from EthereumListener in BasicSample

### ISSUE THREAD

**Issue by vikulin** [ethereum/ethereumj#869]
10:46:04.776 INFO [sample]  New block: #3532851 (a47e7c <~ 707309) Txs:1, Unc: 0
10:46:06.781 INFO [sample]  New block: #3532851 (fef275 <~ 707309) Txs:130, Unc: 0
10:46:08.223 INFO [sample]  New block: #3532852 (137008 <~ fef275) Txs:55, Unc: 1
10:46:10.643 INFO [sample]  New block: #3532853 (5ece40 <~ 137008) Txs:2, Unc: 0
10:46:13.194 INFO [sample]  New block: #3532851 (be215a <~ 707309) Txs:130, Unc: 0
10:46:15.561 INFO [sample]  New block: #3532854 (cb25d6 <~ 5ece40) Txs:6, Unc: 0
10:46:27.157 INFO [sample]  New block: #3532855 (1a044b <~ cb25d6) Txs:0, Unc: 1
10:46:43.935 INFO [sample]  New block: #3532856 (a7477e <~ 1a044b) Txs:15, Unc: 0

**Comment by vikulin** [comment]
More logs:
03:50:26.615 INFO [sample]  New block: #3551010 (c64893 <~ 9ddf44) Txs:0, Unc: 0
03:50:41.521 INFO [sample]  New block: #3551011 (b17afa <~ c64893) Txs:4, Unc: 0
03:50:41.552 INFO [sample]  New block: #3551012 (9dd152 <~ b17afa) Txs:1, Unc: 0
03:50:42.193 INFO [sample]  New block: #3551012 (327425 <~ b17afa) Txs:1, Unc: 0
03:50:48.162 INFO [sample]  New block: #3551013 (944d77 <~ 9dd152) Txs:123, Unc: 0
03:50:56.334 INFO [sample]  New block: #3551011 (e0ce4c <~ c64893) Txs:130, Unc: 0
03:51:12.818 INFO [sample]  New block: #3551013 (9943e6 <~ 9dd152) Txs:0, Unc: 0
03:51:15.943 INFO [sample]  New block: #3551014 (2ee474 <~ 944d77) Txs:48, Unc: 1

**Comment by vikulin** [comment]
Any updates?

**Comment by mkalinin** [comment]
Are you referring to duplicated numbers? These are blocks from different forks as I can see, thus `EthereumListener` behaves as designed
