### ISSUE TITLE
EthereumJ can shut down randomly

### ISSUE THREAD

**Issue by ewiner** [ethereum/ethereumj#889]
We're using EthereumJ as a library, as part of a bigger application.  We've hit [this `System.exit()` call](https://github.com/ethereum/ethereumj/blob/release-1.4.x/ethereumj-core/src/main/java/org/ethereum/core/BlockchainImpl.java#L526) a couple times now, which has caused the whole application to shut down.

Is there something better the software can do in that situation apart from just shut down the whole JVM?

**Comment by Glamdring** [comment]
+1, this sounds like the wrong thing to do. If the error is so sever, throw an Error, but don't exit.

I guess you can workaround that by disabling it via a security manager: https://stackoverflow.com/questions/5401281/preventing-system-exit-from-api

but it should definitely be fixed. Maybe you can supply a Pull Request with, say, `throw new RuntimeException("Inconsistency block handling behaviour")`

**Comment by mkalinin** [comment]
An option is added for that exit, it uses `exitOnBlockConflict` flag which is `false` by default https://github.com/ethereum/ethereumj/commit/f6445416e1f784fb66b97135684aee83e5bb10c4
