### ISSUE TITLE
Upgrade LevelDB

### ISSUE THREAD

**Issue by Glamdring** [ethereum/ethereumj#896]
On windows at least the JVM fails regularly with LevelDB JNI failure. There is an issue that has been resolved there, but EthereumJ is using quite an old version (as well as a bit old version of leveldb itself).

Through maven exclusions and explicit dependencies I set up the latest leveldb and leveldb-jni and it seems to be working properly.

Are there are reasons to stick to the older versions, or it should be upgraded?

**Comment by Glamdring** [comment]
Here's a patch that can be applied directly. Build is passing with the new versions:


diff --git a/ethereumj-core/build.gradle b/ethereumj-core/build.gradle
index 37a4867..92a1885 100644
--- a/ethereumj-core/build.gradle
+++ b/ethereumj-core/build.gradle
@@ -105,7 +105,7 @@ test {
 
 ext {
     slf4jVersion = '1.7.7'
-    leveldbVersion = '0.7'
+    leveldbVersion = '0.9'
     scastleVersion = '1.53.0.0'
     springVersion = '4.2.0.RELEASE'
     hibernateVersion = '4.3.7.Final'
@@ -119,7 +119,7 @@ dependencies {
 
     compile "org.iq80.leveldb:leveldb:${leveldbVersion}"     // Java API wrapper around native components
 
-    compile "org.ethereum:leveldbjni-all:1.18.3"             // native leveldb components
+    compile "org.fusesource.leveldbjni:leveldbjni-all:1.8"    // native leveldb components
 
     compile "org.ethereum:solcJ-all:0.4.8"                   // Solidity Compiler win/mac/linux binaries

**Comment by Glamdring** [comment]
On closer inspection, after the upgrade the directory "peers" is not created in the database dir, though there are no errors.

**Comment by Nashatyrev** [comment]
Hey @Glamdring 
`org.iq80.leveldb` - is the LevelDB Java port, which showed to be pretty slower than native version. It is not currently used in EthJ (not sure why it is still in deps)
As for native LevelDB: we have custom `leveldbjni` build (which corresponds to `LevelDB 1.18`), because original (`org.fusesource.leveldbjni:leveldbjni-all:1.8`) had issues on Windows

**Comment by Glamdring** [comment]
@Nashatyrev unfortunately, for me the current leveldbjni fails on Windows as well, regularly. That's why I brought up the issue. After the upgrade I made locally, it worked. If your custom build is using really the latest version, that would be strange indeed
