### ISSUE TITLE
Can't get JSONRPC to listen on port 8545

### ISSUE THREAD

**Issue by James-Sangalli** [ethereum/ethereumj#900]
Hi Guys,

I am trying to get the morden node listing on port 8545 so I can interact with it via the JSON RPC. I can see the code to run this but it is not listening on that port when I run: **telnet localhost 8545**

```
JsonRpcWhisper rpcWhisper = new JsonRpcWhisper(new
URL("http://localhost:8545"));
ethereumj-core/src/main/java/org/ethereum/net/shh/JsonRpcWhisper.java
```

This appears to be working back in here: https://github.com/ethereum/ethereumj/issues/442

Any ideas?

Thanks

**Comment by mkalinin** [comment]
I'll close this one. It may be reopened later if it's still actual

**Comment by Kwaskoff** [comment]
> I'll close this one. It may be reopened later if it's still actual
How can I diagnose why this happened?
