### ISSUE TITLE
Error:Failed to resolve: commons-logging:commons-logging:1.2 

### ISSUE THREAD

**Issue by sandeshlasnapure** [ethereum/ethereumj#901]
what is wrong?
I am adding gradle dependency   
compile "org.ethereum:ethereumj-core:
compile "org.ethereum:solcJ-all:0.4.8"

**Comment by lebedevsd1** [comment]
@sandeshlasnapure hey did you solved this?

**Comment by sandeshlasnapure** [comment]
yes. add ethereumj-core-1.5.0-RELEASE.jar and slf4j-android-1.6.1-RC1.jar

**Comment by mkalinin** [comment]
Looks like it was solved

**Comment by HelixCat** [comment]
> yes. add ethereumj-core-1.5.0-RELEASE.jar and slf4j-android-1.6.1-RC1.jar

how can do that in my even project?
