### ISSUE TITLE
Reading contract events from the blockchain

### ISSUE THREAD

**Issue by epsstan** [ethereum/ethereumj#914]
What is the recommended way to read events generated from the blockchain.

I'm not asking about reading events in real-time using a EthereumListener. I want to scan the blocks and reconstruct the events.

Is this possible ? As far as I can see,  logs are accessible only through EthereumListener.onTransactionExecuted.TransactionExecutionSummary

**Comment by adonley** [comment]
@epsstan have you tried querying the node with getBlockByNumber and using something similar to `new BlockSummary(this.ethereum.getBlockchain().getBestBlock().getEncoded()).getSummaries();` to get the summaries from the block?

**Comment by mkalinin** [comment]
New Event API introduced in [1.7.0](https://github.com/ethereum/ethereumj/releases/tag/1.7.0) should help much with Event tracking.
