### ISSUE TITLE
How frequent are ethereumJ releases compared to go-ethereum?

### ISSUE THREAD

**Issue by akshatdev0** [ethereum/ethereumj#921]
There will be metropolis release for ethereum in september end.
I want to start a project and think that it would be a good idea to do it on metropolis release.

But I am only familiar with Java language and prefer to use ethereumJ over go-ethereum.
So I wanted to ask:

- How far behind are the releases of ethereumJ implementation compared to go-ethereum releases?

- Is there any difference or limitations between both implementation features or they are implemented same eventually over time?

- Does ethereumJ follow same roadmap?

- Will ethereumJ metropolis be released till october?

**Comment by mkalinin** [comment]
Hi there,

Both EthereumJ and go-ethereum implements Ethereum Yellopaper, so they are pretty same in terms of it. The main difference between clients is language and perhaps the way of how infrastracture can be built with usage of these clients. EthereumJ is a core library which implements independant ethereum node; with Ethereum Harmony on top this library makes up an ethereum client which is less or more similar to go-ethereum. 
EthereumJ will have Metropolis released in the same time as other clients do this. 

Please, close the issue when you think  you've got asnwers to all of your questions.
