### ISSUE TITLE
Byzantium release

### ISSUE THREAD

**Issue by mkalinin** [ethereum/ethereumj#923]
- [x] [EIP-100 Change difficulty adjustment to target mean block time including uncles](https://github.com/ethereum/EIPs/issues/100) | https://github.com/ethereum/ethereumj/pull/916
- [x] [EIP-206 REVERT instruction in the Ethereum Virtual Machine](https://github.com/ethereum/EIPs/pull/206) | https://github.com/ethereum/ethereumj/pull/918
- [X] [EIP-213 Precompiled contracts for addition and scalar multiplication on the elliptic curve alt_bn128](https://github.com/ethereum/EIPs/pull/213) | https://github.com/ethereum/ethereumj/pull/924
- [X] [EIP-212 Precompiled contract for pairing check](https://github.com/ethereum/EIPs/pull/212) | https://github.com/ethereum/ethereumj/pull/933
- [x] [EIP-198 Precompiled contract for bigint modular exponentiation](https://github.com/ethereum/EIPs/pull/198) | https://github.com/ethereum/ethereumj/pull/920
- [x] [EIP-211 New opcodes: RETURNDATASIZE and RETURNDATACOPY](https://github.com/ethereum/EIPs/pull/211) | https://github.com/ethereum/ethereumj/pull/919
- [x] [EIP-214 New opcode STATICCALL](https://github.com/ethereum/EIPs/pull/214) | https://github.com/ethereum/ethereumj/pull/922
- [x] [EIP-649 Metropolis Difficulty Bomb Delay and Issuance Reduction](https://github.com/ethereum/EIPs/pull/669) | https://github.com/ethereum/ethereumj/pull/927
- [x] [EIP-658 Embedding transaction return data in receipts](https://github.com/ethereum/EIPs/pull/658) | https://github.com/ethereum/ethereumj/pull/928
- [X] [EIP-684 Prevent overwriting contracts](https://github.com/ethereum/EIPs/issues/684) | https://github.com/ethereum/ethereumj/pull/932
- [x] Fix `BlockchainTests/TransitionTests` execution
- [x] Add `BlockchainTests/GeneralStateTests` execution
- [x] 100% TCK tests passing

**Comment by lyless** [comment]
hello. i want to make sure my program is ready before hard fork happen. i do not know when hard fork will be happen. may be Sept. 22nd ? is there a release version will be released for ethereumj or i will merge the each change to my program manually? if i do not update the ethereumj when hard fork happen, ethereumj will hang in some blog can not receive the new block?

**Comment by mkalinin** [comment]
@lyless The release is the first decade of October. It's gonna be a release of EthereumJ binaries before hard fork happens

**Comment by lyless** [comment]
@mkalinin thank you. that is great helpful for me.
