### ISSUE TITLE
can not sync done in ROPSTEN

### ISSUE THREAD

**Issue by lyless** [ethereum/ethereumj#930]
i use ethereumj 1.5.0 to download the block in testnet(ROPSTEN).
but it always can not sync done to best block, and very slow with few peer connected.
i check the log found out the 585503's block hash dos not match the other peers

> 15:00:00.861 DEBUG [sync]  Peer f248afec: wrong fork (Block 585503 hash constraint violated. Expected:c4b3dcb5b22554db111148cca5181374585b037cc0ad786460319027a3486104, got: e8d61ae10fd62e639c2e3c9da75f8b0bdb3fa5961dbd3aed1223f92e147595b9). Drop the peer and reduce reputation.

i check out this web site, the hash of block 585503 is 0xe8d61ae10fd62e639c2e3c9da75f8b0bdb3fa5961dbd3aed1223f92e147595b9
https://ropsten.etherscan.io/block/585503

the setting of ropsten.json is below. i modifed to "0xe8d61ae10fd62e639c2e3c9da75f8b0bdb3fa5961dbd3aed1223f92e147595b9".
block downlad   ##normally.

ropsten.json 
```
"headerValidators": [
      {"number": 10,     "hash": "0xb3074f936815a0425e674890d7db7b5e94f3a06dca5b22d291b55dcd02dde93e"},
      {"number": 585503, "hash": "0xc4b3dcb5b22554db111148cca5181374585b037cc0ad786460319027a3486104"}
    ]
```

**Comment by mkalinin** [comment]
That was fixed. Thanks
