### ISSUE TITLE
http://ethereumj.io down

### ISSUE THREAD

**Issue by charbull** [ethereum/ethereumj#937]
hello,

just got here, seems that http://ethereumj.io is down,

Thx

**Comment by xmkane** [comment]
+1
some doc local avable?

**Comment by jeremie-H** [comment]
Is this project abandoned ? there is no update since 23 Aug ? no more website..

**Comment by jiapanlong** [comment]
anybody have the local document?

**Comment by jiapanlong** [comment]
anybody cached the document?

**Comment by ajlopez** [comment]
Now, it is pointing to a domain register site, domain expired?

**Comment by bibryam** [comment]
How can we acceess it then? what is the IP of the site?

**Comment by zilm13** [comment]
We don't have any control of this website. Looks like it's closed and not maintained.
As for EthereumJ it's alive and we are currently working on performance improvements and new features.
We don't have any comprehensive documentation online, so the best way to learn EthereumJ is using its Javadocs and understanding the Samples https://github.com/ethereum/ethereumj/tree/develop/ethereumj-core/src/main/java/org/ethereum/samples

**Comment by bibryam** [comment]
Can you change the description of this project then? The first thing people discover when they come to this github project is to see and click on the borken link. That immeadiatly implies the project is not actively deceloped and maintained. 
That was my thought few months back... then I head to web3j...

**Comment by zilm13** [comment]
@bibryam ouch, have not noticed it. Removed it from top description.
