### ISSUE TITLE
Can't peer with Geth v1.7.1+

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/ethereumj#941]
My node does not peer with any nodes running Geth v1.7.1 where the Devp2p protocol is 5

While I can pair with some older -unstable releases of Geth v1.7.1 where devp2p is still 4, I can't peer to anything newer...

**Comment by MysticRyuujin** [comment]
Here's an example of the bombardment of P2p messages I'm seeing

```
2017-10-21 17:16:29,191 WARN  [nioEventLoopGroup-3-12] net - P2p handling failed
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: RLP wrong encoding (4ca8f84a3f01850400000000a0d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3822100)
```

```
2017-10-21 17:16:31,608 WARN  [nioEventLoopGroup-3-2] net - P2p handling failed
io.netty.handler.codec.DecoderException: java.lang.ClassCastException: org.ethereum.util.RLPItem cannot be cast to org.ethereum.util.RLPList
```

**Comment by mkalinin** [comment]
Fix in https://github.com/ethereum/ethereumj/pull/945

**Comment by MysticRyuujin** [comment]
I can confirm that my node is now peered with lots of new Geth nodes > 1.7.1
