### ISSUE TITLE
personal_unlockAccount  direct return true, no logic

### ISSUE THREAD

**Issue by tianleios** [ethereum/ethereumj#943]
@Override
    public boolean personal_unlockAccount(String addr, String pass, String duration) {
        String s = null;

////////  should have logic code
        try {
            return true;
        } finally {
            if (logger.isDebugEnabled()) logger.debug("personal_unlockAccount(" + addr + ", ***, " + duration + "): " + s);
        }
    }

**Comment by mkalinin** [comment]
Add a link pointing to that piece of code, please

**Comment by tianleios** [comment]
package org.ethereum.jsonrpc;
class JsonRpcImpl
line num 1520;
Method:  
    public boolean personal_unlockAccount(String addr, String pass, String duration)

**Comment by mkalinin** [comment]
I see. It seems to be an old outdated JSON-RPC implementation which is not supported and will hardly be supported. Use Harmony to get JSON-RPC on top of EthereumJ
