### ISSUE TITLE
NPE happens in some cases while Sync

### ISSUE THREAD

**Issue by vikulin** [ethereum/ethereumj#948]
develop branch, fast sync = true

09:01:11.341 ERROR [sync]  Error processing block #4499182 (04fa5f <~ ba85dd) Txs:50, Unc: 0:
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:159)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:115)
        at org.ethereum.trie.TrieImpl.encode(TrieImpl.java:462)
        at org.ethereum.trie.TrieImpl.flush(TrieImpl.java:663)
        at org.ethereum.db.RepositoryRoot$MultiStorageCache.flushChild(RepositoryRoot.java:57)
        at org.ethereum.db.RepositoryRoot$MultiStorageCache.flushChild(RepositoryRoot.java:40)
        at org.ethereum.datasource.MultiCache.flushImpl(MultiCache.java:72)
        at org.ethereum.datasource.AbstractChainedSource.flush(AbstractChainedSource.java:64)
        at org.ethereum.db.RepositoryRoot.getRoot(RepositoryRoot.java:119)
        at org.ethereum.core.BlockchainImpl.applyBlock(BlockchainImpl.java:899)
        at org.ethereum.core.BlockchainImpl.processBlock(BlockchainImpl.java:854)
        at org.ethereum.core.BlockchainImpl.addImpl(BlockchainImpl.java:582)
        at org.ethereum.core.BlockchainImpl.add(BlockchainImpl.java:532)
        at org.ethereum.core.BlockchainImpl.tryToConnect(BlockchainImpl.java:434)
        at org.ethereum.sync.SyncManager.produceQueue(SyncManager.java:267)
        at org.ethereum.sync.SyncManager.access$600(SyncManager.java:56)
        at org.ethereum.sync.SyncManager$5.run(SyncManager.java:177)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.ethereum.trie.TrieImpl$Node.encodeRlpListFutures(TrieImpl.java:198)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:157)
        ... 17 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.ethereum.util.RLP.encodeList(RLP.java:1075)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:169)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:172)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:165)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:165)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:165)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:165)
        at org.ethereum.trie.TrieImpl$Node.encode(TrieImpl.java:165)
        at org.ethereum.trie.TrieImpl$Node.access$200(TrieImpl.java:65)
        at org.ethereum.trie.TrieImpl$Node$1.call(TrieImpl.java:146)
        at org.ethereum.trie.TrieImpl$Node$1.call(TrieImpl.java:143)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 common frames omitted
09:01:11.341 ERROR [sync]  Block dump: f924bcf90219a0ba85ddd59c2a1071093f84215e58483f8773d4fcecc272f8ef5fda5b2501ea6da01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347945a0b54d5dc17e0aadc383d2db43b0a0d3e029c4ca002402f93ba87006e96e38cdae51601a85db5957e4746db2ab4e38ba1669ba19fa025f7dc0a58af50bc2bf0fe483483e21143d2c59e425537092665311cd34d1a2fa0fb5f7d3afbabee5c506db78f98fad4a3e16a8f7181c39f0cc4099bb502158a82b9010000128000844900160003000000100800a1000004800001004c14840000a04988000203800420000008000510004001000020802000001c0000000000022000e0a40004402800202000104008300000001220020104000080222040008000000004008128024020401010002400080480042000000a058000270001114200a0122000d000003000808008000000208010240090010080109088020000010404102200000240000000049010050000001600006c0100028000001180c40020880040024012000000001042000602004401801100048009000000000000000400010098000810148000400200040000000440310000022002c4022080400800420087053a89a197f93a8344a6ee83666c48832086e08459ffe4c4984554482e45544846414e532e4f52472d4430464143443442a0d4cd71086ec797f8f2af9f2d369d16b213bb62a4771e326a949845d213188b4d88eaa2720c1ba61e3ff9229cf8aa5c850df847580083017900947728dfef5abd468669eb7f9b48a7f70a501ed29d80b844a9059cbb0000000000000000000000004529c711cd31e090372584e53aeb499061c50d070000000000000000000000000000000000000000000000000000000430e23ada25a0d853a78af95241d8b9c6ce50c18936e84bb03c6b0b7f1b1fd15c023a7aad7b11a02859a93d8ae7d2b624d7de02972bf0134f8cf1b735a5519800c52ea557a3e396f86e820705850bdfd63e00830249f094c85788e87585fbd54a701b8cbdc0da275466e88f872386f26fc10000801ca0593c62061d2134e1045a3c9fe6c3b33288a3f368abeb64b70f4420c6f547bdefa06a3df11dcdb09779794baca7b6ab626294a6dbd59bf2012a32e3279f1e24d139f8ad8306727e850ba43b7400830249f094a74476443119a942de498590fe1f2454d7d4ac0d80b844a9059cbb0000000000000000000000007e710249d3d7499330a73c260cb29775a72800c400000000000000000000000000000000000000000000002f03ff486d58a8800026a00a6f28439e555c685a7d5482830af6db88f2e838e24f23b89fb2067ff96c0479a07ebcf629ca737f120f01e6e043aefbbc8623f22e77a1a6a7cdd1a6837063515ff86f8244be850ba43b740083028b0a94e14d80ef2392080276218126b7ecb95d691d839b8806952bfcad7f28008026a0e7c07c89dce97d1a99dbb4a37c4f6bdcbd8ea12bdd1adefa9fbf1f1e4d71e92ba0544c7e12f01c1beb7354e06de75a1775d895ecbd5ab077c6a9728e50d0549102f86d3a850ba43b740083028b0a94f5bec430576ff1b82e44ddb5a1c93f6f9d0884f388015cb7533b4738008025a0ced799b938b9dbe728747fa7ec911f693f43a9575ab6444860697db26d8f5013a06f95520d04d85ff15da0034d71f89a3cb42f843c5eb3935c6d337d60c5fdcc14f8a90f850b68a0aa0082ccd4948f8221afbb33998d8584a2b05749ba73c37a938a80b844a9059cbb0000000000000000000000000c977942f7eec9119a939e0c9443a16dc9764bc400000000000000000000000000000000000000000000013fdae73a7345ac800026a0e4895572290e86d43c558f19114eefc831df01e1b649fec652913784d1a914b0a05edcb80238f78e280f377596883a86fb3337fdc6f1e4599ad353429d580bc553f86b688506fc23ac00825208947ed1e469fcb3ee19c0366d829e291451be638e5987b0bb6d2980c9f88025a0a3fcf562b1b59f578335101b10b57e1bcee3889d9e87c3730dad6c6a71d93b3aa07b53da786a55f5f33953f78494c3081ba72617425cb9a1acf0326769ddc561caf8aa188505d21dba00830186a094595832f8fc6bf59c85c527fec3740a1b7a36126980b844a9059cbb000000000000000000000000a4648f340c595e45bacd9660a688963260c2252900000000000000000000000000000000000000000000000000000002913f2fa325a0d118db90179e32f126bdf868f961a258222cb9a8a34fb0664bc24fbb1fd43f24a027494f7b38edf8d2ccf900c37e287591e9e21fe9927c5811f19d61b74088323ef86f8203e785051f4d5c0082b7a0946fc82a5fe25a5cdb58bc74600a40a69c065263f88902b5dc65887a2b0000801ba0a8d6204b5804bc696f7ea4bf19d1f7707be6492542d1062ced0bb5717020e638a033e45f3a4eb6a8dd04b7efb31e22341cf883892ed3640226cd592655809460bef8ca4a8504e3b292008307a120946090a6e47849629b7245dfa1ca21d94cd15878ef80b86447872b4289f858c4f8c12d0a3611719f719bc4b388f1baf53a51c38fa0e4f94e652076bc000000000000000000000000000000000000000000000000002386f26fc10000724f6bdc92705714b251fdfe205b952f71c1b25dac823eb448ff509b43ca200526a0fdb19cd697a625dc59c51634828e01fab195a2167cb022f2a5970f0b8d910047a06902b2eceba7a7e039b173b27b3386fb8f9115bf3a5b827e04bd61560f33bdb9f8aa068504e3b29200830162359481be91c7e74ad0957b4156f782263e7b0b88cf7b80b844a9059cbb000000000000000000000000f7dc53864e9d19e03d5b3ae31c7c44996581714f0000000000000000000000000000000000000000000000000000000002faf08025a0b5379d15bb0c9eaaf93ddf1959542b6e3a6af97bc1d0c926eac3236c385b08c2a05479c76f0587f7f81238b758d4a0401754132d67f3d83defaa00f79657b55891f8b1068504e3b2920082cad194d0a6e6c54dbc68db5db3a091b171a77407ff7ccf880de0b6b3a7640000b844e0cb3aa00000000000000000000000000000000000000000000000000000000000000086000000000000000000000000000000000000000000000000000000000000000026a06458f4505df036d5351b505767e9914100b9d0edaaf4ac23ddde039a0e1d46d5a034bd6a977d6a1dd3f43eb34aaa4bdb26c9ee33ea38c2fde6ecdf893e1bc4522df86c7a8504e3b292008252089479b5033f64e9f43469dd02a2d1beb273e80529c58802386f26fc1000008025a045398b45dc214e7337a39f792497f60515ce977ed894d43c4753521b592583c9a0300f66cecfacc80d9b42f89695a34c8bbaf44c83b8ef898cde22706ee41267d5f86c018504e3b292008252089409a5e54729b72aa51020b1d74d14ba35d3ef51cb880383c1c14b5b4000801ca0a757e404e716286a76826b7abea68de7a9636a50edf5cf8b9b3c33961ecb51cca072197c8c8af13e2b1f2a8a851d5088f0b26db750295bcef55bba857f991c0ef2f8728201d28504a817c8008303d090948d12a197cb00d4747a1fe03395095ce2a5cc6819880de0b6b3a764000084d0e30db01ca0a5674a00c622364f2c391214bfb17530f8a904e6aeba8e75fe221f4da10a949e9f912929d7e527be4dfcefec754a28d36bbab84b71ad59103803706ca7e270ebf86d808504a817c80083015f90947b30f44301bc2d6f176bde03167db7255c75eeb2880f43fc2c04ee00008026a074e6f463c467fdb73891f78399d6a8a788de8502fd18edd2ec05f40f247c86c0a03be9ea7960a7e8515e901eb7bb2837dee1ccdc85276eb6ded35dd6a59a62211ff86c808504a817c8008252089470faa28a6b8d6829a4b1e649d26ec9a2a39ba41388c2487fd648a9b000801ba0ffbaba98ac8aaea9cea084adff9587d1da311d4462ff53daee3b6fafd62d1f26a072099404fc23104eb52a75f487722b48e997acfb60e73c59f9ac31989194eebff8a9808504a817c80082b45094ced4e93198734ddaff8492d525bd258d49eb388e80b844095ea7b30000000000000000000000000a7cb7b6cafa02e0684124908ce0b602536a126b000000000000000000000000000000000000000000084595161401484a00000026a0c2600c285633c7c7062b60be54a1856993044144fb2427239302e736445daf38a015b893d75d955a20e7825b87dd5fd226bfdf3511f2f81a5b4156dca047334f1bf86c808504a817c8008252089470faa28a6b8d6829a4b1e649d26ec9a2a39ba41388393ac59467e4e000801ca0972c7fbda7644bd391481334e1dac5242bfd165e37ff81726491d23e96199b8da04efbffac838e7299c94fbbe963af7a26e417f00d6e11529e5bc25febba5e0475f8ad83239d068504a817c8008302db1694d26114cd6ee289accf82350c8d8487fedb8a0c0780b844a9059cbb0000000000000000000000005e44c3e467a49c9ca0296a9f130fc433041aaa280000000000000000000000000000000000000000000000260cd1bb2ca6ae000026a08685a30023b69a7a48d3523356e43d9fa9f18b5babe8131c9fcf2618c836f5cba04cf4693144665034a077cd4aa81b4747aaafabb44c7fde1b6bf7ae4fbcd8be44f86e8263ee8504a817c80082f80c94be6c6a8ba67f8a36c2b36674268cac61e97e9b64885029b17b4076e8008025a07fcc8998224be7d90566beb770a23dc79ae69d540bc1080a20f2eec90f291e55a02a1ca62bcdb84ad6cc95964dc5abe9f9af2e39d4e3e231ccb6db229896174dc6f8ad83046ce28502cb41780083015f909486fa049857e0209aa7d9e616f7eb3b3b78ecfdb080b844a9059cbb000000000000000000000000cd1672a4e0f7afee8db53e6137d130785629edfe0000000000000000000000000000000000000000000000274c493335902c000026a0badf6b00ee062c907bf9d753163a15d9fb6286493fe3f1892ac892dca729c39ba024db798422a8c4519b1e5d17e433b17d17c4ea6bfdd906055ab0635fc8ce7508f86d088502540be400830249f0945ab1ca2be913512f96b1e134a85e328002c2324f88026db992a3b18000801ca0c937ab78544cfce8b8c93bbf331932e2daa233aba7f29c7cc6fce62643ecb06aa03a48821c4a26677335283cc2f8b3d4df1c473fdf537c9d81ce072e923cc9be16f86d82cb1d8502540be400827530941ea6f84e1c10b840cccd29b8f395f5b30fdecf368708dc225f53a000801ba0cbd66ef68edef66ac585afff2856f737249d9343219af4097962ecfb6df605eda054c0585ab349fa06d124615f1e05b06818267540dabe682568e02172230390f5f86d82d71b8502540be400827530945d319f4afed0fbecfba17444d321549bdf9496b1870cd4d717a0d000801ca0baaf26f37da9e862b6d8fdeab47f1666d62928b4d87c2d4b8d6872fb325bf0e9a0354e93d16be3735906415fee7f2332499a993be79ac23871ae77d499aebf8821f8ac820169850218711a008303d090948d12a197cb00d4747a1fe03395095ce2a5cc681980b8449e281a980000000000000000000000004dc3643dbc642b72c158e7f3d2ff232df61cb6ce00000000000000000000000000000000000000000000006c6b935b8bbd4000001ba0482c81dd1575c20836146bd92c7efc2735e020e76f22b184e932c4666473552ea01aecf08d2dd2dbf8adc119e3107fee4b3c18b9e714828b00736004d347941b52f8ac82c94e8501dcd6500083015f909482665764ea0b58157e1e5e9bab32f68c76ec0cdf80b844a9059cbb00000000000000000000000086029d7c198d57ecfa3a7e5a41b71b8b203c6d71000000000000000000000000000000000000000000000000000000000000002e25a0ccbf5a2aa46101baab50b938cf1089a5a82bf17096c28a24a0edcf93713d6e87a01d94300edfe88b5bed722c6268bd49a48a643f70bb9f6cf943fe0ba0d05efe94f9042d8202bc850165a0bc008303d0189409678741bd50c3e74301f38fbd0136307099ae5d80b903c48eb4e0ad0000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000240000000000000000000000000000000000000000000000000000000000000028000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000340000000000000000000000000000000000000000000000000000000000000038000000000000000000000000000000000000000000000000000000000000000011951ae15a4d544cb84fbbfc105363bfb000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f29d7c47dfce00bb1d398a9a9a2a4bf15b45bad60000000000000000000000000000000000000000000000000000000000000001000000000000000000000000ae61a5c6dd55c540d82de4cb656d91a9ae537150000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000006ff0790629e200000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000006fc23ac000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000001bb73cf94d5e3033607f3f8ecca9bad92699dfde3cd5aace2ab04d9c9ff38aa7e00000000000000000000000000000000000000000000000000000000000000013739b6dcb1ba8a9606c1be15f046659983d9171836afbd8364e3ae6b965aef1f000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000051ca062c034a6d346503e0d654445467dc2395c4b6d28e31c5f12407fa9b7b823ae2ca0702ef61c5ac3817b9892565a25a3e41a60bfa3e86bce35a7087d074dfc2983b8f8a98084ee6b2800830249f09428c8d01ff633ea9cd8fc6a451d7457889e698de680b844a9059cbb0000000000000000000000004b01721f0244e7c5b5f63c20942850e447f5a5ee0000000000000000000000000000000000000000000000000000000000003e4b25a06a1fc9b70ca42d1299b4893a9cb7a6b6b10619a1182d9f194d2b8dba3384353ca063e4d78d9f98db62666c230fe684036c470032f5561944dfe797b6aca8172c24f9018c820aff84ee6b28008303d090948d12a197cb00d4747a1fe03395095ce2a5cc681980b90124278b8c0e000000000000000000000000e41d2489571d322189246dafa5ebde1f4699f49800000000000000000000000000000000000000000000065a4da25d3016c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f1e3cca6e30f0000000000000000000000000000000000000000000000000000000000000044be6f00000000000000000000000000000000000000000000000000000000e7b8779b000000000000000000000000000000000000000000000000000000000000001cca735edc3457df255867fcb023c7ed10e0e198538b4f0070dc528de2f9a62ff90ccf7922ac1ab9595ab987cc1bfa07e970b0016e0d233fa9e63e4638e963deb81ca0124bba8a6725d61bde75876b08e44dd155d918fb1a339d9834649b43ff9546bba03146d37e6fd4b48af3b823545fe93582791c1d7ea9751e433c03744693ea6d66f9018c82027f84ee6b28008303d090948d12a197cb00d4747a1fe03395095ce2a5cc681980b90124278b8c0e000000000000000000000000a9aad2dc3a8315caeee5f458b1d8edc31d8467bd0000000000000000000000000000000000000000000054b40b1f852bda0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000125cf363aecc00000000000000000000000000000000000000000000000000000000000000dd3bfa00000000000000000000000000000000000000000000000000000000f7f9d88d000000000000000000000000000000000000000000000000000000000000001b6e54b9fa0b4fdb9a10b507b18e1d592eca0711fe91fdbc8872468f1d6a94f75d683e1b33401a6a84b576934d147178a1cc63991a379befd53a207c8e2c1571f81ba08fcf0f9dad28d11c8024203c6283731a4c2ed4ad4fe2e4b26cd1c9d627b560efa02dfd2db20613e5f8cf62a95af7772dc4989b98c50f577ce404913a4785f4c1d4f8a98084b2d05e008303d09094f845e6443e0b6f21885648ae64c6a801e2b37b5e80b844095ea7b30000000000000000000000008d12a197cb00d4747a1fe03395095ce2a5cc6819000000000000000000000000000000000000000000000012f939c99edab800001ba0f40e2359624a9382131eda82ca2c5c0fb68e16036188d9877d94411ffd69e465a03f3089f89b8165b6e423bdd725cfd5403519a7c1449bbcbb06a8df8a8067f0faf8a82884b2d05e0082c89394afc39788c51f0c1ff7b55317f3e70299e521fff680b844a9059cbb000000000000000000000000c857b69d79ff5f975b116266192ec4ca67e09626000000000000000000000000000000000000000000000000000000ba43b7400026a0d065c577195bacc2ddb74fb29d74f7144244ceaf921855d71f2a980c32b618cba009b2563727e51ebf6b4275ab62f817d3c1868efec06d5c27adf6943efc98f862f88802843b9aca008303345094561c7d8fd30d7e555ac86395af1d6ce67d8268e780a40121b93f000000000000000000000000000000000000000000000000000000000000000126a04636e3d483e3dea08768bd51ef537c9fa7923920e01eab5ae2aa8472a02d75f7a06fcfb6bfc1e3f1696817fed93e2c9dfec7de258f1537a63dbfb59440259a80f3f87024843b9aca008301422994f2fbb2939981594e25d93e6226231fcc1b01718e8829a2241af62c0000843290ce2926a036686344f3433c771f2123f84a4198662b8d86810ae2739a69e772d2abe4afe1a0539fe58957a49a0676c306f2bb5dec359e8e37687262e33bbbbeed10a155f16df86b8238a9843b9aca0082520894e5847f0e18bde5e68bc02ad6f6f2b54eadc7cb27865af3107a40008025a0d355fbf3af08708ee3da264784a533ce137ae651395ca7838de1e251c5b62a1ba0383343fa2bcdd6471c638a9aec1cdd87f9606d741954fdd88f510e96dc73acecf8ab820960843b9aca0083012f4e947b1309c1522afd4e66c31e1e6d0ec1319e1eba5e80b844a9059cbb0000000000000000000000007659f5dcd00a821db1a4cb254c5c81939734ad1c0000000000000000000000000000000000000000000000015af1d78b58c4000025a0556404748ed9f8e7b48632b5d0133c6ebabe87ebe7ba1212fbb5857099ceda1da00506c752a86cf798d3c1343c36500b092e65048e5532b0f857f919aa5c5a0433f8ab821e7a843b9aca0083030d4094c3972ac283b3a7a56125674631a5c254f7f373cf80b844a9059cbb000000000000000000000000edf96d80281019a6735968316c57bcc3a271abc500000000000000000000000000000000000000000000000000003b1dfde910001ba066ecdfaafaab285c7722e4f1f8b367e475a0d85b52bfc50476d805108d2142f5a0382a7bf766e32b3b72341138eb758fa1bf2267c29856c44497dab1b9bff3df3cf9018c82025f843b9aca008303d090948d12a197cb00d4747a1fe03395095ce2a5cc681980b90124278b8c0e0000000000000000000000009b11efcaaa1890f6ee52c6bb7cf8153ac5d741390000000000000000000000000000000000000000000000000000032ee841b8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000246ddf9797668000000000000000000000000000000000000000000000000000000000000044cd0d00000000000000000000000000000000000000000000000000000000878765a0000000000000000000000000000000000000000000000000000000000000001bf9f2ad5347b78102fa76ff51eccf6f0829363733f9da30d409dc316910320fde21ecba6233a376ebb28511921fb85e5f01ec3968ca88f51fe0c6aea58eb79f0526a041cadca1810ce03a43b15d41a7d82bbeb0adc87ed408c8208ed9e76605c49c3ca033cd5446e2a1b15d46bc89b047357d6811ce6c3adb4371d92d1976216aab352ef88a820543843b9aca00830186a094f44072eda87ede9613b6ae1b812de8a60ade27a280a42e1a7d4d0000000000000000000000000000000000000000000000001bc16d674ec8000025a06585592ce412a0989c13bfec95929d08933f9e213af7ffcaaab73e5c1a6b95ffa05f5f0a83d2ed569d4ebc763070e60f00c6e01c82489e511ce75adea43f4f2c3df88811843b9aca0083022234946090a6e47849629b7245dfa1ca21d94cd15878ef80a4983b94fbe864d0d8a5d14fcd6e82eb5cebef132f12f86d885279cfe30f64207aaed2d1a626a0a30f36aac14c9390cd48a976662831b1295cb6f7d470a503504d1245b1cc41dea06b24c6c4e2a1134b7a8b837dd1fad4d93e567b940b24080c0dac12f5c8197ed7f8a920843b9aca0083030d409424692791bc444c5cd0b81e3cbcaba4b04acd1f3b80b844a9059cbb00000000000000000000000030129d90f969857f52e9a2f0a896dc44079e3e80000000000000000000000000000000000000000000000042ea2fa814972c000026a0341337df5aa30c3c74da423255610044bbc6783d73a47d8bf42239ae4d9b29aaa06d9da47238a07ba9bf015867f39ad5516d4ad79bccfe652a0c0c6821d00560c9f8ad8306727f850ba43b7400830249f094744d70fdbe2ba4cf95131626614a1763df805b9e80b844a9059cbb00000000000000000000000033eaadbbfeaa998b834f6bb89748ee5c76cdfd3f00000000000000000000000000000000000000000000011e9d38000d22c2a00026a06bfe110c38aeae65d65fb787d90488b17069891a61f1c3f9d072d373de50242aa001a37dbb42de1c3c28ea421685586e0370175d8bf8d3f44a09552ba82238ed9ff8ad83239d078504a817c8008302db1694d26114cd6ee289accf82350c8d8487fedb8a0c0780b844a9059cbb0000000000000000000000005e44c3e467a49c9ca0296a9f130fc433041aaa280000000000000000000000000000000000000000000000260cd1bb2ca6ae000026a02293a24c38283df8c92012f64458a8c859e384e3f5c9b0bfae159050a58680e8a054f98f8cb8cc723cf1257baaed6dd6da8574eef1fc60605b07493439d75b4ee7f86f83046ce38502cb41780083015f909413851d5bea6c8b95e9637786225df6f8e2eff7a8878ce801872d5c008026a098b4b7de166980fb5214bf7ca1871e00b767c86db063aa094dc48cde0e31d72da013b3eaa097b4fa99fc8c1db4da244216f73cf2f0ab406b90486458e50152682df8a90184b2d05e008303d090948d12a197cb00d4747a1fe03395095ce2a5cc681980b844338b5dea000000000000000000000000f845e6443e0b6f21885648ae64c6a801e2b37b5e000000000000000000000000000000000000000000000012f939c99edab800001ba092b4133294525b1dc2e61e599ef0c9f5470c161258c3b3c022c9a97bef29392da04634411af1dc1392bfd5157a499e2b5f081751b0e156ee905902b654e7fa1457f86b8238aa843b9aca0082520894fe381fc04165a37192d760ff1998650eb36719e9865af3107a40008026a045658b27e408fd6d7cd494a07f4fc84a5bc6463ef86aedd075945d1e66ca8fa1a06db58f92c80037a9bb220dc544ac1aa1b54545ba13fc529f6bdab757ed4c663cf8ab820961843b9aca0083012f4e947b1309c1522afd4e66c31e1e6d0ec1319e1eba5e80b844a9059cbb000000000000000000000000e8806160504279568399482324036a28bcc90c7f0000000000000000000000000000000000000000000000015af1d78b58c4000026a0698f6c0671fa23c04b69639ce9ded387fd3f7177b12506a1a2b3f6400bea5c28a009298cdd2c3b57e9c19a0c584b446b91c736aec8d637552e940a96347b159735f87083046ce48502cb41780083015f9094411fb52ab38c5bdfa948487bdc7cd7c3923a67748803048e478e30a0008026a021461eab215af5ae95c07e7086749f651b7cd490028ca682a68d8c8340056c42a023ad8dd5d6a0986fe8a5f032beb91393b2cf37bf37470dd2c75a2a8be8e9326bf86b8238ab843b9aca008252089434678e1f4d157e4e2cde261706ed8f0fd38f6c34865af3107a40008026a082c1390b99899c67bf2133fb48dd95e11d33a555ea2a58ff1a5054ae42f290eba0658aabba7fbfbd87147caf5469aeaddb2426d276ae6951456c8d2acf21a2a8a1c0
09:01:11.386 ERROR [sync]  No parent on the chain for block.number: 4499183 block.hash: 07f978
09:01:11.411 ERROR [sync]  No parent on the chain for block.number: 4499184 block.hash: e1679f
09:01:11.431 ERROR [sync]  No parent on the chain for block.number: 4499185 block.hash: 89ef1c

**Comment by mkalinin** [comment]
did you update EthereumJ to the latest version?

**Comment by vikulin** [comment]
Yes, I did. used latest develop branch code (last update 10/29/2017)

2017-11-06 14:46 GMT+02:00 Mikhail Kalinin <notifications@github.com>:

**Comment by mkalinin** [comment]
pls, try `1.6.3-RELEASE`

**Comment by vikulin** [comment]
Are you going to fix it in develop?

2017-11-06 16:44 GMT+02:00 Mikhail Kalinin <notifications@github.com>:

**Comment by mkalinin** [comment]
Fixed
