### ISSUE TITLE
can not find method to connect with contract

### ISSUE THREAD

**Issue by ADifferentChenYun** [ethereum/ethereumj#960]
is there any method connect with contract or call contract method

**Comment by mkalinin** [comment]
Check `CallTransaction` code. Maybe it will help in your case

**Comment by ADifferentChenYun** [comment]
is there any method like "web3.eth.contract(abi).at(address)"

**Comment by mkalinin** [comment]
there is no method similar to `web3` one. but you don't need it for interacting with contracts

**Comment by ADifferentChenYun** [comment]
thank you
