### ISSUE TITLE
transaction gas calculate bug?

### ISSUE THREAD

**Issue by lyless** [ethereum/ethereumj#961]
i use the transactionCost method of Transaction class to calculate the actual gas spent for transaction, and i  found some transaction gas was not same as etherscan.io 
for example. this transaction 's gas is 21051.
https://etherscan.io/tx/0x2c6d61dca2b10703ceeb7801cb4fa4da6f85f39db8b809013e9c18a07eff450d

and i use the this code to calculate gas of binary transaction . result was 21000.
21051 and 21000 which one is correct? 

`        String rawTx  = "f8708201b4850df8475800830f424094663a7c8694210ca7326b72f1f68c1000d7a5db1189014d1120d7b1600000801ba07b38b108311ae2405d9130fe2c9f7f2696582850e9d1d7921166412e0e6d66a0a07c9c1ad1c7f5c0ea8752e68707423392d4319f74d3924b8835ef09465d64aade";
        String txRoot = "b7bf3571d3783e8b0f720d44ffc0662b27e26c62f59457b1c7d7109f44f0c194";
        Block b = new Block(null,
                            null,
                            null,
                            null,
                            null,
                            4521985,
                            null,
                            0,
                            0,
                            null,
                            null,
                            null,
                            null,
                            Hex.decode("b7bf3571d3783e8b0f720d44ffc0662b27e26c62f59457b1c7d7109f44f0c194"),
                            null,
                            new ArrayList<>(),
                            new ArrayList<>());

        byte[]      bytes = Hex.decode(rawTx);
        Transaction tx    = new Transaction(bytes);
        long gas  = tx.transactionCost(new MainNetConfig(), b);`

**Comment by mkalinin** [comment]
`tx.transactionCost()` return basic amount of gas for the transaction which is spent before any code is executed. etherscan.io shows you final amount of gas that has been spent during transaction execution, this value also includes amount of gas spent on code execution.
