### ISSUE TITLE
Mismatch in difficulty calculation when comparing to block on mainnet 

### ISSUE THREAD

**Issue by weisheme** [ethereum/ethereumj#965]
@Nashatyrev I’ve continued writing tests mostly around the soft- and hard fork rule changes in org.ethereum.config.blockchain. I’ve created a test for ByzantiumConfig and decided to take a real life case from Etherscan.io.

I took parent block https://etherscan.io/block/4490788 and current block https://etherscan.io/block/4490789 as random samples, and created a unit test
1. Exact timestamps (in seconds) and uncles so difficulty multiplier is triggered
1. Exact block number so explosion is triggered correctly

My assumption is that, based on above scenario, a call to `#calcDifficulty(current, parent)` returns the minimum difficulty, which is `1,378,600,421,631,340`. This minimum difficulty should be lower than the actual difficulty of the current block on etherscan (https://etherscan.io/block/4490789). However, this doesn’t seem to be the case because the actual difficulty is `1,377,927,933,620,791`, which is lower than the minimum difficulty.

For completeness, unit test code can be found here:
https://github.com/ethereum/ethereumj/compare/develop...weisheme:increase_test_coverage_fork_config_rules#diff-9da1b488937c9a800cd17874c886315fR86. Name of test method is `testEtherscanIoBlock4490790`.

What’s wrong with my assumptions? Am I perhaps passing the wrong parameters to `calcDifficulty()`?

**Comment by mkalinin** [comment]
I don't get what exactly confuses you. Could you pls clarify what minimum difficulty is?

**Comment by MysticRyuujin** [comment]
I'm not sure if I should open a new Issue or report here as this seems related, but Ethereum-Harmony (ethereumj?) seems to be reporting a different difficulty than Geth and Parity. Check it out:

![difficulty](https://user-images.githubusercontent.com/8877131/37865799-abe93662-2f4f-11e8-9db2-336a6a9e88c2.png)

My Geth and Parity nodes are reporting `3.2356092555165853e+21` give or take, but Harmony is reporting `14,958,892,774,765,636,000` give or take

**Comment by mkalinin** [comment]
I am not sure that @weisheme and @MysticRyuujin described the same problem. I will investigate in second one, cause it looks clear to me.

**Comment by mkalinin** [comment]
@MysticRyuujin I opened a bug https://github.com/ethereum/ethereumj/issues/1041
