### ISSUE TITLE
Is there any rule of proguard ?

### ISSUE THREAD

**Issue by weichin0220** [ethereum/ethereumj#968]
Warning:org.ethereum.config.Initializer: can't find superclass or interface org.springframework.beans.factory.config.BeanPostProcessor
Warning:org.ethereum.facade.EthereumImpl: can't find superclass or interface org.springframework.context.SmartLifecycle
Warning:org.ethereum.facade.EthereumImpl$1: can't find superclass or interface org.springframework.util.concurrent.FutureAdapter
Warning:org.ethereum.mine.AnyFuture: can't find superclass or interface com.google.common.util.concurrent.AbstractFuture
Warning:org.ethereum.net.eth.handler.EthHandler: can't find superclass or interface io.netty.channel.SimpleChannelInboundHandler
Warning:org.ethereum.net.p2p.P2pHandler: can't find superclass or interface io.netty.channel.SimpleChannelInboundHandler
Warning:org.ethereum.net.rlpx.HandshakeHandler: can't find superclass or interface io.netty.handler.codec.ByteToMessageDecoder
Warning:org.ethereum.net.rlpx.MessageCodec: can't find superclass or interface io.netty.handler.codec.MessageToMessageCodec
Warning:org.ethereum.net.rlpx.NettyByteToMessageCodec: can't find superclass or interface io.netty.handler.codec.ByteToMessageCodec
Warning:org.ethereum.net.rlpx.NettyByteToMessageCodec$1: can't find superclass or interface io.netty.handler.codec.ByteToMessageDecoder
Warning:org.ethereum.net.rlpx.discover.MessageHandler: can't find superclass or interface io.netty.channel.SimpleChannelInboundHandler

**Comment by mkalinin** [comment]
can you provide more information about your case?
