### ISSUE TITLE
Mining on an account

### ISSUE THREAD

**Issue by cadam7** [ethereum/ethereumj#971]
Hi! I just started a new project and I want to use ethereumJ in it.
I am curious how to create an new account with some password programmaticaly, get its private hash and start mining on this account. I did not found solution jet and I hope someone can help because it seems to be some common issue...
Thank you in advance

**Comment by zilm13** [comment]
You'd better try [Ethereum Harmony](https://github.com/ether-camp/ethereum-harmony) it's the app made around EthereumJ library for end-users. You could find some helpful info about using it for miniing in its Github Wiki.

**Comment by mkalinin** [comment]
@cadam7 can we close this issue?

**Comment by cadam7** [comment]
Yes, i forgot about it, sorry

2018-03-13 12:17 GMT+01:00 Mikhail Kalinin <notifications@github.com>:

**Comment by mkalinin** [comment]
no problem, just was wondering if it's still relevant
