### ISSUE TITLE
Strategy interface for getGeneratedNodePrivateKey()

### ISSUE THREAD

**Issue by lucassaldanha** [ethereum/ethereumj#972]
There is a TODO on the test `testGeneratedNodePrivateKeyThroughECKey` on the class `SystemPropertiesTest` to create a strategy interface for getGeneratedNodePrivateKey().

```
/**
 * TODO: Consider using a strategy interface for #getGeneratedNodePrivateKey().
 * Anything 'File' and 'random' generation are difficult to test and assert
 */
@Test
public void testGeneratedNodePrivateKeyThroughECKey() throws Exception {
    ...
}
```

I'd love to get someone to review my PR and come with suggestions for improvements.

**Comment by mkalinin** [comment]
@lucassaldanha btw, did you finally create a PR? Sorry for late response

**Comment by lucassaldanha** [comment]
@mkalinin I had, but I closed it some time ago.

Anyway, I've opened a new one: https://github.com/ethereum/ethereumj/pull/1104

Cheers!
