### ISSUE TITLE
how to verify  between private key and ethereum account address

### ISSUE THREAD

**Issue by ADifferentChenYun** [ethereum/ethereumj#983]
I have an account address like "0x4eb60bfab454b5aaece4e8759e62ed36266fde39", private key file like "UTC--2017-11-13T03-24-42......" and the seed  password like "123456789" ,but  how can i verify the pair of address and the private key file is  matched.
thank you.

**Comment by zilm13** [comment]
It depends on the software that made private key file. Is it EthereumJ?

**Comment by ADifferentChenYun** [comment]
I figured it out， i can do this by web3j like "WalletUtils.loadCredentials()".
thank you
