### ISSUE TITLE
load config error

### ISSUE THREAD

**Issue by leo-zheng** [ethereum/ethereumj#987]
InputStream is = getClass().getResourceAsStream("/version.properties");
maven project, import another jar which include the file named version.properties, we will load error config

**Comment by zilm13** [comment]
@leo-zheng Could you explain in detail how to reproduce this bug including version of EthereumJ you used.

**Comment by leo-zheng** [comment]
[bug.docx](https://github.com/ethereum/ethereumj/files/1611733/bug.docx)

**Comment by zilm13** [comment]
@leo-zheng thank, I confirm the bug, web3j contains version.properties file too and it's loaded instead. I've submitted PR to fix it.

**Comment by zilm13** [comment]
@leo-zheng you can use 1.7.0-SNAPSHOT with fix in it or wait for next release version

**Comment by CaptainJno** [comment]
version.properties still exist, so does the bug
