### ISSUE TITLE
Issue Compiling with IntelliJ (Lombok plugin)

### ISSUE THREAD

**Issue by ajlopez** [ethereum/ethereumj#996]
I had an issue compiling with IntelliJ. The first time, it didn't work "log variable undefined". Gradle command line build, worked.

Then I found that the Lombok plugin should be installed, and the annotation processing should be enabled.

Could you add the solution to README? I could write a pull request, by English is not in my skills ;-)

**Comment by mkalinin** [comment]
are you sure that EthereumJ depends on lombok plugin? maybe you're talking about Harmony?

**Comment by ajlopez** [comment]
Sorry, my mistake... I will add this issue to the other repo

**Comment by mkalinin** [comment]
Substituted by https://github.com/ether-camp/ethereum-harmony/issues/55
