### ISSUE TITLE
Improve Fastsync begining

### ISSUE THREAD

**Issue by zilm13** [ethereum/ethereumj#997]
Currently starting of fast sync process is very slow, we need to choose initial pivot more accurate when it's availability is guaranteed by more nodes.
For example, we could start when we 5 peers which were able to response on 1 node request successfully or smth like this.

**Comment by mkalinin** [comment]
@zilm13 I am not sure that this is still up to date. can you recall the decision we made on it last time?

**Comment by zilm13** [comment]
@mkalinin I think not an issue, we could close this
